### ISSUE TITLE
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

### ISSUE THREAD

**Issue by sahina** [AtomLinter/linter-eslint#100]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.209.0
**System**: Mac OS X 10.10.3
**Thrown From**: [linter-eslint](https://github.com/AtomLinter/linter-eslint) package, v0.5.8

### Stack Trace

Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

```
At /Users/asahin/.nvm/versions/io.js/v2.2.1/lib/node_modules/eslint/node_modules/is-my-json-valid/node_modules/generate-function/index.js:55

EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

  at Function (native)
  at Function.line.toFunction (/Users/asahin/.nvm/versions/io.js/v2.2.1/lib/node_modules/eslint/node_modules/is-my-json-valid/node_modules/generate-function/index.js:55:21)
  at compile (/Users/asahin/.nvm/versions/io.js/v2.2.1/lib/node_modules/eslint/node_modules/is-my-json-valid/index.js:539:23)
  at module.exports (/Users/asahin/.nvm/versions/io.js/v2.2.1/lib/node_modules/eslint/node_modules/is-my-json-valid/index.js:560:10)
  at validateRuleOptions (/Users/asahin/.nvm/versions/io.js/v2.2.1/lib/node_modules/eslint/lib/config-validator.js:67:24)
  at /Users/asahin/.nvm/versions/io.js/v2.2.1/lib/node_modules/eslint/lib/config-validator.js:101:13
  at Array.forEach (native)
  at Object.validate (/Users/asahin/.nvm/versions/io.js/v2.2.1/lib/node_modules/eslint/lib/config-validator.js:100:35)
  at loadConfig (/Users/asahin/.nvm/versions/io.js/v2.2.1/lib/node_modules/eslint/lib/config.js:99:19)
  at getLocalConfig (/Users/asahin/.nvm/versions/io.js/v2.2.1/lib/node_modules/eslint/lib/config.js:225:23)
  at Config.getConfig (/Users/asahin/.nvm/versions/io.js/v2.2.1/lib/node_modules/eslint/lib/config.js:363:22)
  at CLIEngine.getConfigForFile (/Users/asahin/.nvm/versions/io.js/v2.2.1/lib/node_modules/eslint/lib/cli-engine.js:382:29)
  at LinterESLint.lintFile (/Users/asahin/.atom/packages/linter-eslint/lib/linter-eslint.coffee:79:21)
  at /Users/asahin/.atom/packages/linter/lib/linter-view.coffee:163:18
  at Array.forEach (native)
  at /Users/asahin/.atom/packages/linter/lib/linter-view.coffee:162:18
  at FSReqWrap.oncomplete (fs.js:77:15)

```

### Commands

```
     -0:04.4.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "jshint",
      "linter-jshint",
      "linter-jsxhint"
    ]
  },
  "linter-eslint": {
    "useGlobalEslint": true,
    "disableWhenNoEslintrcFileInPath": true
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
Stylus, v1.0.0
atom-beautify, v0.28.5
atom-typescript, v4.5.13
autocomplete-plus-python-jedi, v0.3.6
coffee-compile, v0.16.1
color-picker, v2.0.4
emmet, v2.3.10
language-jade, v0.4.0
language-rust, v0.4.3
less-autocompile, v1.0.0
linter, v0.12.7
linter-csslint, v0.0.13
linter-eslint, v0.5.8
linter-rust, v0.1.0
linter-scss-lint, v1.0.4
meteor-api, v2.19.0
react, v0.12.0

# Dev
No dev packages
```

**Comment by keithamus** [comment]
Dupe of #99. This should be closed.
