### ISSUE TITLE
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

### ISSUE THREAD

**Issue by MoOx** [AtomLinter/linter-eslint#101]
[Enter steps to reproduce below:]

1. Use latest version of eslint

**Atom Version**: 0.209.0
**System**: Mac OS X 10.10.3
**Thrown From**: [linter-eslint](https://github.com/AtomLinter/linter-eslint) package, v0.5.8

### Stack Trace

Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

```
At /Users/MoOx/Sync/Development/cssnext/cssnext/node_modules/eslint/node_modules/is-my-json-valid/node_modules/generate-function/index.js:55

EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

  at Function (native)
  at Function.line.toFunction (/Users/MoOx/Sync/Development/cssnext/cssnext/node_modules/eslint/node_modules/is-my-json-valid/node_modules/generate-function/index.js:55:21)
  at compile (/Users/MoOx/Sync/Development/cssnext/cssnext/node_modules/eslint/node_modules/is-my-json-valid/index.js:539:23)
  at module.exports (/Users/MoOx/Sync/Development/cssnext/cssnext/node_modules/eslint/node_modules/is-my-json-valid/index.js:560:10)
  at validateRuleOptions (/Users/MoOx/Sync/Development/cssnext/cssnext/node_modules/eslint/lib/config-validator.js:67:24)
  at /Users/MoOx/Sync/Development/cssnext/cssnext/node_modules/eslint/lib/config-validator.js:101:13
  at Array.forEach (native)
  at Object.validate (/Users/MoOx/Sync/Development/cssnext/cssnext/node_modules/eslint/lib/config-validator.js:100:35)
  at loadConfig (/Users/MoOx/Sync/Development/cssnext/cssnext/node_modules/eslint/lib/config.js:99:19)
  at getLocalConfig (/Users/MoOx/Sync/Development/cssnext/cssnext/node_modules/eslint/lib/config.js:225:23)
  at Config.getConfig (/Users/MoOx/Sync/Development/cssnext/cssnext/node_modules/eslint/lib/config.js:363:22)
  at CLIEngine.getConfigForFile (/Users/MoOx/Sync/Development/cssnext/cssnext/node_modules/eslint/lib/cli-engine.js:382:29)
  at LinterESLint.lintFile (/Users/MoOx/setup/dotfiles/atom/packages/linter-eslint/lib/linter-eslint.coffee:79:21)
  at /Users/MoOx/setup/dotfiles/atom/packages/linter/lib/linter-view.coffee:163:18
  at Array.forEach (native)
  at /Users/MoOx/setup/dotfiles/atom/packages/linter/lib/linter-view.coffee:162:18
  at FSReqWrap.oncomplete (fs.js:77:15)

```

### Commands

```
     -0:29.5.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -0:29.2.0 core:delete (atom-text-editor.editor.is-focused)
     -0:28.7.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
  2x -0:28.4.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:19.9.0 core:paste (atom-text-editor.editor.is-focused)
     -0:19.6.0 core:save (atom-text-editor.editor.is-focused)
     -0:18.6.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -0:16.6.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:16.4.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -0:16 core:delete (atom-text-editor.editor.is-focused)
     -0:15.7.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:14.4.0 core:move-up (div.terminal)
     -0:13.3.0 core:move-down (div.terminal)
     -0:13.1.0 core:confirm (div.terminal)
     -0:06.4.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -0:04.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "projectHome": "/Users/MoOx/Sync/Development",
    "disabledPackages": [
      "language-mustache",
      "welcome",
      "language-toml",
      "language-sass",
      "language-ruby-on-rails",
      "language-ruby",
      "language-python",
      "language-php",
      "language-perl",
      "language-objective-c",
      "language-less",
      "language-java",
      "language-hyperlink",
      "language-go",
      "language-csharp",
      "language-coffee-script",
      "language-clojure",
      "language-jsx",
      "close-tags",
      "yuno-commit",
      "atom-color-highlight"
    ]
  },
  "linter-eslint": {
    "disableWhenNoEslintrcFileInPath": true
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.5
auto-update-packages, v1.0.0
bezier-curve-editor, v0.7.2
color-picker, v2.0.4
docblockr, v0.7.2
editorconfig, v1.0.0
file-type-icons, v0.7.0
git-log, v0.4.1
git-projects, v1.14.1
git-tab-status, v1.9.2
language-apache, v1.3.0
linter, v0.12.7
linter-eslint, v0.5.8
linter-htmlhint, v0.0.16
linter-jsonlint, v0.1.4
live-archive, v0.1.15
project-manager, v1.15.10
react, v0.12.0
term2, v0.9.9
travis-ci-status, v0.15.1
web-browser, v1.5.0

# Dev
No dev packages
```

**Comment by keithamus** [comment]
Dupe of #99. This should be closed.
