### ISSUE TITLE
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

### ISSUE THREAD

**Issue by alanrsoares** [AtomLinter/linter-eslint#102]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.209.0
**System**: Mac OS X 10.10.3
**Thrown From**: [linter-eslint](https://github.com/AtomLinter/linter-eslint) package, v0.5.8

### Stack Trace

Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

```
At /Users/alan.soares/dev/Timer/node_modules/eslint/node_modules/is-my-json-valid/node_modules/generate-function/index.js:55

EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

    at Function (native)
    at Function.line.toFunction (/Users/alan.soares/dev/Timer/node_modules/eslint/node_modules/is-my-json-valid/node_modules/generate-function/index.js:55:21)
    at compile (/Users/alan.soares/dev/Timer/node_modules/eslint/node_modules/is-my-json-valid/index.js:539:23)
    at module.exports (/Users/alan.soares/dev/Timer/node_modules/eslint/node_modules/is-my-json-valid/index.js:560:10)
    at validateRuleOptions (/Users/alan.soares/dev/Timer/node_modules/eslint/lib/config-validator.js:67:24)
    at /Users/alan.soares/dev/Timer/node_modules/eslint/lib/config-validator.js:101:13
    at Array.forEach (native)
    at Object.validate (/Users/alan.soares/dev/Timer/node_modules/eslint/lib/config-validator.js:100:35)
    at loadConfig (/Users/alan.soares/dev/Timer/node_modules/eslint/lib/config.js:99:19)
    at getLocalConfig (/Users/alan.soares/dev/Timer/node_modules/eslint/lib/config.js:225:23)
    at Config.getConfig (/Users/alan.soares/dev/Timer/node_modules/eslint/lib/config.js:363:22)
    at CLIEngine.getConfigForFile (/Users/alan.soares/dev/Timer/node_modules/eslint/lib/cli-engine.js:382:29)
    at LinterESLint.lintFile (/Users/alan.soares/.atom/packages/linter-eslint/lib/linter-eslint.coffee:97:23)
    at /Users/alan.soares/.atom/packages/linter/lib/linter-view.coffee:232:29
    at Array.forEach (native)
    at /Users/alan.soares/.atom/packages/linter/lib/linter-view.coffee:231:27
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ],
    "disabledPackages": [
      "nuclide-file-tree"
    ]
  },
  "linter-eslint": {
    "disableWhenNoEslintrcFileInPath": true
  }
}
```

### Installed Packages

```coffee
# User
editorconfig, v1.0.0
emmet, v2.3.10
language-diff, v0.3.0
language-livescript, v0.0.2
linter, v0.12.7
linter-eslint, v0.5.8
minimap, v4.10.0
nuclide-code-format, v0.0.0
nuclide-diff-view, v0.0.0
nuclide-flow, v0.0.0
nuclide-hack, v0.0.0
nuclide-hg-repository, v0.0.0
nuclide-remote-projects, v0.0.0
nuclide-ssh-dialog, v0.0.0
nuclide-tabs, v0.0.0
nuclide-type-hint, v0.0.0
react, v0.12.0
seti-syntax, v0.4.0
seti-ui, v0.7.1

# Dev
No dev packages
```

**Comment by keithamus** [comment]
Dupe of #99. This should be closed.
