### ISSUE TITLE
Linter does not work with eslint plugins containing rules written in ES6+

### ISSUE THREAD

**Issue by LegNeato** [AtomLinter/linter-eslint#1029]
## Issue Type
Bug

## Setup

* Using `parser: babel-eslint` in `.eslintconfig`
* Have a local eslint plugin specified in `.eslintconfig`
* The plugin exports some `rules`, that are `require`d in the plugin's `index.js`
* The rules use features that rely on babel transpilation

## Issue Description
A syntax error is thrown when `CLIEngine` requires the plugin:

```js
Error while running ESLint: Unexpected token ).
Unexpected token )
/Users/legnitto/src/pocketship/lint/eslint-rules/warning-and-invariant-args.js:61
        );
        ^
SyntaxError: Unexpected token )
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:543:28)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:234:23)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/legnitto/src/pocketship/lint/eslint-rules/index.js:10:35)
    at Object.<anonymous> (/Users/legnitto/src/pocketship/lint/eslint-rules/index.js:14:3)
    at Module._compile (module.js:571:32)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:234:23)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Plugins.load (/Users/legnitto/src/pocketship/node_modules/eslint/lib/config/plugins.js:128:26)
    at Array.forEach (native)
    at Plugins.loadAll (/Users/legnitto/src/pocketship/node_modules/eslint/lib/config/plugins.js:173:21)
    at loadFromDisk (/Users/legnitto/src/pocketship/node_modules/eslint/lib/config/config-file.js:536:35)
    at Object.load (/Users/legnitto/src/pocketship/node_modules/eslint/lib/config/config-file.js:592:20)
    at Config.getLocalConfigHierarchy (/Users/legnitto/src/pocketship/node_modules/eslint/lib/config.js:226:44)
    at Config.getConfigHierarchy (/Users/legnitto/src/pocketship/node_modules/eslint/lib/config.js:180:43)
    at Config.getConfigVector (/Users/legnitto/src/pocketship/node_modules/eslint/lib/config.js:285:21)
    at Config.getConfig (/Users/legnitto/src/pocketship/node_modules/eslint/lib/config.js:328:29)
    at processText (/Users/legnitto/src/pocketship/node_modules/eslint/lib/cli-engine.js:156:33)
    at CLIEngine.executeOnText (/Users/legnitto/src/pocketship/node_modules/eslint/lib/cli-engine.js:594:26)
    at lintJob (/Users/legnitto/.atom/packages/linter-eslint/src/worker.js:66:28)
    at process.<anonymous> (/Users/legnitto/.atom/packages/linter-eslint/
```

 It works correctly when run via the eslint CLI.

I also can't use `babel-register` to work around the issue in the plugin, as it is loaded in Atom's context and `babel-register` doesn't work there .

## Bug Checklist
* [x] Restart Atom
* [x] Verify the `eslint` CLI gives the proper result, while `linter-eslint` does not
* [x] Paste the output of the `Linter Eslint: Debug` command from the Command Palette below

```json
Atom version: 1.20.0
linter-eslint version: 8.3.2
ESLint version: 4.7.1
Hours since last Atom restart: 0.1
Platform: darwin
Using local project ESLint from: /Users/legnitto/src/pocketship/node_modules/eslint
Current file's scopes: [
  "source.json",
  "meta.structure.dictionary.json",
  "meta.structure.dictionary.value.json",
  "meta.structure.dictionary.json",
  "meta.structure.dictionary.key.json",
  "string.quoted.double.json"
]
linter-eslint configuration: {
  "lintHtmlFiles": false,
  "useGlobalEslint": false,
  "showRuleIdInMessage": true,
  "disableWhenNoEslintConfig": true,
  "eslintrcPath": "",
  "globalNodePath": "",
  "advancedLocalNodeModules": "",
  "eslintRulesDir": "",
  "disableEslintIgnore": false,
  "disableFSCache": false,
  "fixOnSave": false,
  "scopes": [
    "source.js",
    "source.jsx",
    "source.js.jsx",
    "source.babel",
    "source.js-semantic"
  ],
  "rulesToSilenceWhileTyping": [],
  "rulesToDisableWhileFixing": [],
  "ignoreFixableRulesWhileTyping": false
}
```

**Comment by Arcanemagus** [comment]
Are you able to share an example `.zip` or repository so we can determine what is going on here?

**Comment by LegNeato** [comment]
Got a smaller repro, not quite minimal yet though:

https://github.com/LegNeato/linter-eslint-bug

Make sure you run `yarn` in the repo first.

**Comment by Arcanemagus** [comment]
@BinaryMuse I _think_ this is a bug/conflict with `atom-babel6-transpiler`, Atom's compile cache, and how the plugin file is being included. It seems like within the `Task` process `require` is using the fixed version that uses Atom's compile cache... which is what we want for the `Task` files, but not what is wanted for bringing in `eslint`. Is there anything that can be done here to use the "original" `require` for `eslint` (and thus everything it does afterwards)?

**Comment by LegNeato** [comment]
Friendly poke 👉 @BinaryMuse

**Comment by aaronjensen** [comment]
I don't know if it's related, but when I ran into this the issue was that I had a trailing comma on a function argument list in the local babel preset I was using. Removing that trailing comma fixed it for me.

**Comment by LegNeato** [comment]
Anything I can do to help here? This bug basically makes the plugin unusable for my setup.

**Comment by skylize** [comment]
Traced to here in `eslint/lib/config/plugins.js` where it uses `require` to load your local plugin, but any properties in the definition that are functions get silently dropped.

```
if (!this._plugins[shortName]) {
    try {
        plugin = require(longName); // <-- 💩
    } catch (pluginLoadErr) {
```

Definitely looks to me like a problem with Atom's customizations to `require`.

Maybe another ping to @BinaryMuse with this more detailed info will help us get somewhere?

**Comment by UziTech** [comment]
Is this still an issue?
