### ISSUE TITLE
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

### ISSUE THREAD

**Issue by tomaskikutis** [AtomLinter/linter-eslint#103]
Steps to reproduce:

1. npm install eslint@0.23.0
2. npm install eslint-plugin-react@2.5.2
3. vuala

**Atom Version**: 0.209.0
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [linter-eslint](https://github.com/AtomLinter/linter-eslint) package, v0.5.8

### Stack Trace

Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

```
At C:\Work\Dev1\EShop.Client\node_modules\eslint\node_modules\is-my-json-valid\node_modules\generate-function\index.js:55

EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

  at Function (native)
  at Function.line.toFunction (C:\Work\Dev1\EShop.Client\node_modules\eslint\node_modules\is-my-json-valid\node_modules\generate-function\index.js:55:21)
  at compile (C:\Work\Dev1\EShop.Client\node_modules\eslint\node_modules\is-my-json-valid\index.js:539:23)
  at module.exports (C:\Work\Dev1\EShop.Client\node_modules\eslint\node_modules\is-my-json-valid\index.js:560:10)
  at validateRuleOptions (C:\Work\Dev1\EShop.Client\node_modules\eslint\lib\config-validator.js:67:24)
  at C:\Work\Dev1\EShop.Client\node_modules\eslint\lib\config-validator.js:101:13
  at Array.forEach (native)
  at Object.validate (C:\Work\Dev1\EShop.Client\node_modules\eslint\lib\config-validator.js:100:35)
  at loadConfig (C:\Work\Dev1\EShop.Client\node_modules\eslint\lib\config.js:99:19)
  at getLocalConfig (C:\Work\Dev1\EShop.Client\node_modules\eslint\lib\config.js:225:23)
  at Config.getConfig (C:\Work\Dev1\EShop.Client\node_modules\eslint\lib\config.js:363:22)
  at CLIEngine.getConfigForFile (C:\Work\Dev1\EShop.Client\node_modules\eslint\lib\cli-engine.js:382:29)
  at LinterESLint.lintFile (C:\Users\tkikutis\.atom\packages\linter-eslint\lib\linter-eslint.coffee:79:21)
  at C:\Users\tkikutis\.atom\packages\linter\lib\linter-view.coffee:163:18
  at Array.forEach (native)
  at C:\Users\tkikutis\.atom\packages\linter\lib\linter-view.coffee:162:18
  at FSReqWrap.oncomplete (fs.js:77:15)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ],
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "Thumbs.db",
      ".idea",
      "node_modules/",
      "libraries/",
      "tmp/",
      "bower_components/",
      "_DEPLOY/"
    ]
  },
  "linter-eslint": {}
}
```

### Installed Packages

```coffee
# User
atom-handlebars, v0.5.0
highlight-selected, v0.10.0
linter, v0.12.7
linter-eslint, v0.5.8
linter-handlebars, v0.1.1
linter-less, v0.5.0
pretty-json, v0.3.3

# Dev
No dev packages
```

**Comment by keithamus** [comment]
Dupe of #99. This should be closed.
