### ISSUE TITLE
"Path must be a string. Received undefined" in untitled JavaScript tab

### ISSUE THREAD

**Issue by 50Wliu** [AtomLinter/linter-eslint#1037]
## Issue Type
Bug

## Issue Description
1. Open Untitled tab
2. Set language to JavaScript
3. Type something
4. Open dev tools

```
Path must be a string. Received undefined TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:695:5)
    at process.<anonymous> (file:///C:/Users/user/.atom/packages/linter-eslint/src/worker.js:93:26)
    at emitTwo (events.js:111:20)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:752:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by Arcanemagus** [comment]
Fascinating, this _should_ be impossible due to this:
https://github.com/AtomLinter/linter-eslint/blob/4254301165d41e6053c977c2dd2ef0b851f2e8fd/src/main.js#L197-L201

Will have to investigate how this is getting sent to the worker...

**Comment by Arcanemagus** [comment]
Ah ha! This was fixed in https://github.com/AtomLinter/linter-eslint/pull/1017, but hasn't been released yet. I'll push one out now.

**Comment by 50Wliu** [comment]
:sparkles:
