### ISSUE TITLE
Not using local node_modules

### ISSUE THREAD

**Issue by richardpringle** [AtomLinter/linter-eslint#1039]
## Issue Type

Bug

## Issue Description

The local node_modules aren't being used, despite having set the path in the config for this package.
Am I setting this wrong?

console error (sorry for the error dump):
```bash
Failed to load plugin json: Cannot find module 'eslint-plugin-json'
Referenced from: /Users/richardpringle/code/nw-utils/.eslintrc Error: Failed to load plugin json: Cannot find module 'eslint-plugin-json'
Referenced from: /Users/richardpringle/code/nw-utils/.eslintrc
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.resolve (internal/module.js:27:19)
    at Plugins.load (/Users/richardpringle/.atom/packages/linter-eslint/node_modules/eslint/lib/config/plugins.js:133:29)
    at Array.forEach (native)
    at Plugins.loadAll (/Users/richardpringle/.atom/packages/linter-eslint/node_modules/eslint/lib/config/plugins.js:173:21)
    at loadFromDisk (/Users/richardpringle/.atom/packages/linter-eslint/node_modules/eslint/lib/config/config-file.js:536:35)
    at load (/Users/richardpringle/.atom/packages/linter-eslint/node_modules/eslint/lib/config/config-file.js:592:20)
    at configExtends.reduceRight (/Users/richardpringle/.atom/packages/linter-eslint/node_modules/eslint/lib/config/config-file.js:421:36)
    at Array.reduceRight (native)
    at applyExtends (/Users/richardpringle/.atom/packages/linter-eslint/node_modules/eslint/lib/config/config-file.js:403:28)
    at loadFromDisk (/Users/richardpringle/.atom/packages/linter-eslint/node_modules/eslint/lib/config/config-file.js:556:22)
    at Object.load (/Users/richardpringle/.atom/packages/linter-eslint/node_modules/eslint/lib/config/config-file.js:592:20)
    at Config.getLocalConfigHierarchy (/Users/richardpringle/.atom/packages/linter-eslint/node_modules/eslint/lib/config.js:226:44)
    at Config.getConfigHierarchy (/Users/richardpringle/.atom/packages/linter-eslint/node_modules/eslint/lib/config.js:180:43)
    at Config.getConfigVector (/Users/richardpringle/.atom/packages/linter-eslint/node_modules/eslint/lib/config.js:285:21)
    at Config.getConfig (/Users/richardpringle/.atom/packages/linter-eslint/node_modules/eslint/lib/config.js:328:29)
    at processText (/Users/richardpringle/.atom/packages/linter-eslint/node_modules/eslint/lib/cli-engine.js:158:33)
    at CLIEngine.executeOnText (/Users/richardpringle/.atom/packages/linter-eslint/node_modules/eslint/lib/cli-engine.js:606:17)
    at lintJob (/Users/richardpringle/.atom/packages/linter-eslint/src/worker.js:66:28)
    at fixJob (/Users/richardpringle/.atom/packages/linter-eslint/src/worker.js:74:18)
    at process.<anonymous> (/Users/richardpringle/.atom/packages/linter-eslint/src/worker.js:117:18)
    at emitTwo (events.js:111:20)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:752:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

## Bug Checklist
- Restart Atom
- Verify the `eslint` CLI gives the proper result, while `linter-eslint` does not
- Paste the output of the `Linter Eslint: Debug` command from the Command Palette below

```
Atom version: 1.21.1
linter-eslint version: 8.4.0
ESLint version: 4.9.0
Hours since last Atom restart: 0
Platform: darwin
Using bundled fallback ESLint from: /Users/richardpringle/.atom/packages/linter-eslint/node_modules/eslint
Current file's scopes: [
  "source.js",
  "string.quoted.single.js",
  "punctuation.definition.string.begin.js"
]
linter-eslint configuration: {
  "advancedLocalNodeModules": "./node_modules",
  "disableFSCache": true,
  "lintHtmlFiles": false,
  "useGlobalEslint": false,
  "showRuleIdInMessage": true,
  "disableWhenNoEslintConfig": true,
  "eslintrcPath": "",
  "globalNodePath": "",
  "eslintRulesDirs": [],
  "disableEslintIgnore": false,
  "fixOnSave": false,
  "scopes": [
    "source.js",
    "source.jsx",
    "source.js.jsx",
    "source.babel",
    "source.js-semantic"
  ],
  "rulesToSilenceWhileTyping": [],
  "rulesToDisableWhileFixing": [],
  "ignoreFixableRulesWhileTyping": false
}
```

**Comment by Arcanemagus** [comment]
The `advancedLocalnode` modules should have a giant disclaimer: "Don't touch this unless you know _exactly_ what you are doing" 😛.

In this case you have attempted to use a relative path, which isn't relative to what you think it is. Assuming that relative paths even work there at all, it would be relative to wherever was determined [here](https://github.com/AtomLinter/linter-eslint/blob/7f791653480ce30c1ffe9ab99c6c84e34fe7e7fe/src/worker-helpers.js#L139-L157).

Generally though you shouldn't need to fill that in unless you have a _very_ non-standard setup, one in which Node.js itself wouldn't work. Can you try clearing that setting and restarting Atom?

**Comment by Arcanemagus** [comment]
After some debugging over Atom's Slack, we found that re-creating the `node_modules` folder magically made this start working.

**Comment by richardpringle** [comment]
@Arcanemagus 
A nice-to-have would be some sort of warning about using the fallback `eslint`. I don't think I would have ever realized that my local package wasn't being used if I wasn't also depending on an eslint-plugin.

As I said though, it's a nice-to-have, thanks again for the help.

**Comment by Arcanemagus** [comment]
> A nice-to-have would be some sort of warning about using the fallback eslint.

Completely removing the fallback is actually on the long term roadmap here exactly because of issues like this. Getting it done Right:tm: is somewhat of a challenge and as it (usually) doesn't break anything we haven't put any time into it yet 😉.
