### ISSUE TITLE
Failed to activate the linter-eslint package

### ISSUE THREAD

**Issue by dirkhe1051931999** [AtomLinter/linter-eslint#1041]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 8.1 中文版
**Thrown From**: [linter-eslint](https://github.com/AtomLinter/linter-eslint) package 8.4.0

### Stack Trace

Failed to activate the linter-eslint package

```
At Cannot find module 'atom-babel6-transpiler' from 'C:\Users\asus\.atom\packages\linter-eslint'

Error: Cannot find module 'atom-babel6-transpiler' from 'C:\Users\asus\.atom\packages\linter-eslint'
    at /app.asar/node_modules/resolve/lib/sync.js:40:15)
    at PackageTranspilationRegistry.getTranspilerPath (~/AppData/Local/atom/app-1.21.1/resources/app/src/package-transpilation-registry.js:180:26)
    at PackageTranspilationRegistry.getCachePath (~/AppData/Local/atom/app-1.21.1/resources/app/src/package-transpilation-registry.js:131:39)
    at Object.getCachePath (~/AppData/Local/atom/app-1.21.1/resources/app/src/package-transpilation-registry.js:67:29)
    at compileFileAtPath (~/AppData/Local/atom/app-1.21.1/resources/app/src/compile-cache.js:91:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.21.1/resources/app/src/compile-cache.js:238:26)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (~/AppData/Local/atom/app-1.21.1/resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (~/AppData/Local/atom/app-1.21.1/resources/app/src/package.js:903:35)
    at Package.module.exports.Package.activateNow (~/AppData/Local/atom/app-1.21.1/resources/app/src/package.js:242:22)
    at ~/AppData/Local/atom/app-1.21.1/resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.21.1/resources/app/src/package.js:99:21)
    at ~/AppData/Local/atom/app-1.21.1/resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (~/AppData/Local/atom/app-1.21.1/resources/app/src/package.js:215:40)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.21.1/resources/app/src/package-manager.js:690:42)
    at config.transactAsync (~/AppData/Local/atom/app-1.21.1/resources/app/src/package-manager.js:665:36)
    at Config.module.exports.Config.transactAsync (~/AppData/Local/atom/app-1.21.1/resources/app/src/config.js:367:24)
    at PackageManager.activatePackages (~/AppData/Local/atom/app-1.21.1/resources/app/src/package-manager.js:663:23)
    at PackageManager.activate (~/AppData/Local/atom/app-1.21.1/resources/app/src/package-manager.js:646:50)
    at ~/AppData/Local/atom/app-1.21.1/resources/app/src/atom-environment.js:854:36
```

### Commands

```
     -0:17.8.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-atom-dark-ui)
```

### Non-Core Packages

```
atom-beautify 0.30.5 
atom-ternjs 0.18.3 
emmet 2.4.3 
file-icons 2.1.13 
highlight-line 0.12.0 
highlight-selected 0.13.1 
linter 2.2.0 
linter-eslint 8.4.0 
open-in-browser 0.5.2 
```

**Comment by Arcanemagus** [comment]
Please try re-installing the package, APM didn't install all the dependencies.

**Comment by dimpiax** [comment]
```
Package not initialized

Error: Package not initialized
    at Object.moduleExports.(anonymous function) [as consumeLinterProvider] (/Users/mac/.atom/packages/atom-ide-ui/modules/nuclide-commons-atom/createPackage.js:48:15)
    at Provider.module.exports.Provider.provide (/Applications/Atom.app/Contents/Resources/app/node_modules/service-hub/lib/provider.js:34:58)
    at ServiceHub.module.exports.ServiceHub.provide (/Applications/Atom.app/Contents/Resources/app/node_modules/service-hub/lib/service-hub.js:30:26)
    at Package.module.exports.Package.activateServices (/Applications/Atom.app/Contents/Resources/app/src/package.js:446:77)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:256:22)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:99:21)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:215:40)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:690:42)
    at packagesToEnable.forEach.name (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:439:51)
    at Array.forEach (native)
    at disabledPackagesSubscription.config.onDidChange (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:439:30)
    at /Applications/Atom.app/Contents/Resources/app/src/config.js:693:26
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Config.module.exports.Config.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app/src/config.js:884:35)
    at Config.module.exports.Config.setRawValue (/Applications/Atom.app/Contents/Resources/app/src/config.js:670:25)
    at Config.module.exports.Config.set (/Applications/Atom.app/Contents/Resources/app/src/config.js:248:20)
    at Config.module.exports.Config.removeAtKeyPath (/Applications/Atom.app/Contents/Resources/app/src/config.js:407:18)
    at Package.module.exports.Package.enable (/Applications/Atom.app/Contents/Resources/app/src/package.js:84:32)
    at PackageManager.enablePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:245:18)
    at HTMLButtonElement.enablementButtonClickHandler (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-card.js:361:31)
```

**Comment by IanVS** [comment]
@dimpiax did you try restarting Atom, after you installed linter-eslint?

**Comment by dimpiax** [comment]
@IanVS I've installed it half-year ago.
But after restarting there is no error from **linter-eslint**, neither from **atom-ide-ui**.
But it happen sometimes, looks like bug of Atom's engine.

**Comment by Arcanemagus** [comment]
Marking this as closed since @dirkhe1051931999 hasn't responded.

@dimpiax That looks like an internal Atom error, nothing that we can do here about it. Does it show that on every launch?

**Comment by dimpiax** [comment]
@Arcanemagus not on every, but sometimes, where fix is relaunch Atom.
