### ISSUE TITLE
Linting does not work

### ISSUE THREAD

**Issue by chrispahm** [AtomLinter/linter-eslint#1048]
# Issue Type
Bug

## Issue Description
I can't get ESLinter to work on a fresh installation, ```Linter Eslint: Debug``` leads to error message ```TypeError: Path must be a string. Received undefined``` -> no output. 
Console shows ```Uncaught (in promise) TypeError: Cannot read property 'atomVersion' of undefined
    at Object.<anonymous> (/Users/.../.atom/packages/linter-eslint/helpers.js:130:22)
    at Generator.next (<anonymous>)
    at step (/Users/.../.atom/packages/linter-eslint/helpers.js:9:1)
    at /Users/.../.atom/packages/linter-eslint/helpers.js:9:1
    at process._tickCallback (internal/process/next_tick.js:103:7)```

Tried restarting, re-installing packages, and new installation of Atom
Thanks for having a look!

## Installed packages
├── bug-report@0.7.1
├── busy-signal@1.4.3
├── intentions@1.1.5
├── linter@2.2.0
├── linter-eslint@8.4.0
└── linter-ui-default@1.6.10

Default linter-eslint package settings were used.

## Versions

* **Atom:**       1.21.2
* **Atom-Shell:**
* **OS:**         Mac OS X 10.12.5
* **Misc**
    * apm  1.18.5
    * npm  3.10.10
    * node 6.9.5 x64
    * python 2.7.12
    * git 2.7.1

---

**Comment by chrispahm** [comment]
For anyone experiencing the issue as well, chances are quiet high that you made the same mistake as I did and forgot to setup a .eslintrc file in your project directory using ```eslint --init```!
