### ISSUE TITLE
Unconfigured ESLint does nothing

### ISSUE THREAD

**Issue by drstonebraker** [AtomLinter/linter-eslint#1050]
## Issue Type

linter does not seem to work at all... not getting any errors in my javascript files

## Issue Description

I think I should be getting some kind of errors from the linter in my javascript, but I do not.

## Bug Checklist
- Restart Atom
done
- Verify the `eslint` CLI gives the proper result, while `linter-eslint` does not
I don't know what this means.  for `eslint`, I get output about different options I can use with the command.  for `linter-eslint`, I get `bash: linter-eslint: command not found`
- Paste the output of the `Linter Eslint: Debug` command from the Command Palette below
I don't know what this means.

```
Linter Eslint: Debug output here
```

**Comment by Arcanemagus** [comment]
Under the default settings this linter does nothing if it can't find a configuration for ESLint. Although you _can_ disable this, at best you will only be getting the most basic parse errors and none of the nice functionality of ESLint.

> I don't know what this means. for eslint, I get output about different options I can use with the command.

It sounds like you might want to review the [Getting Started](https://eslint.org/docs/user-guide/getting-started) guide for ESLint. This package is meant to be used when you already have ESLint configured.

**Comment by MikaelCarpenter** [comment]
I'm seeing the same thing, the footer on Atom has an infinte spinner saying ESLint is running on my open files.

Restarting Atom works for a second and then goes back to not working

The CLI works as expected

The output for `Linter Eslint: Debug` is: 
```
Error: channel closed
    at ChildProcess.target.send (internal/child_process.js:548:16)
    at Task.module.exports.Task.send (/Applications/Atom.app/Contents/Resources/app/src/task.js:113:33)
    at /Users/mikael/.atom/packages/linter-eslint/helpers.js:61:14
    at /Users/mikael/.atom/packages/linter-eslint/helpers.js:45:10
    at Generator.next (<anonymous>)
    at step (/Users/mikael/.atom/packages/linter-eslint/helpers.js:9:1)
    at /Users/mikael/.atom/packages/linter-eslint/helpers.js:9:1
    at /Users/mikael/.atom/packages/linter-eslint/helpers.js:9:1
    at sendJob (/Users/mikael/.atom/packages/linter-eslint/src/helpers.js:55:17)
    at /Users/mikael/.atom/packages/linter-eslint/helpers.js:104:28
    at Generator.next (<anonymous>)
    at step (/Users/mikael/.atom/packages/linter-eslint/helpers.js:9:1)
    at /Users/mikael/.atom/packages/linter-eslint/helpers.js:9:1
    at /Users/mikael/.atom/packages/linter-eslint/helpers.js:9:1
    at getDebugInfo (/Users/mikael/.atom/packages/linter-eslint/src/helpers.js:109:18)
    at Object.<anonymous> (/Users/mikael/.atom/packages/linter-eslint/helpers.js:128:23)
    at Generator.next (<anonymous>)
    at step (/Users/mikael/.atom/packages/linter-eslint/helpers.js:9:1)
    at /Users/mikael/.atom/packages/linter-eslint/helpers.js:9:1
    at Object.<anonymous> (/Users/mikael/.atom/packages/linter-eslint/helpers.js:9:1)
    at Object.generateDebugString (/Users/mikael/.atom/packages/linter-eslint/src/helpers.js:121:18)
    at HTMLElement.<anonymous> (/Users/mikael/.atom/packages/linter-eslint/main.js:122:43)
    at Generator.next (<anonymous>)
    at step (/Users/mikael/.atom/packages/linter-eslint/main.js:4:1)
    at /Users/mikael/.atom/packages/linter-eslint/main.js:4:1
    at HTMLElement.<anonymous> (/Users/mikael/.atom/packages/linter-eslint/main.js:4:1)
    at HTMLElement.linterEslintDebug (/Users/mikael/.atom/packages/linter-eslint/main.js:115:7)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:381:36)
    at Object.didConfirmSelection (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/lib/command-palette-view.js:144:35)
    at SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/node_modules/atom-select-list/src/select-list-view.js:324:26)
    at HTMLDivElement.core:confirm (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/node_modules/atom-select-list/src/select-list-view.js:81:20)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:381:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

**Comment by Arcanemagus** [comment]
@MikaelCarpenter You have an entirely different issue, please file a new issue to track trying to figure out what is wrong on your system.
