### ISSUE TITLE
Uncaught Error: C:\dev\smartui\.eslintrc:	Configuration for rule "react/jsx-no-undef" is invalid:	Value "2," is the wrong type.

### ISSUE THREAD

**Issue by davidtheclark** [AtomLinter/linter-eslint#106]
My config includes `react/jsx-no-undef: 2,`. I'm getting this error anytime the linter runs.

**Atom Version**: 0.209.0
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [linter-eslint](https://github.com/AtomLinter/linter-eslint) package, v0.5.9

### Stack Trace

Uncaught Error: C:\dev\smartui\.eslintrc:
	Configuration for rule "react/jsx-no-undef" is invalid:
	Value "2," is the wrong type.

```
At C:\dev\smartui\node_modules\eslint\lib\config-validator.js:88

Error: C:\dev\smartui\.eslintrc:
	Configuration for rule "react/jsx-no-undef" is invalid:
	Value "2," is the wrong type.

  at validateRuleOptions (C:\dev\smartui\node_modules\eslint\lib\config-validator.js:88:15)
  at C:\dev\smartui\node_modules\eslint\lib\config-validator.js:101:13
  at Array.forEach (native)
  at Object.validate (C:\dev\smartui\node_modules\eslint\lib\config-validator.js:100:35)
  at loadConfig (C:\dev\smartui\node_modules\eslint\lib\config.js:99:19)
  at getLocalConfig (C:\dev\smartui\node_modules\eslint\lib\config.js:225:23)
  at Config.getConfig (C:\dev\smartui\node_modules\eslint\lib\config.js:363:22)
  at CLIEngine.getConfigForFile (C:\dev\smartui\node_modules\eslint\lib\cli-engine.js:382:29)
  at C:\Users\david.clark\.atom\packages\linter-eslint\lib\linter-eslint.coffee:81:23
  at exports.allowUnsafeNewFunction (C:\Users\david.clark\.atom\packages\linter-eslint\node_modules\loophole\lib\loophole.js:25:14)
  at LinterESLint.lintFile (C:\Users\david.clark\.atom\packages\linter-eslint\lib\linter-eslint.coffee:80:5)
  at C:\Users\david.clark\.atom\packages\linter\lib\linter-view.coffee:163:18
  at Array.forEach (native)
  at C:\Users\david.clark\.atom\packages\linter\lib\linter-view.coffee:162:18
  at FSReqWrap.oncomplete (fs.js:77:15)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
editorconfig, v1.0.0
emmet, v2.3.10
highlight-selected, v0.10.0
language-freemarker, v0.2.0
linter, v0.12.7
linter-eslint, v0.5.9
react, v0.12.0

# Dev
No dev packages
```

**Comment by davidtheclark** [comment]
Sorry ... looks like a problem with the plugin itself.
