### ISSUE TITLE
Uncaught Error: /Users/andreaascari/Sites/github/web-seed/.eslintrc:	Configuration for rule "comma-dangle" is invalid:	Value "always" is the wrong type.

### ISSUE THREAD

**Issue by ascariandrea** [AtomLinter/linter-eslint#108]
[Enter steps to reproduce below:]

1. I just restart atom

**Atom Version**: 0.209.0
**System**: Mac OS X 10.10.3
**Thrown From**: [linter-eslint](https://github.com/AtomLinter/linter-eslint) package, v0.5.9

### Stack Trace

Uncaught Error: /Users/andreaascari/Sites/github/web-seed/.eslintrc:
	Configuration for rule "comma-dangle" is invalid:
	Value "always" is the wrong type.

```
At /Users/andreaascari/Sites/github/web-seed/node_modules/eslint/lib/config-validator.js:88

Error: /Users/andreaascari/Sites/github/web-seed/.eslintrc:
	Configuration for rule "comma-dangle" is invalid:
	Value "always" is the wrong type.

  at validateRuleOptions (/Users/andreaascari/Sites/github/web-seed/node_modules/eslint/lib/config-validator.js:88:15)
  at /Users/andreaascari/Sites/github/web-seed/node_modules/eslint/lib/config-validator.js:101:13
  at Array.forEach (native)
  at Object.validate (/Users/andreaascari/Sites/github/web-seed/node_modules/eslint/lib/config-validator.js:100:35)
  at loadConfig (/Users/andreaascari/Sites/github/web-seed/node_modules/eslint/lib/config.js:99:19)
  at getLocalConfig (/Users/andreaascari/Sites/github/web-seed/node_modules/eslint/lib/config.js:225:23)
  at Config.getConfig (/Users/andreaascari/Sites/github/web-seed/node_modules/eslint/lib/config.js:363:22)
  at CLIEngine.getConfigForFile (/Users/andreaascari/Sites/github/web-seed/node_modules/eslint/lib/cli-engine.js:382:29)
  at /Users/andreaascari/.atom/packages/linter-eslint/lib/linter-eslint.coffee:81:23
  at exports.allowUnsafeNewFunction (/Users/andreaascari/.atom/packages/linter-eslint/node_modules/loophole/lib/loophole.js:25:14)
  at LinterESLint.lintFile (/Users/andreaascari/.atom/packages/linter-eslint/lib/linter-eslint.coffee:80:5)
  at /Users/andreaascari/.atom/packages/linter/lib/linter-view.coffee:163:18
  at Array.forEach (native)
  at /Users/andreaascari/.atom/packages/linter/lib/linter-view.coffee:162:18
  at FSReqWrap.oncomplete (fs.js:77:15)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ],
    "ignoredNames": [
      "node_modules"
    ],
    "disabledPackages": [
      "eslint",
      "eslint",
      "symbols-view"
    ],
    "destroyEmptyPanes": false,
    "excludeVcsIgnoredPaths": false
  },
  "linter-eslint": {}
}
```

### Installed Packages

```coffee
# User
atom-ctags, v4.1.2
color-picker, v2.0.4
file-type-icons, v0.7.0
file-types, v0.4.0
language-scala, v1.1.3
linter, v0.12.7
linter-csslint, v0.0.13
linter-eslint, v0.5.9
linter-less, v0.5.0
linter-scalac, v0.3.4
minimap, v4.10.0
pretty-json, v0.3.3
trailing-spaces, v0.3.2
vim-mode, v0.53.0

# Dev
No dev packages
```

**Comment by iam4x** [comment]
comma-dangle values in config: `0-1-2`
