### ISSUE TITLE
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an al...

### ISSUE THREAD

**Issue by bgc** [AtomLinter/linter-eslint#109]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.210.0-abca152
**System**: Ubuntu 14.04.2
**Thrown From**: [linter-eslint](https://github.com/AtomLinter/linter-eslint) package, v0.5.9

### Stack Trace

Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

```
At /home/gcosta/.atom/packages/linter-eslint/node_modules/eslint/node_modules/is-my-json-valid/node_modules/generate-function/index.js:55

EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

  at Function (native)
  at Function.line.toFunction (/home/gcosta/.atom/packages/linter-eslint/node_modules/eslint/node_modules/is-my-json-valid/node_modules/generate-function/index.js:55:21)
  at compile (/home/gcosta/.atom/packages/linter-eslint/node_modules/eslint/node_modules/is-my-json-valid/index.js:539:23)
  at module.exports (/home/gcosta/.atom/packages/linter-eslint/node_modules/eslint/node_modules/is-my-json-valid/index.js:560:10)
  at validateRuleOptions (/home/gcosta/.atom/packages/linter-eslint/node_modules/eslint/lib/config-validator.js:67:24)
  at /home/gcosta/.atom/packages/linter-eslint/node_modules/eslint/lib/config-validator.js:101:13
  at Array.forEach (native)
  at Object.validate (/home/gcosta/.atom/packages/linter-eslint/node_modules/eslint/lib/config-validator.js:100:35)
  at loadConfig (/home/gcosta/.atom/packages/linter-eslint/node_modules/eslint/lib/config.js:99:19)
  at getLocalConfig (/home/gcosta/.atom/packages/linter-eslint/node_modules/eslint/lib/config.js:225:23)
  at Config.getConfig (/home/gcosta/.atom/packages/linter-eslint/node_modules/eslint/lib/config.js:363:22)
  at CLIEngine.getConfigForFile (/home/gcosta/.atom/packages/linter-eslint/node_modules/eslint/lib/cli-engine.js:382:29)
  at LinterESLint.lintFile (/home/gcosta/.atom/packages/linter-eslint/lib/linter-eslint.coffee:51:5)
  at /home/gcosta/.atom/packages/linter/lib/linter-view.coffee:163:18
  at Array.forEach (native)
  at /home/gcosta/.atom/packages/linter/lib/linter-view.coffee:162:18
  at FSReqWrap.oncomplete (fs.js:77:15)

```

### Commands

```
     -4:43.6.0 git-control:toggle (atom-text-editor.editor.is-focused)
     -0:03.1.0 editor:newline (atom-text-editor.editor.is-focused)
  3x -0:02.3.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".DS_Store",
      "nbproject",
      "idea"
    ],
    "disabledPackages": [
      "metrics",
      "tree-view-open-files",
      "gamboge",
      "scope-inspector",
      "jsdoc",
      "xml-formatter",
      "merge-conflicts",
      "linter-perl",
      "perltidy",
      "atom-jshint",
      "timecop",
      "welcome",
      "spell-check",
      "release-notes",
      "language-latex",
      "powerline",
      "vim-mode",
      "language-javascript-semantic",
      "org",
      "mechanical-keyboard",
      "language-csharp",
      "language-ruby",
      "language-ruby-on-rails",
      "language-toml",
      "language-yaml",
      "language-property-list",
      "language-objective-c",
      "feedback",
      "exception-reporting",
      "language-mustache",
      "emacs-flow",
      "atom-ternjs",
      "slack-chat",
      "todo-list"
    ],
    "themes": [
      "isotope-ui",
      "viriato"
    ],
    "projectHome": "/home/gcosta/workspace",
    "autoHideMenuBar": true,
    "followSymlinks": true
  },
  "linter-eslint": {}
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.5
file-icons, v1.5.7
git-control, v0.3.0
git-log, v0.4.1
git-projects, v1.14.1
highlight-line, v0.11.0
htmlhint, v1.1.3
isotope-ui, v2.4.0
jsonlint, v1.1.2
linter, v0.12.7
linter-eslint, v0.5.9
method-separator, v0.1.3
minimap, v4.10.0
minimap-bookmarks, v0.1.0
minimap-color-highlight, v4.1.4
minimap-find-and-replace, v4.2.0
minimap-git-diff, v4.1.3
pretty-json, v0.3.3
tasks, v2.1.0
viriato, v0.10.0

# Dev
No dev packages
```

**Comment by impinball** [comment]
This could be fixed by simply wrapping the ESLint call with [atom/loophole](https://github.com/atom/loophole)'s `allowUnsafeNewFunction(callback)` and possibly `allowUnsafeEval(callback)` as well.

On another note, how the hell are you getting CSP errors? I've never had that problem. Also, does updating to Atom 1.0 help?

**Comment by iam4x** [comment]
This has been already resolved like you said @impinball with atom/loophole
