### ISSUE TITLE
Uncaught TypeError: Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by tuantle** [AtomLinter/linter-eslint#111]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.210.0
**System**: Mac OS X 10.10.3
**Thrown From**: [linter-eslint](https://github.com/AtomLinter/linter-eslint) package, v0.5.9

### Stack Trace

Uncaught TypeError: Cannot read property 'toLowerCase' of undefined

```
At /Users/Tuan/Projects/arch/node_modules/eslint/lib/rules/sort-vars.js:24

TypeError: Cannot read property 'toLowerCase' of undefined
  at /Users/Tuan/Projects/arch/node_modules/eslint/lib/rules/sort-vars.js:24:56
  at Array.reduce (native)
  at EventEmitter.VariableDeclaration (/Users/Tuan/Projects/arch/node_modules/eslint/lib/rules/sort-vars.js:19:31)
  at emitOne (events.js:82:20)
  at EventEmitter.emit (events.js:166:7)
  at Controller.controller.traverse.enter (/Users/Tuan/Projects/arch/node_modules/eslint/lib/eslint.js:725:25)
  at Controller.__execute (/Users/Tuan/Projects/arch/node_modules/eslint/node_modules/estraverse/estraverse.js:393:31)
  at Controller.traverse (/Users/Tuan/Projects/arch/node_modules/eslint/node_modules/estraverse/estraverse.js:491:28)
  at EventEmitter.module.exports.api.verify (/Users/Tuan/Projects/arch/node_modules/eslint/lib/eslint.js:718:24)
  at /Users/Tuan/.atom/packages/linter-eslint/lib/linter-eslint.coffee:129:25
  at exports.allowUnsafeNewFunction (/Users/Tuan/.atom/packages/linter-eslint/node_modules/loophole/lib/loophole.js:25:14)
  at LinterESLint.lintFile (/Users/Tuan/.atom/packages/linter-eslint/lib/linter-eslint.coffee:128:7)
  at /Users/Tuan/.atom/packages/linter/lib/linter-view.coffee:163:18
  at Array.forEach (native)
  at /Users/Tuan/.atom/packages/linter/lib/linter-view.coffee:162:18
  at FSReqWrap.oncomplete (fs.js:77:15)

```

### Commands

```
     -3:41.2.0 release-notes:show (atom-text-editor.editor.is-focused)
     -2:37.9.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -2:37.3.0 core:move-down (atom-text-editor.editor.is-focused)
     -2:36.3.0 core:backspace (atom-text-editor.editor.is-focused)
 13x -2:32.8.0 core:move-right (atom-text-editor.editor.is-focused)
     -2:12.4.0 application:new-file (ul.list-inline.tab-bar.inset-panel)
     -1:27.5.0 core:move-right (atom-text-editor.editor.is-focused)
     -1:21.4.0 core:move-left (atom-text-editor.editor.is-focused)
 30x -0:59.3.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:41.7.0 core:save (atom-text-editor.editor.is-focused)
     -0:27.4.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-base16-tomorrow-dark-theme.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "projectHome": "/Users/Tuan/Projects",
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  },
  "linter-eslint": {}
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.5
emmet, v2.3.10
file-icons, v1.5.7
linter, v0.12.7
linter-eslint, v0.5.9
minimap, v4.10.0

# Dev
No dev packages
```

**Comment by iam4x** [comment]
Error thrown from `eslint` itself, they should be caught now.
