### ISSUE TITLE
Uncaught Error: Cannot find module './worker-helpers'

### ISSUE THREAD

**Issue by vishvajit79** [AtomLinter/linter-eslint#1137]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.27.0 x64
**Electron**: 1.7.11
**OS**: Microsoft Windows 10 Home
**Thrown From**: [linter-eslint](https://github.com/AtomLinter/linter-eslint) package 8.4.1

### Stack Trace

Uncaught Error: Cannot find module './worker-helpers'

```
At module.js:472

Error: Cannot find module './worker-helpers'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.27.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.27.0/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.27.0/resources/app/src/native-compile-cache.js:66:33)
    at loadDeps (/packages/linter-eslint/src/main.js:26:21)
    at callBack (/packages/linter-eslint/src/main.js:37:5)
```

### Commands

```
     -0:16.2.0 window:toggle-dev-tools (div.tool-panel.tree-view)
```

### Non-Core Packages

```
atom-beautify 0.32.3 
atom-live-server 2.2.0 
busy-signal 1.4.3 
color-picker 2.3.0 
emmet 2.4.3 
file-icons 2.1.20 
intentions 1.1.5 
jquery-snippets 11.0.0 
language-arduino 0.4.3 
language-blade 0.39.0 
language-vue 0.23.1 
laravel 0.7.1 
linter 2.2.0 
linter-eslint 8.4.1 
linter-ui-default 1.7.1 
pigments 0.40.2 
platformio-ide-terminal 2.8.1 
react 0.18.0 
react-snippets 1.1.0 
```

**Comment by skylize** [comment]
I think your installation of `linter-eslint` package is corrupted. Try reinstalling and let us know if you still have issues.

**Comment by vishvajit79** [comment]
Thank you. Yes, I uninstalled the extensions and installed again. It worked! 👍
