### ISSUE TITLE
Failed to activate the linter package

### ISSUE THREAD

**Issue by DjebbZ** [AtomLinter/linter-eslint#114]
1. Install linter-eslint
2. Start Atom

I suppose the problem comes from a conflict with the "react" package, since it uses "Javascript (JSX)" file mode and not normal ("Javascript").

**Atom Version**: 0.210.0
**System**: Mac OS X 10.8.5
**Thrown From**: [linter-eslint](https://github.com/AtomLinter/linter-eslint) package, v0.5.10

### Stack Trace

Failed to activate the linter package

```
At Cannot find module 'resolve'

Error: Cannot find module 'resolve'
    at Module._resolveFilename (module.js:328:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (/Users/khalid_jebbari/.atom/packages/linter-eslint/lib/linter-eslint.coffee:12:13)
    at Object.<anonymous> (/Users/khalid_jebbari/.atom/packages/linter-eslint/lib/linter-eslint.coffee:227:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
```

### Commands

```
     -0:00.3.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "excludeVcsIgnoredPaths": true
  },
  "linter-eslint": {}
}
```

### Installed Packages

```coffee
# User
atom-ternjs, v0.6.4
color-picker, v2.0.6
emmet, v2.3.10
language-gitignore, v0.2.0
linter, v0.12.7
linter-eslint, v0.5.10
react, v0.12.0

# Dev
No dev packages
```

**Comment by DjebbZ** [comment]
The error happens whether I install the npm modules `eslint` and `eslint-plugin-react` (locally) or not.

**Comment by DjebbZ** [comment]
The error also happens when I disabled *ALL* other community packages, leaving only `linter` and `linter-eslint`.

**Comment by AsaAyers** [comment]
try uninstalling and reinstalling `linter-eslint`. It seems like for some reason it failed to download the dependency even though it's listed in [package.json](https://github.com/AtomLinter/linter-eslint/blob/master/package.json#L16).

**Comment by DjebbZ** [comment]
I just did, using the cli `apm`, and now it works ! Thanks for the advice.

**Comment by damassi** [comment]
For whatever reason when trying to install I'm getting `cannot read property 'path' of undefined`, and I've tried to install, uninstall, and reinstall:

Cannot read property 'path' of undefined
Hide Stack Trace
TypeError: Cannot read property 'path' of undefined
  at Object.<anonymous> (/Users/damassi/.atom/packages/linter-eslint/lib/linter-eslint.coffee:8:54)
  at Object.<anonymous> (/Users/damassi/.atom/packages/linter-eslint/lib/linter-eslint.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:709:34)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:188:28
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:165:15)
  at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:179:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:372:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:451:30)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:362:29
  at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:53:16)
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1057:12)
