### ISSUE TITLE
Cannot find module 'eslint-config-strict'

### ISSUE THREAD

**Issue by ghost** [AtomLinter/linter-eslint#1155]
## Issue Type
Question

## Issue Description
I am using an .eslintrc file in my atom projects and getting the following error:
Error while running ESLint: Cannot find module 'eslint-config-strict'.

The .eslintrc contains a:
`"extends": ["strict"]`

What can I do to resolve this issue?

## Bug Checklist
- [x ] Restart Atom
- [x ] Verify the `eslint` CLI gives the proper result, while `linter-eslint` does not
- [x ] Paste the output of the `Linter Eslint: Debug` command from the Command Palette below

```
Error while running ESLint: Cannot find module 'eslint-config-strict'.
<div style="white-space: pre-wrap">Cannot find module 'eslint-config-strict'
Referenced from: C:\Users\someuser\Documents\GitHub\sls-lambda-njamsApiRules\.eslintrc
<hr />Error: Cannot find module 'eslint-config-strict'
Referenced from: C:\Users\someuser\Documents\GitHub\sls-lambda-njamsApiRules\.eslintrc
    at ModuleResolver.resolve (C:\Users\someuser\.atom\packages\linter-eslint\node_modules\eslint\lib\util\module-resolver.js:74:19)
    at resolve (C:\Users\someuser\.atom\packages\linter-eslint\node_modules\eslint\lib\config\config-file.js:479:28)
    at load (C:\Users\someuser\.atom\packages\linter-eslint\node_modules\eslint\lib\config\config-file.js:551:26)
    at configExtends.reduceRight (C:\Users\someuser\.atom\packages\linter-eslint\node_modules\eslint\lib\config\config-file.js:425:36)
    at Array.reduceRight (<anonymous>)
    at applyExtends (C:\Users\someuser\.atom\packages\linter-eslint\node_modules\eslint\lib\config\config-file.js:403:26)
    at loadFromDisk (C:\Users\someuser\.atom\packages\linter-eslint\node_modules\eslint\lib\config\config-file.js:523:22)
    at Object.load (C:\Users\someuser\.atom\packages\linter-eslint\node_modules\eslint\lib\config\config-file.js:559:20)
    at Config.getLocalConfigHierarchy (C:\Users\someuser\.atom\packages\linter-eslint\node_modules\eslint\lib\config.js:227:44)
    at Config.getConfigHierarchy (C:\Users\someuser\.atom\packages\linter-eslint\node_modules\eslint\lib\config.js:179:43)
    at Config.getConfigVector (C:\Users\someuser\.atom\packages\linter-eslint\node_modules\eslint\lib\config.js:286:21)
    at Config.getConfig (C:\Users\someuser\.atom\packages\linter-eslint\node_modules\eslint\lib\config.js:329:29)
    at processText (C:\Users\someuser\.atom\packages\linter-eslint\node_modules\eslint\lib\cli-engine.js:163:33)
    at CLIEngine.executeOnText (C:\Users\someuser\.atom\packages\linter-eslint\node_modules\eslint\lib\cli-engine.js:620:17)
    at lintJob (file:///C:/Users/someuser/.atom/packages/linter-eslint/src/worker.js:17:28)
    at process.<anonymous> (file:///C:/Users/someuser/.atom/packages/linter-eslint/src/worker.js:67:24)
    at emitTwo (events.js:131:20)
    at process.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)</div>
```

**Comment by Arcanemagus** [comment]
Do you have that NPM package installed in your project?

**Comment by kirnberger** [comment]
Yes, with npm I installed `eslint` and also `eslint-config-strict` after the issue came up. But no help.
