### ISSUE TITLE
Error: Cannot find module 'lodash'

### ISSUE THREAD

**Issue by anthonator** [AtomLinter/linter-eslint#117]
Getting this after installing Linter 1.0.0. I've tried installing lodash as a dependency in my project and that didn't seem to have any effect.

```
Error: Cannot find module 'lodash'
  at Module._resolveFilename (module.js:328:15)
  at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:270:25)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at LinterESLint.Linter.getEditorScopesForPosition (/Users/anthonator/.atom/packages/linter/lib/linter.coffee:291:31)
  at LinterESLint.Linter.computeRange (/Users/anthonator/.atom/packages/linter/lib/linter.coffee:337:5)
  at LinterESLint.Linter.createMessage (/Users/anthonator/.atom/packages/linter/lib/linter.coffee:16:3)
  at /Users/anthonator/.atom/packages/linter-eslint/lib/linter-eslint.coffee:165:8
  at Array.map (native)
  at LinterESLint.lintFile (/Users/anthonator/.atom/packages/linter-eslint/lib/linter-eslint.coffee:160:23)
  at /Users/anthonator/.atom/packages/linter/lib/legacy.coffee:48:16
  at Object.lint (/Users/anthonator/.atom/packages/linter/lib/legacy.coffee:47:18)
  at /Users/anthonator/.atom/packages/linter/lib/editor-linter.coffee:64:24
  at /Users/anthonator/.atom/packages/linter/lib/editor-linter.coffee:63:25
  at Set.forEach (native)
  at EditorLinter._lint (/Users/anthonator/.atom/packages/linter/lib/editor-linter.coffee:57:26)
  at EditorLinter.lint (/Users/anthonator/.atom/packages/linter/lib/editor-linter.coffee:51:18)
  at /Users/anthonator/.atom/packages/linter/lib/editor-linter.coffee:21:37
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1183:25
```

**Comment by AsaAyers** [comment]
use `View > Reload` to reload Atom. It's a temporary problem with the upgrade.

**Comment by anthonator** [comment]
Seemed to be an issue with Linter.  Upgraded to Linter 1.0.1 and the issue was fixed.
