### ISSUE TITLE
Package crashes at Atom startup

### ISSUE THREAD

**Issue by tolokoban** [AtomLinter/linter-eslint#1174]
## Issue Description
The package throw an error any time I start Atom.

Here is how to reproduce:

1. Just starting Atom from command line.

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [linter-eslint](https://github.com/AtomLinter/linter-eslint) package 8.4.1

### Stack Trace

Failed to activate the linter-eslint package

```
At Unexpected token (

SyntaxError: Unexpected token (
    at Module._compile (/app.asar/src/native-compile-cache.js:79:40)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:207:16)
    at /app.asar/src/package.js:190:32
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at /app.asar/src/package.js:183:26
    at Package.module.exports.Package.activate (/app.asar/src/package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:550:34)
    at /app.asar/src/package-manager.js:531:29
    at Config.module.exports.Config.transactAsync (/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/app.asar/src/package-manager.js:526:19)
    at PackageManager.module.exports.PackageManager.activate (/app.asar/src/package-manager.js:508:46)
    at /app.asar/src/atom-environment.js:812:28

```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-easy-jsdoc 4.12.5 
atom-keyboard-macros 0.12.1 
atom-macros 0.5.2 
browser-plus 0.0.98 
busy-signal 1.4.3 
ide-typescript 0.7.6 
intentions 1.1.5 
language-batchfile 0.7.5 
language-rust 0.4.12 
linter 2.2.0 
linter-eslint 8.4.1 
linter-jshint 3.1.9 
linter-ui-default 1.7.1 
markdown-folding 0.3.1 
todo-show 2.3.2 
```

**Comment by IanVS** [comment]
Hmmm, I notice that your version of atom is quite old.  You could try upgrading it, as the error _looks_ like something coming from node/atom.  I don't see anything about linter-eslint in the stack trace.  Did it just start happening when you installed this package?

**Comment by tolokoban** [comment]
Great!
Reinstalling Atom gave me the last version and the fix for my problem.
Thank you!
