### ISSUE TITLE
Uncaught Error: Cannot find module './helpers'

### ISSUE THREAD

**Issue by Wasya1212** [AtomLinter/linter-eslint#1190]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.32.0 x64
**Electron**: 2.0.9
**OS**: Unknown Windows version
**Thrown From**: [linter-eslint](https://github.com/AtomLinter/linter-eslint) package 8.4.1

### Stack Trace

Uncaught Error: Cannot find module './helpers'

```
At module.js:545

Error: Cannot find module './helpers'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.32.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.32.0/resources/app/static/<embedded>:11:154364)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.32.0/resources/app/static/<embedded>:11:145671)
    at loadDeps (/packages/linter-eslint/src/main.js:26:15)
    at callBack (/packages/linter-eslint/src/main.js:40:5)
```

### Commands

```
     -8:22.2.0 tree-view:go-to-letter-a (div.list-tree.has-collapsable-children.file-tree-scroller.nuclide-file-tree.focusable-panel.tree-view)
     -8:10.4.0 tree-view:add-file (span.)
     -7:58.7.0 editor:consolidate-selections (input.hidden-input)
     -7:58.7.0 core:cancel (input.hidden-input)
     -7:57.3.0 application:new-file (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -7:47.8.0 core:save (input.hidden-input)
     -7:38.2.0 tree-view:add-file (span.)
  3x -7:31.9.0 core:backspace (input.hidden-input)
     -7:30.3.0 core:confirm (input.hidden-input)
  4x -7:16.8.0 tree-view:go-to-letter-a (div.list-tree.has-collapsable-children.file-tree-scroller.nuclide-file-tree.focusable-panel.tree-view)
  5x -7:14.9.0 tree-view:remove-letter (div.list-tree.has-collapsable-children.file-tree-scroller.nuclide-file-tree.focusable-panel.tree-view)
  2x -6:55.1.0 core:close (input.hidden-input)
     -6:25 core:paste (input.hidden-input)
     -6:23.1.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
color-picker 2.3.0 
emmet 2.4.3 
language-javascript-jsx 0.3.7 
linter-eslint 8.4.1 
nuclide 0.362.0 
platformio-ide-terminal 2.8.1 
pug 0.8.0 
webbox-color 0.5.9 
```

**Comment by skylize** [comment]
Looks like something went wrong with the installation and you are missing files. Please try reinstalling the package, and let us know if you still have trouble. Thanks.
