### ISSUE TITLE
relative is not defined

### ISSUE THREAD

**Issue by iamstarkov** [AtomLinter/linter-eslint#120]
Have a popup with this error everytime I try to edit js file

Project has `.eslintrc` file in the root 

Here is a stacktrace
```
ReferenceError: relative is not defined
  at Object.provider.lint (/Users/vladimir/.atom/packages/linter-eslint/lib/linter-eslint.coffee:75:47)
  at /Users/vladimir/.atom/packages/linter/lib/editor-linter.coffee:79:24
  at /Users/vladimir/.atom/packages/linter/lib/editor-linter.coffee:78:25
  at Set.forEach (native)
  at EditorLinter._lint (/Users/vladimir/.atom/packages/linter/lib/editor-linter.coffee:72:26)
  at EditorLinter.lint (/Users/vladimir/.atom/packages/linter/lib/editor-linter.coffee:66:18)
  at /Users/vladimir/.atom/packages/linter/lib/editor-linter.coffee:22:37
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1183:25
``

**Comment by iam4x** [comment]
dupe #119 should be fixed with new version published. Can you confirm?

**Comment by hoppula** [comment]
Just installed 1.0.1 and having the same problem.
