### ISSUE TITLE
Uncaught Error: Cannot find module 'atom-babel6-transpiler' from '$ATOM_HOME/packages\linter-eslint'

### ISSUE THREAD

**Issue by smamat** [AtomLinter/linter-eslint#1201]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.32.2 x64
**Electron**: 2.0.9
**OS**: Microsoft Windows 10 Home Single Language
**Thrown From**: [linter-eslint](https://github.com/AtomLinter/linter-eslint) package 8.4.1

### Stack Trace

Uncaught Error: Cannot find module 'atom-babel6-transpiler' from 'C:\Users\smama\.atom\packages\linter-eslint'

```
At C:\Users\smama\AppData\Local\atom\app-1.32.2\resources\app.asar\node_modules\resolve\lib\sync.js:45

Error: Cannot find module 'atom-babel6-transpiler' from 'C:\Users\smama\.atom\packages\linter-eslint'
    at /app.asar/node_modules/resolve/lib/sync.js:43:15)
    at PackageTranspilationRegistry.getTranspilerPath (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:572497)
    at PackageTranspilationRegistry.getCachePath (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:571452)
    at Object.getCachePath (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:570539)
    at compileFileAtPath (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:147317)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:149898)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:145675)
    at loadDeps (/packages/linter-eslint/src/main.js:26:15)
    at callBack (/packages/linter-eslint/src/main.js:40:5)
```

### Commands

```
```

### Non-Core Packages

```
busy-signal 1.4.3 
ex-mode 0.18.0 
intentions 1.1.5 
linter 2.2.0 
linter-eslint 8.4.1 
linter-ui-default 1.7.1 
platformio-ide-terminal 2.8.4 
vim-mode-plus 1.36.0 
```

**Comment by Arcanemagus** [comment]
It looks like `apm` didn't install all the required dependencies when you installed the package, it's a bug that happens rarely that is beyond our control to fix unfortunately.

Please re-install the package, which should fix this for you 😉.
