### ISSUE TITLE
Failed to load the linter-eslint package

### ISSUE THREAD

**Issue by jpbufe3** [AtomLinter/linter-eslint#121]
[Enter steps to reproduce below:]
Both of the following had the same result:
1.a. Click "Install" on linter-eslint from inside the Atom package manager.
1.b. apm install linter-eslint
2. Open Atom or go to "Preferences" -> "Open Config Folder"

**Atom Version**: 0.211.0
**System**: Mac OS X 10.10.3
**Thrown From**: [linter-eslint](https://github.com/AtomLinter/linter-eslint) package, v1.0.2

### Stack Trace

Failed to load the linter-eslint package

```
At Cannot read property 'path' of undefined

TypeError: Cannot read property 'path' of undefined
    at Object.<anonymous> (~/.atom/packages/linter-eslint/lib/linter-eslint.coffee:16:56)
    at Object.<anonymous> (~/.atom/packages/linter-eslint/lib/linter-eslint.coffee:191:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:709:34)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:188:28
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
jslint, v1.4.0
linter-eslint, v1.0.2

# Dev
No dev packages
```

**Comment by AsaAyers** [comment]
You have to also install [linter](https://atom.io/packages/linter) for `linter-eslint` to work.

**Comment by jpbufe3** [comment]
Thank you @AsaAyers . While I feel stupid for missing that line in the README, wouldn't it be helpful to have that come up as the error message instead of what is shown above?

**Comment by iam4x** [comment]
@jpbufe3 Done with https://github.com/AtomLinter/linter-eslint/commit/d9e7c3dcd32e92c5f9e5cd8a947ff442b48dd81a

**Comment by brunowego** [comment]
+1

**Comment by steelbrain** [comment]
@brunowego See https://github.com/AtomLinter/linter-eslint/issues/320

**Comment by brunowego** [comment]
Thanks @steelbrain :+1:
