### ISSUE TITLE
Install "linter-eslint@8.5.2" failed

### ISSUE THREAD

**Issue by KoaLaYT** [AtomLinter/linter-eslint#1242]
## Issue Type

Can't not install **linter-eslint**

## Issue Description

Installing "linter-eslint@8.5.2" failed.
npm ERR! Unexpected end of JSON input while parsing near '...1.3.1", "dependencies"'

Here is the debug log:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/share/atom/resources/app/apm/bin/node',
1 verbose cli   '/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js',
1 verbose cli   '--globalconfig',
1 verbose cli   '/home/koalayt/.atom/.apm/.apmrc',
1 verbose cli   '--userconfig',
1 verbose cli   '/home/koalayt/.atom/.apmrc',
1 verbose cli   'install',
1 verbose cli   'https://www.atom.io/api/packages/linter-eslint/versions/8.5.2/tarball',
1 verbose cli   '--runtime=electron',
1 verbose cli   '--target=2.0.16',
1 verbose cli   '--dist-url=https://atom.io/download/electron',
1 verbose cli   '--arch=x64',
1 verbose cli   '--global-style' ]
2 info using npm@6.2.0
3 info using node@v8.9.3
4 verbose npm-session bdc7b913b1a67d8e
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 200 https://www.atom.io/api/packages/linter-eslint/versions/8.5.2/tarball 6684ms
8 silly pacote remote manifest for undefined@https://www.atom.io/api/packages/linter-eslint/versions/8.5.2/tarball fetched in 6694ms
9 timing stage:loadCurrentTree Completed in 6816ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 1ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule linter-eslint@8.5.2 checking installable status
17 http fetch GET 304 https://registry.npmjs.org/atom-package-deps 869ms (from cache)
18 silly pacote version manifest for atom-package-deps@5.0.0 fetched in 871ms
19 silly resolveWithNewModule atom-package-deps@5.0.0 checking installable status
20 http fetch GET 304 https://registry.npmjs.org/user-home 175ms (from cache)
21 silly pacote version manifest for user-home@2.0.0 fetched in 176ms
22 silly resolveWithNewModule user-home@2.0.0 checking installable status
23 http fetch GET 304 https://registry.npmjs.org/babel-preset-env 1049ms (from cache)
24 silly fetchPackageMetaData error for babel-preset-env@1.7.0 Unexpected end of JSON input while parsing near '...1.3.1","dependencies"'
25 http fetch GET 304 https://registry.npmjs.org/atom-babel6-transpiler 1097ms (from cache)
26 silly pacote version manifest for atom-babel6-transpiler@1.2.0 fetched in 1099ms
27 silly resolveWithNewModule atom-babel6-transpiler@1.2.0 checking installable status
28 http fetch GET 304 https://registry.npmjs.org/eslint 1219ms (from cache)
29 silly pacote version manifest for eslint@4.19.1 fetched in 1225ms
30 silly resolveWithNewModule eslint@4.19.1 checking installable status
31 http fetch GET 304 https://registry.npmjs.org/consistent-path 1276ms (from cache)
32 silly pacote version manifest for consistent-path@2.0.3 fetched in 1277ms
33 silly resolveWithNewModule consistent-path@2.0.3 checking installable status
34 http fetch GET 304 https://registry.npmjs.org/fs-plus 1408ms (from cache)
35 silly pacote version manifest for fs-plus@3.1.1 fetched in 1409ms
36 silly resolveWithNewModule fs-plus@3.1.1 checking installable status
37 http fetch GET 304 https://registry.npmjs.org/resolve-env 1418ms (from cache)
38 silly pacote version manifest for resolve-env@1.0.0 fetched in 1419ms
39 silly resolveWithNewModule resolve-env@1.0.0 checking installable status
40 http fetch GET 304 https://registry.npmjs.org/eslint-rule-documentation 1629ms (from cache)
41 silly pacote version manifest for eslint-rule-documentation@1.0.22 fetched in 1630ms
42 silly resolveWithNewModule eslint-rule-documentation@1.0.22 checking installable status
43 http fetch GET 304 https://registry.npmjs.org/crypto-random-string 1664ms (from cache)
44 silly pacote version manifest for crypto-random-string@1.0.0 fetched in 1665ms
45 silly resolveWithNewModule crypto-random-string@1.0.0 checking installable status
46 http fetch GET 304 https://registry.npmjs.org/atom-linter 5821ms (from cache)
47 silly pacote version manifest for atom-linter@10.0.0 fetched in 5822ms
48 silly resolveWithNewModule atom-linter@10.0.0 checking installable status
49 timing stage:rollbackFailedOptional Completed in 0ms
50 timing stage:runTopLevelLifecycles Completed in 12653ms
51 silly saveTree apm-install-dir-119111-7840-czu8nn.shyzp
51 silly saveTree └─┬ linter-eslint@8.5.2
51 silly saveTree   ├── atom-babel6-transpiler@1.2.0
51 silly saveTree   ├── atom-linter@10.0.0
51 silly saveTree   ├── atom-package-deps@5.0.0
51 silly saveTree   ├── consistent-path@2.0.3
51 silly saveTree   ├── crypto-random-string@1.0.0
51 silly saveTree   ├── eslint-rule-documentation@1.0.22
51 silly saveTree   ├── eslint@4.19.1
51 silly saveTree   ├── fs-plus@3.1.1
51 silly saveTree   ├── resolve-env@1.0.0
51 silly saveTree   └── user-home@2.0.0
52 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...1.3.1","dependencies"'
52 verbose stack     at JSON.parse (<anonymous>)
52 verbose stack     at parseJson (/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/json-parse-better-errors/index.js:7:17)
52 verbose stack     at consumeBody.call.then.buffer (/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-fetch-npm/src/body.js:96:50)
52 verbose stack     at <anonymous>
52 verbose stack     at process._tickCallback (internal/process/next_tick.js:188:7)
53 verbose cwd /tmp/apm-install-dir-119111-7840-czu8nn.shyzp
54 verbose Linux 4.20.6-200.fc29.x86_64
55 verbose argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/koalayt/.atom/.apm/.apmrc" "--userconfig" "/home/koalayt/.atom/.apmrc" "install" "https://www.atom.io/api/packages/linter-eslint/versions/8.5.2/tarball" "--runtime=electron" "--target=2.0.16" "--dist-url=https://atom.io/download/electron" "--arch=x64" "--global-style"
56 verbose node v8.9.3
57 verbose npm  v6.2.0
58 error Unexpected end of JSON input while parsing near '...1.3.1","dependencies"'
59 verbose exit [ 1, true ]
```

**Comment by KoaLaYT** [comment]
Follow the solution on https://github.com/AtomLinter/linter-eslint/issues/704
`linter-eslint` can be successfully installed
