### ISSUE TITLE
Uncaught Error: Cannot find module 'crypto-random-string'

### ISSUE THREAD

**Issue by chrisdrackett** [AtomLinter/linter-eslint#1268]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.37.0 x64
**Electron**: 2.0.18
**OS**: Mac OS X 10.14.4
**Thrown From**: [linter-eslint](https://github.com/AtomLinter/linter-eslint) package 8.5.5

### Stack Trace

Uncaught Error: Cannot find module 'crypto-random-string'

```
At module.js:545

Error: Cannot find module 'crypto-random-string'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:154765)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146072)
    at /packages/linter-eslint/src/helpers.js:5:1)
    at /packages/linter-eslint/src/helpers.js:348:2)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146782)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150329)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146072)
    at loadDeps (/packages/linter-eslint/src/main.js:24:15)
    at callBack (/packages/linter-eslint/src/main.js:38:5)
```

### Commands

```
```

### Non-Core Packages

```
atom-ide-ui 0.13.0 
atom-npm-outdated 0.19.0 
atom-typescript 13.2.1 
autocomplete-emojis 2.5.0 
bamboo-syntax 0.2.1 
bamboo-ui 0.3.0 
busy-signal 2.0.1 
color-picker 2.3.0 
docblockr 0.13.7 
flow-ide 1.13.0 
highlight-selected 0.16.0 
hyperclick 0.0.0 
ide-flowtype 0.24.0 
indent-guide-improved 1.4.13 
intentions 1.1.5 
language-babel 2.85.0 
language-graphql 1.0.0 
language-markdown 0.29.0 
linter 2.3.0 
linter-eslint 8.5.5 
linter-ui-default 1.7.1 
minimap 4.29.9 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
minimap-selection 4.5.0 
package-sync 1.1.0 
pigments 0.40.2 
prettier-atom 0.56.5 
smart-quotes-plus 3.0.1 
sort-lines 0.19.0 
status-bar-blame 2.0.3 
tree-view-panes 0.3.7 
zentabs 0.8.9 
```

**Comment by IanVS** [comment]
Hi, have you tried restarting atom, or uninstalling and re-installing linter-eslint?  It sounds like the installation didn't fully complete.

**Comment by chrisdrackett** [comment]
this seems to have fixed it, thanks!
