### ISSUE TITLE
Uncaught Error: Cannot find module 'user-home'

### ISSUE THREAD

**Issue by SymphonyOfDream** [AtomLinter/linter-eslint#1343]
[Enter steps to reproduce:]

1. Just installed Atom for first time, installed packages in order per https://docs.google.com/document/d/1_U2en_kdW4DlCQs5F07ZyBRIhPU4xAB88pCvbQWZ2ww/preview#heading=h.ajerrdh2bl57

2. Got out of Atom and back in, got the exception, even after letting linter-eslint install prereq's.

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Home
**Thrown From**: [linter-eslint](https://github.com/AtomLinter/linter-eslint) package 8.5.5

### Stack Trace

Uncaught Error: Cannot find module 'user-home'

```
At internal/modules/cjs/loader.js:586

Error: Cannot find module 'user-home'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.45.0/resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:155413)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:146745)
    at /packages/linter-eslint/src/is-config-at-home-root.js:5:1)
    at /packages/linter-eslint/src/is-config-at-home-root.js:16:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:146745)
    at loadDeps (/packages/linter-eslint/src/main.js:30:26)
    at callBack (/packages/linter-eslint/src/main.js:38:5)
```

### Commands

```
```

### Non-Core Packages

```
atom-html-preview 0.2.6 
atom-ternjs 0.20.0 
autoclose-html 0.23.0 
busy-signal 2.0.1 
csslint 1.2.0 
emmet 2.4.3 
intentions 1.1.5 
language-ejs 0.4.0 
linter 2.3.1 
linter-eslint 8.5.5 
linter-ui-default 1.8.1 
pigments 0.40.2 
Sublime-Style-Column-Selection 1.7.5 
```

**Comment by UziTech** [comment]
Is this still an issue?
