### ISSUE TITLE
Uncaught TypeError: The "path" argument must be one of type string, Buffer, or URL. Received type...

### ISSUE THREAD

**Issue by dungnt11** [AtomLinter/linter-eslint#1363]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.47.0 x64
**Electron**: 5.0.13
**OS**: "Manjaro Linux"
**Thrown From**: [linter-eslint](https://github.com/AtomLinter/linter-eslint) package 8.5.5

### Stack Trace

Uncaught TypeError: The "path" argument must be one of type string, Buffer, or URL. Received type boolean

```
At internal/fs/utils.js:423

TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]: The "path" argument must be one of type string, Buffer, or URL. Received type boolean
    at Object.open (fs.js:418:3)
    at Object.module.(anonymous function) [as open] (electron/js2c/asar.js:161:31)
    at Object.writeFile (fs.js:1224:6)
    at /packages/linter-eslint/node_modules/fs-plus/lib/fs-plus.js:300:21
    at /packages/linter-eslint/node_modules/mkdirp/index.js:49:26
    at FSReqCallback.oncomplete (fs.js:164:5)
```

### Commands

```
     -3:54 core:confirm (input.hidden-input)
     -0:52.1.0 remote-ssh:start (input.hidden-input)
     -0:42.4.0 remote-ssh:create-config (atom-notification.error.icon.icon-flame.native-key-bindings.has-close)
     -0:33 remote-ssh:toggle-search (atom-notification.error.icon.icon-flame.native-key-bindings.has-close)
     -0:29.7.0 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui.teletype-Authenticated)
     -0:10.2.0 remote-ssh:create-config (div.panels-item)
```

### Non-Core Packages

```
busy-signal 2.0.1 
intentions 1.1.5 
linter 2.3.1 
linter-eslint 8.5.5 
linter-ui-default 1.8.1 
platformio-ide-terminal 2.10.0 
Remote-SSH 0.11.0 
teletype 0.13.4 
```

**Comment by UziTech** [comment]
Please provide steps to reproduce if this is still an issue
