### ISSUE TITLE
Failed to activate the linter-eslint package

### ISSUE THREAD

**Issue by benjamincanac** [AtomLinter/linter-eslint#137]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.4
**Thrown From**: [linter-eslint](https://github.com/AtomLinter/linter-eslint) package, v1.0.14

### Stack Trace

Failed to activate the linter-eslint package

```
At Command failed: npm config get prefix
/bin/sh: npm: command not found


Error: Command failed: npm config get prefix
/bin/sh: npm: command not found

    at checkExecSyncError (child_process.js:1334:13)
    at execSync (child_process.js:1374:13)
    at Object.module.exports.findGlobalNPMdir (/Users/benjamincanac/.atom/packages/linter-eslint/lib/linter-eslint.coffee:212:23)
    at Object.module.exports.activate (/Users/benjamincanac/.atom/packages/linter-eslint/lib/linter-eslint.coffee:52:21)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:240:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:221:30
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:165:15)
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:213:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:452:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:436:29
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ],
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "projectHome": "/Users/benjamincanac/Work",
    "disabledPackages": [
      "symbols-view",
      "pigments",
      "symbol-gen",
      "git-plus"
    ]
  },
  "linter-eslint": {
    "useGlobalEslint": true,
    "showRuleIdInMessage": true,
    "disableWhenNoEslintrcFileInPath": true
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.0
atom-ctags, v4.1.4
atom-material-syntax, v0.1.2
atom-material-ui, v0.4.15
file-icons, v1.5.8
linter, v1.1.0
linter-eslint, v1.0.14

# Dev
No dev packages
```

**Comment by iam4x** [comment]
(dupe, see discussion in #128)
