### ISSUE TITLE
Uncaught Error: spawn UNKNOWN

### ISSUE THREAD

**Issue by WytchKing96** [AtomLinter/linter-eslint#1428]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.57.0 x64
**Electron**: 9.4.4
**OS**: Microsoft Windows 10 Home
**Thrown From**: [linter-eslint](https://github.com/AtomLinter/linter-eslint) package 8.6.6

### Stack Trace

Uncaught Error: spawn UNKNOWN

```
At internal/child_process.js:394

Error: spawn UNKNOWN
    at ChildProcess.spawn (internal/child_process.js:394:11)
    at spawn (child_process.js:549:9)
    at Object.fork (child_process.js:117:10)
    at new Task (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:14:41996)
    at Object.startWorker (/packages/linter-eslint/dist/helpers.js:41:14)
    at linterEslintStartWorker (/packages/linter-eslint/dist/main.js:37:13)
    at callBack (/packages/linter-eslint/dist/main.js:24:5)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-html-preview 0.2.6 
atom-ternjs 0.20.0 
autoclose-html 0.23.0 
csslint 1.2.0 
emmet 2.4.3 
language-ejs 0.4.0 
linter 3.3.1 
linter-eslint 8.6.6 
linter-ui-default 3.3.1 
pigments 0.40.6 
Sublime-Style-Column-Selection 1.7.5 
```

**Comment by UziTech** [comment]
Might be an install issue. Without reproduction steps I couldn't help more.
