### ISSUE TITLE
Uncaught Error: Cannot find module '$ATOM_HOME/packages/linter-eslint/node_modules/atom-package-d...

### ISSUE THREAD

**Issue by tj-26** [AtomLinter/linter-eslint#1429]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.57.0 x64
**Electron**: 9.4.4
**OS**: macOS 11.3.1
**Thrown From**: [linter-eslint](https://github.com/AtomLinter/linter-eslint) package 8.6.6

### Stack Trace

Uncaught Error: Cannot find module '/Users/tusharjain/.atom/packages/linter-eslint/node_modules/atom-package-deps/lib/index.js'. Please verify that the package.json has a valid "main" entry

```
At internal/modules/cjs/loader.js:309

Error: Cannot find module '/Users/tusharjain/.atom/packages/linter-eslint/node_modules/atom-package-deps/lib/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:301:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:532:18)
    at Module._resolveFilename (internal/modules/cjs/loader.js:784:27)
    at o._resolveFilename (electron/js2c/renderer_init.js:43:689)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:157820)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:149153)
    at linterEslintInstallPeerPackages (/packages/linter-eslint/dist/main.js:33:5)
    at callBack (/packages/linter-eslint/dist/main.js:24:5)
```

### Commands

```
     -0:18.1.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-clock 0.1.18 
atom-ide-ui 0.13.0 
autoclose 0.0.2 
autoclose-html 0.23.0 
flow-ide 1.13.0 
highlight-selected 0.17.0 
hyperclick 0.0.0 
ide-json 0.2.1 
ide-typescript 0.9.2 
intentions 1.1.5 
js-hyperclick 1.19.0 
linter 3.3.1 
linter-eslint 8.6.6 
minimap 4.39.14 
minimap-cursorline 1.0.4 
minimap-find-and-replace 5.0.8 
minimap-highlight-selected 4.6.5 
minimap-selection 4.5.4 
platformio-ide-terminal 2.10.1 
prettier-atom 0.60.1 
```

**Comment by UziTech** [comment]
uninstall and reinstall linter-eslint
