### ISSUE TITLE
TypeError: Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by ButuzGOL** [AtomLinter/linter-eslint#143]
Getting this error on lint

```
[Linter-ESLint] error while linting file
/Users/butuzgol/.atom/packages/linter-eslint/lib/linter-eslint.coffee:151 Cannot read property 'match' of undefined
/Users/butuzgol/.atom/packages/linter-eslint/lib/linter-eslint.coffee:152 TypeError: Cannot read property 'match' of undefined
  at TokenizedBuffer.module.exports.TokenizedBuffer.indentLevelForLine (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:669:23)
  at DisplayBuffer.module.exports.DisplayBuffer.indentLevelForLine (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:818:35)
  at TextEditor.module.exports.TextEditor.indentLevelForLine (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2243:33)
  at TextEditor.module.exports.TextEditor.indentationForBufferRow (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2215:19)
  at /Users/butuzgol/.atom/packages/linter-eslint/lib/linter-eslint.coffee:118:44
  at Array.map (native)
  at /Users/butuzgol/.atom/packages/linter-eslint/lib/linter-eslint.coffee:114:18
  at exports.allowUnsafeNewFunction (/Users/butuzgol/.atom/packages/linter-eslint/node_modules/loophole/lib/loophole.js:25:14)
  at Object.provider.lint (/Users/butuzgol/.atom/packages/linter-eslint/lib/linter-eslint.coffee:111:13)
  at /Users/butuzgol/.atom/packages/linter/lib/editor-linter.coffee:68:24
  at /Users/butuzgol/.atom/packages/linter/lib/editor-linter.coffee:67:25
  at Set.forEach (native)
  at EditorLinter.triggerLinters (/Users/butuzgol/.atom/packages/linter/lib/editor-linter.coffee:63:26)
  at EditorLinter.lint (/Users/butuzgol/.atom/packages/linter/lib/editor-linter.coffee:57:18)
  at /Users/butuzgol/.atom/packages/linter/lib/editor-linter.coffee:18:29
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:996:20)
  at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:978:19)
  at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:579:26)
  at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:535:18)
  at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:518:19)
  at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:592:35)
  at atom-workspace.atom.commands.add.core:save (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace-element.js:311:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)
```

**Comment by ButuzGOL** [comment]
Seems after update everything fine. Thanks

**Comment by parga** [comment]
updated to version 3.0.0 and im receiving the error above mentioned after restart Atom.

**Comment by ColtonProvias** [comment]
Also receiving the error in the latest version.

**Comment by robinwyss** [comment]
I am also getting the same error with the latest version.

**Comment by blaiprat** [comment]
I've seen this error caused by one of the rules in `.eslintrc` pointing to a not installed plugin, react-eslint in my case. 

To give it a shot remove all the content from `.eslintrc` (without removing the file) and try it with one of your files. If now it lints and you see some error there's something wrong in your configuration.

**Comment by robinwyss** [comment]
@blaiprat thanks for your hint, that solved it. It was babel-eslint in my case

**Comment by Sk1Zy** [comment]
Should produce a better error message when a plugin is missing.

**Comment by just-boris** [comment]
I am getting this error when `Use global eslint` option is disabled. 
How it can be?

Eslint from console is working fine

**Comment by steelbrain** [comment]
@just-boris Those two are not really connected, it's a random error in atom internals

**Comment by just-boris** [comment]
@steelbrain just updated to `5.1.0` and problem has been solved.
