### ISSUE TITLE
3.0.2: /linter-eslint.coffee:149 Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by ecoleman** [AtomLinter/linter-eslint#183]
Previous version worked properly, here's the error:

```
/Users/eric/.atom/packages/linter-eslint/lib/linter-eslint.coffee:148 [Linter-ESLint] error while linting file
/Users/eric/.atom/packages/linter-eslint/lib/linter-eslint.coffee:149 Cannot read property 'match' of undefined
/Users/eric/.atom/packages/linter-eslint/lib/linter-eslint.coffee:150 TypeError: Cannot read property 'match' of undefined
  at TokenizedBuffer.module.exports.TokenizedBuffer.indentLevelForLine (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:680:23)
  at DisplayBuffer.module.exports.DisplayBuffer.indentLevelForLine (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:820:35)
  at TextEditor.module.exports.TextEditor.indentLevelForLine (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2244:33)
  at TextEditor.module.exports.TextEditor.indentationForBufferRow (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2216:19)
  at /Users/eric/.atom/packages/linter-eslint/lib/linter-eslint.coffee:116:44
  at Array.map (native)
  at /Users/eric/.atom/packages/linter-eslint/lib/linter-eslint.coffee:112:18
  at exports.allowUnsafeNewFunction (/Users/eric/.atom/packages/linter-eslint/node_modules/loophole/lib/loophole.js:25:14)
  at Object.provider.lint (/Users/eric/.atom/packages/linter-eslint/lib/linter-eslint.coffee:109:13)
  at /Users/eric/.atom/packages/linter/lib/editor-linter.coffee:69:26
  at currentLinter (/Users/eric/.atom/packages/linter/lib/editor-linter.coffee:68:20)
  at /Users/eric/.atom/packages/linter/lib/editor-linter.coffee:82:23
  at Set.forEach (native)
  at EditorLinter.triggerLinters (/Users/eric/.atom/packages/linter/lib/editor-linter.coffee:64:26)
  at /Users/eric/.atom/packages/linter/lib/editor-linter.coffee:57:27
```

**Comment by ecoleman** [comment]
This was actually my fault... I had removed `lodash.assign` from my app's dependencies, but babel-eslint required it... Sorry!
