### ISSUE TITLE
linter-eslint@3.0.2 error while linting file

### ISSUE THREAD

**Issue by mirek** [AtomLinter/linter-eslint#193]
```
[Linter-ESLint] error while linting file
/Users/mirek/.atom/packages/linter-eslint/lib/linter-eslint.coffee:149 Cannot read property 'match' of undefined
/Users/mirek/.atom/packages/linter-eslint/lib/linter-eslint.coffee:150 TypeError: Cannot read property 'match' of undefined
  at TokenizedBuffer.module.exports.TokenizedBuffer.indentLevelForLine (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:680:23)
  at DisplayBuffer.module.exports.DisplayBuffer.indentLevelForLine (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:820:35)
  at TextEditor.module.exports.TextEditor.indentLevelForLine (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2250:33)
  at TextEditor.module.exports.TextEditor.indentationForBufferRow (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2222:19)
  at /Users/mirek/.atom/packages/linter-eslint/lib/linter-eslint.coffee:116:44
  at Array.map (native)
  at /Users/mirek/.atom/packages/linter-eslint/lib/linter-eslint.coffee:112:18
  at exports.allowUnsafeNewFunction (/Users/mirek/.atom/packages/linter-eslint/node_modules/loophole/lib/loophole.js:25:14)
  at Object.provider.lint (/Users/mirek/.atom/packages/linter-eslint/lib/linter-eslint.coffee:109:13)
  at Promise.then._this.emitter.emit.linter (/Users/mirek/.atom/packages/linter/lib/linter-registry.coffee:57:22)
  at LinterRegistry.triggerLinter (/Users/mirek/.atom/packages/linter/lib/linter-registry.coffee:56:16)
  at /Users/mirek/.atom/packages/linter/lib/linter-registry.coffee:50:17
  at Array.map (native)
  at /Users/mirek/.atom/packages/linter/lib/linter-registry.coffee:48:27
```

**Comment by mirek** [comment]
...basically every file shows:
![image](https://cloud.githubusercontent.com/assets/8561/9281678/2cbb1cc6-429d-11e5-910c-4cff327b0f78.png)

I've tried previous version `apm install linter-eslint@3.0.1` and it actually seems to be not working as well. Maybe it's recent atom update to `v1.0.7`.

**Comment by mirek** [comment]
https://github.com/AtomLinter/linter-eslint/blob/master/lib/linter-eslint.coffee#L116 `line` is `undefined`.

**Comment by mirek** [comment]
Map's callback argument is:

```
{
  "fatal": true,
  "severity": 2,
  "message": "attachComments needs range information"
}
```

...so this destructuring doesn't work properly.

**Comment by mirek** [comment]
Following https://github.com/eslint/eslint/issues/3177 advice updating babel-eslint from @3.1.23 to @4.0.5 `npm install babel-eslint --save-dev` did the trick.
