### ISSUE TITLE
Babel eslint issue

### ISSUE THREAD

**Issue by RaviVaranasi** [AtomLinter/linter-eslint#199]
I get the following exception. I have resinstalled the linter and babel-eslint plugin
```
 import Soap from 'soap-as-promised';
^^^^^^
SyntaxError: Unexpected reserved word
  at exports.runInThisContext (vm.js:53:16)
  at Module._compile (module.js:435:25)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:163:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at /project/node_modules/eslint/lib/load-rules.js:36:36
```

.eslintrc file 
```
{
    "env": {
        "es6": true,
        "node": true,
        "browser": false
    },
    "parser": "babel-eslint",
    "rules": {
        "strict": 0,
        "quotes": [
            2,
            "single"
        ],
        "linebreak-style": [
            2,
            "unix"
        ],
        "semi": [
            2,
            "always"
        ]
    },
    "globals": {

    },
    "ecmaFeatures":
    {
      "modules": true
    },
    "extends": "eslint:recommended"
}
```
package.json 
```
"devDependencies": {
    "babel-eslint": "^4.1.0",
    "eslint": "^1.2.1",
    "linter": "0.0.7",
    "mocha": "^2.2.5",
    "mocha-babel": "^3.0.0",
    "watch": "latest"
  }
```
atom installed plugins

<img width="875" alt="lint_plugin" src="https://cloud.githubusercontent.com/assets/51507/9511826/5254aed2-4c40-11e5-8769-4fddb4ba86cd.png">

Thanks for your time,
Ravi

**Comment by simon04** [comment]
I cannot reprocuce. This are the files I used: https://gist.github.com/8a88acce2012ea3f3327

Calling `node_modules/.bin/eslint index.js` as well as linting in Atom worked nicely and output
```
index.js
  1:10  error  Unexpected token
```

**Comment by jermspeaks** [comment]
+1

@simon04 What happens when you add an import statement in `index.js`?

**Comment by simon04** [comment]
Ah, this test https://gist.github.com/dbb383e751e0102ddcff reveals the following error as long as `npm install` has not been called, i.e., the plugin `babel-eslint` is not installed:

```
Error: Cannot find module 'eslint-config-eslint:recommended'
Referenced from: /tmp/dbb383e751e0102ddcff/.eslintrc
  at Module._resolveFilename (module.js:328:15)
  at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:270:25)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at loadConfig (/home/simon/.atom/packages/linter-eslint/node_modules/eslint/lib/config.js:96:48)
  at /home/simon/.atom/packages/linter-eslint/node_modules/eslint/lib/config.js:123:46
  at Array.reduceRight (native)
  at loadConfig (/home/simon/.atom/packages/linter-eslint/node_modules/eslint/lib/config.js:111:36)
  at getLocalConfig (/home/simon/.atom/packages/linter-eslint/node_modules/eslint/lib/config.js:225:23)
  at Config.getConfig (/home/simon/.atom/packages/linter-eslint/node_modules/eslint/lib/config.js:363:22)
  at CLIEngine.getConfigForFile (/home/simon/.atom/packages/linter-eslint/node_modules/eslint/lib/cli-engine.js:382:29)
  at /home/simon/.atom/packages/linter-eslint/lib/linter-eslint.coffee:90:29
  at exports.allowUnsafeNewFunction (/home/simon/.atom/packages/linter-eslint/node_modules/loophole/lib/loophole.js:25:14)
  at Object.provider.lint (/home/simon/.atom/packages/linter-eslint/lib/linter-eslint.coffee:89:11)
  at Promise.then._this.emitter.emit.linter (/home/simon/.atom/packages/linter/lib/linter-registry.coffee:59:22)
  at LinterRegistry.triggerLinter (/home/simon/.atom/packages/linter/lib/linter-registry.coffee:58:16)
  at /home/simon/.atom/packages/linter/lib/linter-registry.coffee:52:17
  at Array.map (native)
  at /home/simon/.atom/packages/linter/lib/linter-registry.coffee:50:27
```

**Comment by steelbrain** [comment]
Fixed by v5.0.0

**Comment by sethbergman** [comment]
Try this setting:

![](https://cloud.githubusercontent.com/assets/427137/14826214/b85fabf8-0b91-11e6-9786-8a6ea0d1affe.png)

You don't need to add `babel-eslint` as a dependency. Just check this setting in Atom.

**Comment by IanVS** [comment]
It really depends on your situation, normally you should install all of your project dependencies _as_ dependencies.  Meaning, `npm i --save-dev eslint babel-eslint`.  Global ESLint installation is not generally recommended.
