### ISSUE TITLE
EvalError when eslintRulesDir is set

### ISSUE THREAD

**Issue by mheitzibm** [AtomLinter/linter-eslint#206]
I'm using atom 1.0.11 on Ubuntu 14.04.  The only installed packages are linter 1.5.0 and linter-eslint 3.0.2.

When eslintRulesDir is set, I get an error like this every time I open or change a .js file.

EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".
    at Function.wrapfunction (/my-dir/node_modules/express/node_modules/depd/index.js:421:5)
    at Object.<anonymous> (/my-dir/node_modules/express/node_modules/send/index.js:156:47)
    at Module._compile (module.js:452:26)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:169:21)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Function.cls_wrapMethod (/my-dir/node_modules/newrelic/lib/shimmer.js:230:38)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (/my-dir/node_modules/express/lib/utils.js:16:12)

I see several issues like this were resolved in the past but I'm using the latest versions of atom and the linter packages.

**Comment by steelbrain** [comment]
Fixed by v5.0.0

**Comment by mheitzibm** [comment]
Yes, it's working now.  Thanks.
