### ISSUE TITLE
This provider feeds invalid line numbers to core APIs

### ISSUE THREAD

**Issue by steelbrain** [AtomLinter/linter-eslint#228]
```
TypeError: Cannot read property 'match' of undefined
  at TokenizedBuffer.module.exports.TokenizedBuffer.indentLevelForLine (/usr/share/atom/resources/app.asar/src/tokenized-buffer.js:680:23)
  at DisplayBuffer.module.exports.DisplayBuffer.indentLevelForLine (/usr/share/atom/resources/app.asar/src/display-buffer.js:817:35)
  at TextEditor.module.exports.TextEditor.indentLevelForLine (/usr/share/atom/resources/app.asar/src/text-editor.js:2284:33)
  at TextEditor.module.exports.TextEditor.indentationForBufferRow (/usr/share/atom/resources/app.asar/src/text-editor.js:2256:19)
  at /home/steel/.atom/packages/linter-eslint/lib/linter-eslint.coffee:112:44
  at Array.map (native)
  at /home/steel/.atom/packages/linter-eslint/lib/linter-eslint.coffee:110:18
  at exports.allowUnsafeNewFunction (/home/steel/.atom/packages/atom-ternjs/node_modules/loophole/lib/loophole.js:25:14)
  at Object.provider.lint (/home/steel/.atom/packages/linter-eslint/lib/linter-eslint.coffee:107:13)
  at promises.push.Promise.then._this.emitter.emit.linter (/home/steel/.atom/packages/linter/lib/linter-registry.js:103:28)
  at /home/steel/.atom/packages/linter/lib/linter-registry.js:102:25
  at Set.forEach (native)
  at LinterRegistry.lint (/home/steel/.atom/packages/linter/lib/linter-registry.js:100:20)
  at /home/steel/.atom/packages/linter/lib/linter.coffee:88:16
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at /home/steel/.atom/packages/linter/lib/editor-linter.js:91:30
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at /usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1271:25
```
linter-eslint 3.1.1
linter 1.8.1 (I have the master branch, the error is clearly not in it so doesn't matter)
Ref: https://github.com/AtomLinter/linter-eslint/blob/704fa7b3b9bec75bdd59a8377b51790cc511f031/lib/linter-eslint.coffee#L112

**Comment by Arcanemagus** [comment]
Marking as closed, if seen again we can re-file.
