### ISSUE TITLE
Error during update to 5.0.1 from 4.0.0

### ISSUE THREAD

**Issue by Grmiade** [AtomLinter/linter-eslint#268]
[Enter steps to reproduce below:]

1. When i install the new version 5.0.1 (before 4.0.0)

**Atom Version**: 1.2.0
**System**: Mac OS X 10.11.1
**Thrown From**: [linter-eslint](https://github.com/AtomLinter/linter-eslint) package, v5.0.1

### Stack Trace

Failed to activate the linter-eslint package

```
At packageName is required

Error: packageName is required
    at Object.install (/Users/jeremyfauvel/.atom/packages/linter-eslint/node_modules/atom-package-deps/lib/main.js:10:2)
    at Object.activate (/Users/jeremyfauvel/.atom/packages/linter-eslint/lib/main.js:34:34)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:170:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:150:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:143:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:140:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:512:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:385:60
    at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:220:18
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

### Commands

```
     -0:12.9.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {},
  "linter-eslint": {
    "disableWhenNoEslintrcFileInPath": true,
    "lintHtmlFiles": true
  }
}
```

### Installed Packages

```coffee
# User
emmet, v2.3.14
language-babel, v2.5.0
language-stylus, v0.2.0
linter, v1.11.1
linter-eslint, v5.0.1
webbox-color, v0.5.9

# Dev
No dev packages
```

**Comment by steelbrain** [comment]
Restart and it should be fixed, it's an atom upgrade cache issue :)
