### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by oaleynik** [AtomLinter/linter-eslint#28]
[Enter steps to reproduce below:]

1. Prepare JavaScript file with following content:  
```javascript
var left, aSize, bSize;

aSize = {
  width: 800,
  height: 600
};

bSize = {
  width: 200,
  height: 100
};
```
1. On the next line enter the statement `left = (aSize.width/2) - ()`
P.S. Should be `left = (aSize.width/2) - (bSize.width/2)`

**Atom Version**: 0.177.0
**System**: Mac OS X 10.10.2
**Thrown From**: [linter-eslint](https://github.com/AtomLinter/linter-eslint) package, v0.3.1

### Stack Trace

Uncaught TypeError: Cannot read property '0' of undefined

```
At /Users/Oleg/.atom/packages/linter-eslint/node_modules/eslint/lib/token-store.js:181

TypeError: Cannot read property '0' of undefined
  at EventEmitter.api.getTokensBetween (/Users/Oleg/.atom/packages/linter-eslint/node_modules/eslint/lib/token-store.js:181:31)
  at RuleContext.(anonymous function) [as getTokensBetween] (/Users/Oleg/.atom/packages/linter-eslint/node_modules/eslint/lib/rule-context.js:79:33)
  at validateBetween (/Users/Oleg/.atom/packages/linter-eslint/node_modules/eslint/lib/rules/no-multi-spaces.js:91:30)
  at EventEmitter.checkExpression (/Users/Oleg/.atom/packages/linter-eslint/node_modules/eslint/lib/rules/no-multi-spaces.js:106:9)
  at EventEmitter.emit (events.js:138:20)
  at Controller.controller.traverse.enter (/Users/Oleg/.atom/packages/linter-eslint/node_modules/eslint/lib/eslint.js:646:25)
  at Controller.__execute (/Users/Oleg/.atom/packages/linter-eslint/node_modules/eslint/node_modules/estraverse/estraverse.js:397:31)
  at Controller.traverse (/Users/Oleg/.atom/packages/linter-eslint/node_modules/eslint/node_modules/estraverse/estraverse.js:495:28)
  at EventEmitter.module.exports.api.verify (/Users/Oleg/.atom/packages/linter-eslint/node_modules/eslint/lib/eslint.js:639:24)
  at LinterESLint.lintFile (/Users/Oleg/.atom/packages/linter-eslint/lib/linter-eslint.coffee:62:21)
  at /Users/Oleg/.atom/packages/linter/lib/linter-view.coffee:150:18
  at Array.forEach (native)
  at /Users/Oleg/.atom/packages/linter/lib/linter-view.coffee:149:18
  at FSReqWrap.oncomplete (fs.js:100:15)

```

### Commands

```
     -0:31.8 editor:newline (atom-text-editor.editor.is-focused)
     -0:31.6 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:31.6 editor:newline (atom-text-editor.editor.is-focused)
  3x -0:29.7 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:25.5 core:move-left (atom-text-editor.editor.is-focused)
     -0:25.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:25.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:19.2 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:19.2 editor:newline (atom-text-editor.editor.is-focused)
     -0:16.2 core:move-down (atom-text-editor.editor.is-focused)
     -0:15.8 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:15.7 editor:newline (atom-text-editor.editor.is-focused)
     -0:15.6 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:15.6 editor:newline (atom-text-editor.editor.is-focused)
  5x -0:09.5 core:backspace (atom-text-editor.editor.is-focused)
     -0:04.3 core:move-right (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  },
  "linter-eslint": {}
}
```

### Installed Packages

```coffee
# User
atom-handlebars, v0.4.0
editorconfig, v0.3.0
emmet, v2.3.3
language-typescript, v0.15.0
linter, v0.11.1
linter-eslint, v0.3.1
react, v0.9.8
seti-syntax, v0.3.1
seti-ui, v0.6.3

# Dev
No dev packages
```

/cc @atom/core

**Comment by jfaissolle** [comment]
This is an eslint problem. Dependency is now bumped to `^0.14.0`. Does it solve the problem ?

**Comment by oaleynik** [comment]
@jfaissolle no, now it's even worst - https://www.dropbox.com/s/umxd6tggm0nj89c/Screenshot%202015-02-09%2016.45.34.png?dl=0

**Comment by jfaissolle** [comment]
The problem can be reproduced with the `eslint` command line tool. I have submitted eslint/eslint#1816.

**Comment by oaleynik** [comment]
@jfaissolle thanks

**Comment by jfaissolle** [comment]
Fixed in eslint/espree

**Comment by oaleynik** [comment]
@jfaissolle thanks!

**Comment by FOr3st** [comment]
I am getting the same error in render function with spread operator:

```javascript
render() {
   return (
      <div>
         <div>Value</div>
         {...props.value}
      </div>
   )
}
```

**Comment by Arcanemagus** [comment]
@FOr3st If you are still seeing this with the latest version of `eslint` please file a new issue with the information requested in the template.
