### ISSUE TITLE
packageName is required

### ISSUE THREAD

**Issue by mojodna** [AtomLinter/linter-eslint#283]
1. Start with linter-eslint 4.0.0
2. Upgrade to 5.1.0

**Atom Version**: 1.2.0
**System**: Mac OS X 10.11.1
**Thrown From**: [linter-eslint](https://github.com/AtomLinter/linter-eslint) package, v5.1.0

### Stack Trace

Failed to activate the linter-eslint package

```
At packageName is required

Error: packageName is required
    at Object.install (/Users/seth/.atom/packages/linter-eslint/node_modules/atom-package-deps/lib/main.js:19:27)
    at Object.activate (/Users/seth/.atom/packages/linter-eslint/lib/main.js:40:34)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:170:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:150:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:143:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:140:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:512:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:385:60
    at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
    at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:235:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

**Comment by steelbrain** [comment]
It's a package upgrade cache problem, restart and it should work

**Comment by mojodna** [comment]
It does, though it's a potentially scary warning that I've experienced on different machines, so I was wondering if the underlying cause is fixable, either within linter-eslint or Atom itself.

**Comment by steelbrain** [comment]
@mojodna Here's the cause:

Atom wants to achieve super-speed so it caches all the requires, if we require a module and then require it again, it does not require the new changed one from the file system but serves the one already in cache. This type of change resulted in the problem above. In the previous version a `packageName` was required but in the latest version it's optional.

It can be fixed, You could try asking the atom core guys about that :)

**Comment by mojodna** [comment]
Aha, cool.  Thanks!
