### ISSUE TITLE
Failed to activate the linter-php package

### ISSUE THREAD

**Issue by wataruoguchi** [AtomLinter/linter-eslint#298]
[Enter steps to reproduce below:]

1. Open any kind of file
2. Then the error message popped up

**Atom Version**: 1.2.1
**System**: Mac OS X 10.11.1
**Thrown From**: [linter-eslint](https://github.com/AtomLinter/linter-eslint) package, v5.2.0

### Stack Trace

Failed to activate the linter-php package

```
At deprecationSite.getFileName is not a function

TypeError: deprecationSite.getFileName is not a function
    at Object.global.__grim__.deprecate (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/grim/lib/grim.js:56:36)
    at Object.defineProperty.get [as TextEditor] (/Applications/Atom.app/Contents/Resources/app.asar/exports/atom.js:38:14)
    at Object.<anonymous> (/Users/admin/.atom/packages/linter-eslint/node_modules/atom-linter/lib/helpers.coffee:1:40)
    at Object.<anonymous> (/Users/admin/.atom/packages/linter-eslint/node_modules/atom-linter/lib/helpers.coffee:1:1)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/admin/.atom/packages/linter-php/lib/main.coffee:2:11)
    at Object.<anonymous> (/Users/admin/.atom/packages/linter-php/lib/main.coffee:1:1)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:661:34)
    at Package.module.exports.Package.activateConfig (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:188:14)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:166:14)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:784:28
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at PackageManager.module.exports.PackageManager.triggerActivationHook (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:528:41)
    at TokenizedBuffer.module.exports.TokenizedBuffer.setGrammar (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:181:27)
    at TokenizedBuffer.module.exports.TokenizedBuffer.grammarAddedOrUpdated (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:121:23)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:3:61
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at GrammarRegistry.module.exports.GrammarRegistry.addGrammar (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/first-mate/lib/grammar-registry.js:75:20)
    at Grammar.module.exports.Grammar.activate (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/first-mate/lib/grammar.js:223:48)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:484:25
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/first-mate/lib/grammar-registry.js:120:55
    at parseContents (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/season/lib/cson.js:119:7)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/season/lib/cson.js:204:20
    at ATOM_SHELL_ASAR.js:375:16
    at FSReqWrap.wrapper [as oncomplete] (fs.js:576:17)
```

### Commands

```
```

### Config

```json
{
  "core": {},
  "linter-eslint": {
    "useGlobalEslint": true,
    "globalNodePath": "/usr/local"
  }
}
```

### Installed Packages

```coffee
# User
Remote-FTP, v0.7.10
color-picker, v2.0.13
css-snippets, v0.9.0
emmet, v2.3.14
highlight-column, v0.5.0
highlight-line, v0.11.0
javascript-snippets, v1.0.0
jquery-snippets, v11.0.0
linter, v1.11.2
linter-coffeelint, v1.1.2
linter-eslint, v5.2.0
linter-php, v1.1.1
minimap, v4.16.0
nuclide-remote-projects, v0.0.32
php-cs-fixer, v2.5.1
php-twig, v4.0.0
remote-edit, v1.8.22
term3, v0.19.2

# Dev
No dev packages
```

**Comment by steelbrain** [comment]
This message is clearly a problem in `linter-php`, just the atom bug reporter is confused about it. cc @Arcanemagus

**Comment by Arcanemagus** [comment]
@wataruoguchi can you open a [new issue](https://github.com/AtomLinter/linter-php/issues/new) over there with this so we can try debugging this further? I think this is actually an Atom issue but I can't be sure.

**Comment by wataruoguchi** [comment]
@steelbrain @Arcanemagus Hi guys,
I guess this is an Atom's issue since I don't see the same error at my personal env. (The error I reported is via my work env, same OS, similar packages tho.)
I will report it if I see this again after a week.
I really appreciate your support and great work for the open source world!
