### ISSUE TITLE
Uncaught TypeError: Cannot read property 'loc' of undefined

### ISSUE THREAD

**Issue by dominicbarnes** [AtomLinter/linter-eslint#30]
Below details an exception I keep seeing when I was using a ternary expression as a function argument: (with ES6 template strings)

```js
o.url = database.mock.url(id ? `${id}` : '');
```

As soon as I remove the template string, it works properly again.

It *appears* that newer releases of ESLint (`0.14+`) have [fixes](https://github.com/eslint/eslint/blob/master/CHANGELOG.md) for this particular rule, so this may be as simple as updating the `eslint` dependency.

Thanks! :D

**Atom Version**: 0.177.0
**System**: Mac OS X 10.10.2
**Thrown From**: [linter-eslint](https://github.com/AtomLinter/linter-eslint) package, v0.3.1

### Stack Trace

Uncaught TypeError: Cannot read property 'loc' of undefined

```
At /Users/dominic/.atom/packages/linter-eslint/node_modules/eslint/lib/rules/no-multi-spaces.js:73

TypeError: Cannot read property 'loc' of undefined
  at validate (/Users/dominic/.atom/packages/linter-eslint/node_modules/eslint/lib/rules/no-multi-spaces.js:73:17)
  at validateBetween (/Users/dominic/.atom/packages/linter-eslint/node_modules/eslint/lib/rules/no-multi-spaces.js:95:9)
  at EventEmitter.checkConditional (/Users/dominic/.atom/packages/linter-eslint/node_modules/eslint/lib/rules/no-multi-spaces.js:117:9)
  at EventEmitter.emit (events.js:138:20)
  at Controller.controller.traverse.enter (/Users/dominic/.atom/packages/linter-eslint/node_modules/eslint/lib/eslint.js:646:25)
  at Controller.__execute (/Users/dominic/.atom/packages/linter-eslint/node_modules/eslint/node_modules/estraverse/estraverse.js:397:31)
  at Controller.traverse (/Users/dominic/.atom/packages/linter-eslint/node_modules/eslint/node_modules/estraverse/estraverse.js:495:28)
  at EventEmitter.module.exports.api.verify (/Users/dominic/.atom/packages/linter-eslint/node_modules/eslint/lib/eslint.js:639:24)
  at LinterESLint.lintFile (/Users/dominic/.atom/packages/linter-eslint/lib/linter-eslint.coffee:62:21)
  at /Users/dominic/.atom/packages/linter/lib/linter-view.coffee:150:18
  at Array.forEach (native)
  at /Users/dominic/.atom/packages/linter/lib/linter-view.coffee:149:18
  at FSReqWrap.oncomplete (fs.js:100:15)

```

### Commands

```
     -2:18.6 core:move-up (input.hidden-input)
     -2:18.1 editor:delete-to-beginning-of-line (input.hidden-input)
     -2:17.9 core:backspace (input.hidden-input)
     -2:17.3 core:move-down (input.hidden-input)
     -2:15.2 core:undo (input.hidden-input)
     -2:13.5 editor:delete-to-beginning-of-line (input.hidden-input)
     -2:13.3 core:backspace (input.hidden-input)
     -2:12.7 core:move-down (input.hidden-input)
  2x -2:12.6 core:move-left (input.hidden-input)
  7x -2:10.3 core:backspace (input.hidden-input)
  2x -1:57.4 core:move-right (input.hidden-input)
     -1:54.2 core:save (input.hidden-input)
     -1:08.9 editor:delete-to-beginning-of-word (input.hidden-input)
  4x -1:08.6 core:backspace (input.hidden-input)
     -1:07.9 core:save (input.hidden-input)
  2x -0:04.1 core:close (input.hidden-input)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.21.2
atom-color-highlight, v3.0.6
atom-handlebars, v0.4.0
color-picker, v1.4.4
docblockr, v0.5.8
emmet, v2.3.3
file-icons, v1.4.8
file-types, v0.3.0
filesize, v0.1.1
git-tab-status, v1.5.3
highlight-selected, v0.7.0
language-gitignore, v0.1.1
language-nginx, v0.4.0
linter, v0.11.1
linter-eslint, v0.3.1
svg-preview, v0.4.0
trailing-spaces, v0.2.4

# Dev
No dev packages
```

/cc @atom/core

**Comment by jfaissolle** [comment]
This is an eslint problem. Dependency is now bumped to `^0.14.0`. Does it solve the problem ?

**Comment by dominicbarnes** [comment]
Looks good! Thanks :)
