### ISSUE TITLE
Error: Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by snowcxt** [AtomLinter/linter-eslint#316]
Updated to 5.2.1. and get error `Error: Cannot read property 'type' of undefined`whenever I type something. Here's the details: 

```
TypeError: Cannot read property 'type' of undefined
    at getPropertyName (D:\Thomas\spttc-portal\node_modules\eslint-plugin-react\lib\rules\sort-comp.js:135:23)
    at Array.map (native)
    at checkPropsOrder (D:\Thomas\spttc-portal\node_modules\eslint-plugin-react\lib\rules\sort-comp.js:299:38)
    at EventEmitter.Program:exit (D:\Thomas\spttc-portal\node_modules\eslint-plugin-react\lib\rules\sort-comp.js:345:9)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
    at NodeEventGenerator.leaveNode (D:\Thomas\spttc-portal\node_modules\eslint\lib\util\node-event-generator.js:51:22)
    at CommentEventGenerator.leaveNode (D:\Thomas\spttc-portal\node_modules\eslint\lib\util\comment-event-generator.js:111:23)
    at Controller.controller.traverse.leave (D:\Thomas\spttc-portal\node_modules\eslint\lib\eslint.js:785:36)
    at Controller.__execute (D:\Thomas\spttc-portal\node_modules\eslint\node_modules\estraverse\estraverse.js:397:31)
```

**Comment by Arcanemagus** [comment]
This looks like something bubbling up from `eslint-plugin-react`, are you sure this is an issue with `linter-eslint` and not the local `eslint` setup?

**Comment by snowcxt** [comment]
Because everything was OK before the update. So how can I check if the local eslint setup?

**Comment by Arcanemagus** [comment]
Which version did you update from?

You should be able to do:
```batch
cd D:\Thomas\spttc-portal\
.\node_modules\.bin\eslint foo.js
```

Replacing `foo.js` with the file you were working on of course.

**Comment by snowcxt** [comment]
I don't remember which version I updated from.

I ran the script but nothing happened. No info, errors, no files generated/modified.

**Comment by Arcanemagus** [comment]
Can you post your `package.json`? Is this triggering on all files, or just a single one?

**Comment by snowcxt** [comment]
I have this trouble for all the jsx files

Here's the dependencies and devDependencies:

```json
"dependencies": {
    "async": "^1.5.0",
    "babel": "6.0.12",
    "babel-plugin-typecheck": "2.0.0",
    "bcryptjs": "^2.3.0",
    "body-parser": "1.14.1",
    "compression": "1.6.0",
    "connect-redis": "^3.0.1",
    "cors": "^2.7.1",
    "express": "4.13.3",
    "express-session": "^1.12.1",
    "file-loader": "0.8.4",
    "handlebars": "^4.0.5",
    "history": "1.13.0",
    "hoist-non-react-statics": "^1.0.3",
    "http-proxy": "1.12.0",
    "ink-react": "0.0.4",
    "jsonwebtoken": "^5.4.1",
    "juice": "^1.6.0",
    "knex": "^0.9.0",
    "less": "2.5.3",
    "less-loader": "2.2.1",
    "lodash": "^3.10.1",
    "lru-memoize": "1.0.0",
    "map-props": "1.0.0",
    "moment": "^2.10.6",
    "multireducer": "1.0.2",
    "nodemailer": "^1.10.0",
    "nodemailer-sendgrid-transport": "^0.2.0",
    "pg": "^4.4.3",
    "piping": "0.3.0",
    "pretty-error": "1.2.0",
    "query-string": "3.0.0",
    "react": "^0.14.3",
    "react-addons-css-transition-group": "^0.14.3",
    "react-datetime": "^2.0.0",
    "react-document-meta": "2.0.0",
    "react-dom": "0.14.3",
    "react-inline-css": "2.0.0",
    "react-redux": "^4.0.0",
    "react-router": "1.0.0-rc3",
    "redux": "3.0.4",
    "redux-form": "3.0.5",
    "request": "^2.67.0",
    "serialize-javascript": "1.1.2",
    "serve-favicon": "2.3.0",
    "serve-static": "1.10.0",
    "spttc-validation": "0.0.2",
    "superagent": "1.4.0",
    "url-loader": "0.5.6",
    "webpack-isomorphic-tools": "2.2.1"
  },
  "devDependencies": {
    "autoprefixer-loader": "^3.1.0",
    "babel-core": "^5.8.25",
    "babel-eslint": "^4.1.3",
    "babel-loader": "^5.3.2",
    "babel-plugin-react-transform": "^1.1.1",
    "babel-runtime": "^6.0.12",
    "better-npm-run": "^0.0.3",
    "bootstrap-sass": "^3.3.5",
    "bootstrap-sass-loader": "^1.0.9",
    "chai": "^3.3.0",
    "clean-webpack-plugin": "^0.1.3",
    "concurrently": "^0.1.1",
    "css-loader": "^0.20.1",
    "eslint": "1.8.0",
    "eslint-config-airbnb": "^0.1.0",
    "eslint-loader": "^1.0.0",
    "eslint-plugin-import": "^0.8.0",
    "eslint-plugin-react": "^3.5.0",
    "extract-text-webpack-plugin": "^0.8.2",
    "font-awesome": "^4.4.0",
    "font-awesome-webpack": "0.0.4",
    "json-loader": "^0.5.3",
    "karma": "^0.13.10",
    "karma-chrome-launcher": "^0.2.0",
    "karma-cli": "^0.1.1",
    "karma-firefox-launcher": "^0.1.6",
    "karma-mocha": "^0.2.0",
    "karma-mocha-reporter": "^1.1.1",
    "karma-sourcemap-loader": "^0.3.5",
    "karma-webpack": "^1.7.0",
    "mocha": "^2.3.3",
    "node-sass": "^3.3.3",
    "react-a11y": "^0.2.6",
    "react-addons-test-utils": "^0.14.0",
    "react-transform-catch-errors": "^1.0.0",
    "react-transform-hmr": "^1.0.1",
    "redbox-react": "^1.1.1",
    "redux-devtools": "^3.0.0-beta-3",
    "redux-devtools-dock-monitor": "^1.0.0-beta-3",
    "redux-devtools-log-monitor": "^1.0.0-beta-3",
    "redux-router": "1.0.0-beta3",
    "sass-loader": "^3.0.0",
    "strip-loader": "^0.1.0",
    "style-loader": "^0.13.0",
    "webpack": "^1.12.2",
    "webpack-dev-middleware": "^1.2.0",
    "webpack-hot-middleware": "^2.4.1"
  }
```

**Comment by IanVS** [comment]
It looks like eslint-plugin-react just released a new version a few hours ago: https://github.com/yannickcr/eslint-plugin-react/releases/tag/v3.10.0

I suggest downgrading to the previous version to see if that helps.

**Comment by snowcxt** [comment]
Thank you very much! It's working now

**Comment by IanVS** [comment]
Cool.  You should also submit an issue to that repo, then, so they can look into it.

**Comment by Arcanemagus** [comment]
Marking this as closed based on the above comments.
