### ISSUE TITLE
Failed to activate the linter-eslint package

### ISSUE THREAD

**Issue by dlwalsh** [AtomLinter/linter-eslint#320]
I've been getting this error ever since updating the linter & linter-eslint packages.

The error box tells me this issue has already been logged as https://github.com/AtomLinter/linter-eslint/issues/269, but in fact this is a different issue.

I actually got the output at https://github.com/AtomLinter/linter-eslint/issues/269 upon updating. But after restarting Atom I got the following error, and have done every time I've restarted the application.

**Atom Version**: 1.2.3
**System**: Mac OS X 10.11.1
**Thrown From**: [linter-eslint](https://github.com/AtomLinter/linter-eslint) package, v5.2.1

### Stack Trace

Failed to activate the linter-eslint package

```
At require(...)(...)[1].getFileName is not a function

TypeError: require(...)(...)[1].getFileName is not a function
    at Object.install (/Users/david/.atom/packages/linter-eslint/node_modules/atom-package-deps/lib/main.js:15:47)
    at Object.activate (/Users/david/.atom/packages/linter-eslint/lib/main.js:53:34)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:170:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:150:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:143:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:140:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:512:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:495:29
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:311:16)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "base16-tomorrow-light-theme"
    ],
    "disabledPackages": [
      "keybinding-resolver"
    ]
  },
  "linter-eslint": {
    "useGlobalEslint": true,
    "globalNodePath": "/usr/local"
  }
}
```

### Installed Packages

```coffee
# User
linter, v1.11.2
linter-eslint, v5.2.1

# Dev
No dev packages
```

**Comment by Arcanemagus** [comment]
Looks like it didn't properly install the package, can you try shutting down Atom, completely deleting the folder, and then running `apm install linter-eslint`?

**Comment by Arcanemagus** [comment]
Nevermind, looks like a recent update to `package-deps` broke this.

**Comment by schoeffman** [comment]
Also seeing this issue. Downgraded to `apm install linter@1.10.0` and `apm install linter-eslint@4.0.0` for now.

**Comment by steelbrain** [comment]
This is a bug in `atom-package-deps`'s dependency `callsite`, it's not cross platform, I'm working on an alternative

**Comment by fabiobiondi** [comment]
Thanks @shoeffman. 
Your solution is the only one that worked for me

**Comment by steelbrain** [comment]
@fabiobiondi For the record, this works too

```
cd ~/.atom/packages/linter-eslint
rm -rf node_modules/atom-package-deps
npm install atom-package-deps@3.0.2
```

**Comment by maxvipon** [comment]
I faced this issue with `linter-eslint@5.2.7` and `linter@1.11.3`.

**Comment by Arcanemagus** [comment]
@maxvipon Can you please file a new issue with your full stack trace? The bug in this issue has long been fixed.

**Comment by maxvipon** [comment]
@Arcanemagus hm… It gone.

**Comment by forestgagnon** [comment]
@Arcanemagus I've just gotten this same issue

```
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.13.1
**Electron Version**: 1.3.13
**System**: Mac OS X 10.11.6
**Thrown From**: [linter-eslint](https://github.com/AtomLinter/linter-eslint) package, v8.1.0


### Stack Trace

Failed to activate the linter-eslint package

```
At Cannot find module 'process-communication'

Error: Cannot find module 'process-communication'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/fgagno/.atom/packages/linter-eslint/lib/helpers.js:170:29)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:109:30)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/fgagno/.atom/packages/linter-eslint/lib/main.js:10:16)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:109:30)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:766:27)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:181:16)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:164:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:94:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:157:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:154:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:550:34)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:531:29
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:526:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:508:46)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:831:28
```

### Commands

```
     -0:00.8.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.seti-compact.seti-roboto.theme-atom-material-syntax-dark.theme-seti-ui)
```

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".hgrc"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "linter-markdown",
      "metrics",
      "exception-reporting",
      "activate-power-mode",
      "welcome",
      "background-tips",
      "linter-clang",
      "autocomplete-ruby",
      "double-tag",
      "linter-ruby",
      "language-gfm",
      "node-debugger",
      "hyperclick",
      "autoclose-html"
    ],
    "packagesWithKeymapsDisabled": [
      "sort-lines"
    ],
    "telemetryConsent": "no",
    "themes": [
      "seti-ui",
      "atom-material-syntax-dark"
    ]
  },
  "linter-eslint": {
    "disableWhenNoEslintConfig": false,
    "eslintrcPath": "~/.eslintrc.json",
    "globalNodePath": "/usr/local",
    "useGlobalEslint": true
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v1.2.0 (inactive)
atom-beautify, v0.29.17 (inactive)
atom-clock, v0.1.3 (inactive)
atom-material-syntax, v1.0.2 (inactive)
atom-material-syntax-dark, v0.2.7 (inactive)
atom-material-ui, v1.3.9 (inactive)
atom-reverser, v2.6.0 (inactive)
atom-ternjs, v0.17.0 (inactive)
atomic-chrome, v0.3.0 (inactive)
auto-indent, v0.5.0 (inactive)
autoclose-html, v0.23.0 (inactive)
autocomplete-modules, v1.6.7 (inactive)
autocomplete-paths, v1.0.5 (inactive)
autocomplete-ruby, v0.2.5 (inactive)
autocomplete-webgl, v1.1.0 (inactive)
blame, v0.10.2 (inactive)
change-case, v0.6.3 (inactive)
character-table, v0.4.3 (inactive)
charcode-display, v0.2.1 (inactive)
color-picker, v2.2.4 (inactive)
custom-title, v1.0.1 (inactive)
docblockr, v0.9.1 (inactive)
double-tag, v0.4.0 (inactive)
editorconfig, v2.2.0 (inactive)
expand-selection-to-quotes, v0.11.0 (inactive)
file-icons, v2.0.13 (inactive)
filesize, v2.0.4 (inactive)
flex-tool-bar, v0.11.0 (inactive)
git-plus, v7.2.0 (inactive)
git-time-machine, v1.5.4 (inactive)
highlight-selected, v0.12.0 (inactive)
hyperclick, v0.0.40 (inactive)
indent-guide-improved, v1.4.12 (inactive)
js-hyperclick, v1.10.1 (inactive)
jumpy, v3.1.3 (inactive)
language-csv, v1.1.2 (inactive)
language-latex, v1.0.0 (inactive)
language-markdown, v0.19.1 (inactive)
linter, v1.11.21 (inactive)
linter-clang, v3.4.6 (inactive)
linter-csslint, v1.3.3 (inactive)
linter-eslint, v8.1.0 (inactive)
linter-js-yaml, v1.2.6 (inactive)
linter-jsonlint, v1.3.0 (inactive)
linter-markdown, v3.1.0 (inactive)
linter-rubocop, v0.5.3 (inactive)
linter-ruby, v1.2.4 (inactive)
linter-sass-lint, v1.7.4 (inactive)
markdown-pdf, v1.5.0 (inactive)
maximize-panes, v0.2.0 (inactive)
merge-conflicts, v1.4.4 (inactive)
minimap, v4.26.8 (inactive)
minimap-bookmarks, v0.4.2 (inactive)
minimap-codeglance, v0.4.5 (inactive)
minimap-cursorline, v0.2.0 (inactive)
minimap-highlight-selected, v4.5.0 (inactive)
minimap-pigments, v0.2.2 (inactive)
node-debugger, v1.10.0 (inactive)
one-dark-material-syntax, v1.0.3 (inactive)
package-sync, v1.1.0 (inactive)
pdf-view, v0.54.0 (inactive)
pigments, v0.39.0 (inactive)
project-manager, v3.3.3 (inactive)
qolor, v0.4.1 (inactive)
react, v0.16.2 (inactive)
ruby-block, v0.3.6 (inactive)
seti-syntax, v1.0.1 (inactive)
seti-ui, v1.4.0 (inactive)
sort-lines, v0.14.0 (inactive)
todo-show, v1.9.0 (inactive)
toggle-quotes, v1.0.0 (inactive)
tool-bar, v1.0.1 (inactive)
trailing-semicolon, v1.1.0 (inactive)
tree-view-git-status, v1.3.0 (inactive)
windows-carriage-return-remover, v0.1.3 (inactive)
wordcount, v2.10.3 (inactive)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (inactive)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (inactive)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (inactive)
archive-view, v0.62.0 (inactive)
autocomplete-atom-api, v0.10.0 (inactive)
autocomplete-css, v0.14.1 (inactive)
autocomplete-html, v0.7.2 (inactive)
autocomplete-plus, v2.33.1 (inactive)
autocomplete-snippets, v1.11.0 (inactive)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (inactive)
background-tips, v0.26.1 (inactive)
bookmarks, v0.43.2 (inactive)
bracket-matcher, v0.85.1 (inactive)
command-palette, v0.39.1 (inactive)
deprecation-cop, v0.55.1 (inactive)
dev-live-reload, v0.47.0 (inactive)
encoding-selector, v0.22.0 (inactive)
exception-reporting, v0.40.0 (inactive)
find-and-replace, v0.204.5 (inactive)
fuzzy-finder, v1.4.0 (inactive)
git-diff, v1.2.0 (inactive)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (inactive)
image-view, v0.60.0 (inactive)
incompatible-packages, v0.26.1 (inactive)
keybinding-resolver, v0.35.0 (inactive)
line-ending-selector, v0.5.1 (inactive)
link, v0.31.2 (inactive)
markdown-preview, v0.159.3 (inactive)
metrics, v1.1.3 (inactive)
notifications, v0.65.1 (inactive)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (inactive)
snippets, v1.0.4 (inactive)
spell-check, v0.68.5 (inactive)
status-bar, v1.6.0 (inactive)
styleguide, v0.48.0 (inactive)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (inactive)
timecop, v0.33.2 (inactive)
tree-view, v0.211.1 (inactive)
update-package-dependencies, v0.10.0 (inactive)
welcome, v0.35.1 (inactive)
whitespace, v0.35.0 (inactive)
wrap-guide, v0.39.0 (inactive)
language-c, v0.54.0 (inactive)
language-clojure, v0.22.1 (inactive)
language-coffee-script, v0.48.1 (inactive)
language-csharp, v0.13.0 (inactive)
language-css, v0.40.1 (inactive)
language-gfm, v0.88.0 (inactive)
language-git, v0.15.0 (inactive)
language-go, v0.43.0 (inactive)
language-html, v0.47.1 (inactive)
language-hyperlink, v0.16.1 (inactive)
language-java, v0.24.0 (inactive)
language-javascript, v0.122.0 (inactive)
language-json, v0.18.3 (inactive)
language-less, v0.29.6 (inactive)
language-make, v0.22.2 (inactive)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.37.0 (inactive)
language-php, v0.37.3 (inactive)
language-property-list, v0.8.0 (inactive)
language-python, v0.45.1 (inactive)
language-ruby, v0.70.2 (inactive)
language-ruby-on-rails, v0.25.1 (inactive)
language-sass, v0.57.0 (inactive)
language-shellscript, v0.23.0 (inactive)
language-source, v0.9.0 (inactive)
language-sql, v0.25.0 (inactive)
language-text, v0.7.1 (inactive)
language-todo, v0.29.1 (inactive)
language-toml, v0.18.1 (inactive)
language-xml, v0.34.12 (inactive)
language-yaml, v0.27.1 (inactive)

# Dev
No dev packages
```

**Comment by iamstarkov** [comment]
@Arcanemagus my report with stacktrace:

```
1. open create-react-app project
2. atom .

**Atom**: 1.14.3 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [linter-eslint](https://github.com/AtomLinter/linter-eslint) package 8.1.2


### Stack Trace

Failed to activate the linter-eslint package

```
At Cannot find module 'process-communication'

Error: Cannot find module 'process-communication'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/linter-eslint/lib/helpers.js:176:29)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/linter-eslint/lib/main.js:10:16)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:207:16)
    at /app.asar/src/package.js:190:32
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at /app.asar/src/package.js:183:26
    at Package.module.exports.Package.activate (/app.asar/src/package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:550:34)
    at /app.asar/src/package-manager.js:531:29
    at Config.module.exports.Config.transactAsync (/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/app.asar/src/package-manager.js:526:19)
    at PackageManager.module.exports.PackageManager.activate (/app.asar/src/package-manager.js:508:46)
    at /app.asar/src/atom-environment.js:814:28
```

### Commands

```
```

### Non-Core Packages

```
advanced-open-file 0.16.5 
autocomplete-modules 1.6.7 
autoupdate-packages 1.3.1 
docblockr 0.9.1 
double-tag 0.4.0 
editorconfig undefined 
linter 1.11.23 
linter-eslint 8.1.2 
react 0.16.2 
```


```

**Comment by Arcanemagus** [comment]
@iamstarkov Please try re-installing the package, it looks like you have been hit by the APM bug where it failed to install all the dependencies.
