### ISSUE TITLE
Error: Cannot read config file: /home/asa/repos/id0-rsa.pub/.eslintrc Error: ENOENT: no such file or directory, open '/home/asa/repos/id0-rsa.pub/.eslintrc'

### ISSUE THREAD

**Issue by AsaAyers** [AtomLinter/linter-eslint#346]
```
Error: Cannot read config file: /home/asa/repos/id0-rsa.pub/.eslintrc
Error: ENOENT: no such file or directory, open '/home/asa/repos/id0-rsa.pub/.eslintrc'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:384:29)
    at readFile (/home/asa/repos/id0-rsa.pub/node_modules/eslint/lib/config/config-file.js:43:15)
    at loadLegacyConfigFile (/home/asa/repos/id0-rsa.pub/node_modules/eslint/lib/config/config-file.js:114:44)
    at loadConfigFile (/home/asa/repos/id0-rsa.pub/node_modules/eslint/lib/config/config-file.js:209:26)
    at Object.load (/home/asa/repos/id0-rsa.pub/node_modules/eslint/lib/config/config-file.js:385:18)
    at loadConfig (/home/asa/repos/id0-rsa.pub/node_modules/eslint/lib/config.js:74:33)
```

I get this error whenever a `.eslintrc` doesn't exist.

**Comment by steelbrain** [comment]
@AsaAyers If I had to guess, your globally installed `eslint` is out of date. Can you try updating it?

**Comment by AsaAyers** [comment]
I don't use a globally installed `eslint`

**Comment by steelbrain** [comment]
@AsaAyers then you should update the one bundled in project

**Comment by AsaAyers** [comment]
ok, I found the problem. 

`linter-eslint` loads the version of `eslint` for your project, but it isn't actually verifying the version is compatible. I have a work project on 1.8. If 1.8 isn't acceptable to `linter-eslint` it should provide a warning and use the built in version.

The second problem is that this version is shared across all Atom instances. This is clearly wrong. Steps to reproduce:

1. Open an atom window with a project that uses eslint@1.8.0
2. Open a new atom window with a project that doesn't have a `.eslintrc`

Your 2nd project will end up using the 1st project's `1.8.0`, which causes this error. Now even if you fix it so that it verifies the version number, it still needs to use make the decision on whether to use the local eslint or the packaged eslint for each window.

So Two things should happen:

1. Reject incompatible eslints
2. Every window needs its own worker with its own eslint.

**Comment by Arcanemagus** [comment]
The only requirement should be eslint `^1.0.0`, if we need higher we need to update the check.

For projects that don't have their own local eslint we should default to the built in one, which is a bug currently.

**Comment by steelbrain** [comment]
Fixed by https://github.com/AtomLinter/linter-eslint/pull/367
