### ISSUE TITLE
Error: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by wsmd** [AtomLinter/linter-eslint#356]
```
TypeError: Cannot read property 'replace' of undefined
    at resolveEnv (/Users/waseem/.atom/packages/linter-eslint/node_modules/resolve-env/index.js:4:15)
    at /Users/waseem/.atom/packages/linter-eslint/lib/worker.js:73:29
    at /Users/waseem/.atom/packages/linter-eslint/lib/worker.js:49:18
    at /Users/waseem/.atom/packages/linter-eslint/node_modules/childprocess-promise/node_modules/sb-communication/node_modules/zm-event-kit/dist/Emitter.js:58:16
    at Array.forEach (native)
    at Communication.emit (/Users/waseem/.atom/packages/linter-eslint/node_modules/childprocess-promise/node_modules/sb-communication/node_modules/zm-event-kit/dist/Emitter.js:57:43)
    at Communication.gotMessage (/Users/waseem/.atom/packages/linter-eslint/node_modules/childprocess-promise/node_modules/sb-communication/dist/main.js:33:16)
    at process.<anonymous> (/Users/waseem/.atom/packages/linter-eslint/node_modules/childprocess-promise/dist/main.js:29:27)
    at emitTwo (events.js:87:13)
    at process.emit (events.js:172:7)
```

This error occurs when I don't have an `.eslintrc` file in my project (is it required?). I tried using both of the  eslint that ships with this package and a global installation (both are currently on @1.10.3).

**Comment by IanVS** [comment]
Thanks for the report.  What version of `linter-eslint` are you using?

**Comment by wsmd** [comment]
@IanVS I'm using:

- Atom@1.2.0
- linter@1.11.3
- linter-eslint@5.2.5

**Comment by Arcanemagus** [comment]
Your Atom is out of date, do you still see this on the latest version?

**Comment by wsmd** [comment]
@Arcanemagus I just updated Atom to version 1.2.4 and I'm still getting the error.

**Comment by paperbd** [comment]
I'm also getting this error, and I have an .eslintrc file located in my home dir (`~/.eslintrc`) which I have specified in the "ESLint Rules Dir" setting. Specifying the exact location, without the tilde (~) also doesn't seem to work.

I just upgraded to 1.2.4 also and still have the error.

**Comment by Arcanemagus** [comment]
v5.2.6 should fix this for you, or at least point us further in the direction of what is really going on. Please let us know how it works!

**Comment by wsmd** [comment]
@SpainTrain Thanks for fixing this really quick! I can confirm that the issue is gone now :+1: /cc @Arcanemagus

**Comment by paperbd** [comment]
Same here, thanks for the quick fix! Issue is gone. :)
