### ISSUE TITLE
Cannot find module `sb-communication`

### ISSUE THREAD

**Issue by jasonkuhrt** [AtomLinter/linter-eslint#361]
I am getting a Failed to load linter-eslint package but not for the same reasons as #121.

This suddenly started happening yesterday probably after a package update but I'm not certain.

The error dump is:

**Atom Version**: 1.2.4
**System**: Mac OS X 10.11.1
**Thrown From**: [linter-eslint](https://github.com/AtomLinter/linter-eslint) package, v5.2.6

### Stack Trace

Failed to load the linter-eslint package

```
At Cannot find module 'sb-communication'

Error: Cannot find module 'sb-communication'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/jasonkuhrt/.atom/packages/linter-eslint/node_modules/childprocess-promise/dist/main.js:9:21)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "mocha-test-runner",
      "Clean",
      "haskell-ghc-mod"
    ],
    "themes": [
      "nucleus-dark-ui",
      "atom-dark-fusion-syntax"
    ]
  },
  "linter-eslint": {
    "useGlobalEslint": true,
    "globalNodePath": "/usr/local",
    "disableWhenNoEslintrcFileInPath": false
  }
}
```

### Installed Packages

```coffee
# User
asciidoc-preview, v0.6.0
atom-dark-fusion-syntax, v1.1.0
atomatigit, v1.5.5
autosave, v0.23.0
color-picker, v2.0.14
ide-haskell-cabal, v1.0.0
language-asciidoc, v0.12.0
language-diff, v0.4.0
language-docker, v1.1.6
language-elm, v1.3.0
language-haskell, v1.5.1
language-jade, v0.6.2
language-protobuf, v0.5.0
language-purescript, v0.6.0
language-terraform, v0.6.0
linter, v1.11.3
linter-coffeelint, v1.1.2
linter-eslint, v5.2.6
linter-flow, v4.0.1
linter-hlint, v0.4.2
nucleus-dark-ui, v0.6.14
project-manager, v2.6.5
vim-mode, v0.63.0

# Dev
No dev packages
```

**Comment by steelbrain** [comment]
If I had to guess, it's a one-time upgrade issue. Restart atom to fix it, if that doesn't fix it for you, this will
```
cd ~/.atom/packages/linter-eslint
apm install
```

**Comment by jasonkuhrt** [comment]
> Restart atom to fix it

Did not seem to work for me.

> cd ~/.atom/packages/linter-eslint
apm install

Also did not seem to work for me (no affect on the reported error):

```
❯ cd ~/.atom/packages/linter-eslint

~/.atom/packages/linter-eslint
❯ apm install
Installing modules ✓
```

**Comment by steelbrain** [comment]
Lets try some old school fixes
```
apm uninstall linter-eslint
apm install linter-eslint
```

**Comment by jasonkuhrt** [comment]
@steelbrain Old School solved all the things. Thank-you!

**Comment by jasonkuhrt** [comment]
As to _how_ I got myself into this state, I do not know. I did nothing out of the ordinary. Opening projects, editing files... etc.

**Comment by Arcanemagus** [comment]
Atom occasionally just completely fails to install a dependency and never notifies the user, so issues like this just crop up. I think it's due to their old version of `npm` they wrap with `apm`, but I don't really know the reason.
