### ISSUE TITLE
Error: EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by Jiia** [AtomLinter/linter-eslint#388]
Lately I've been unable to use eslint on my Windows machine because of a weird error I get. I'm using global eslint installation and a global eslintrc config file located in the eslint package directory. But no matter where I put the eslintrc file, I always get the following error:

	Error: Cannot read config file: C:\Users\User.atom\packages\linter-eslint Error: EISDIR: illegal operation on a directory, read

	Error: Cannot read config file: C:\Users\User\.atom\packages\linter-eslint
	Error: EISDIR: illegal operation on a directory, read
	    at Error (native)
	    at Object.fs.readSync (fs.js:603:19)
	    at Object.fs.readFileSync (fs.js:438:24)
	    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:385:29)
	    at readFile (C:\Users\User\.atom\packages\linter-eslint\node_modules\eslint\lib\config\config-file.js:43:15)
	    at loadLegacyConfigFile (C:\Users\User\.atom\packages\linter-eslint\node_modules\eslint\lib\config\config-file.js:114:44)
	    at loadConfigFile (C:\Users\User\.atom\packages\linter-eslint\node_modules\eslint\lib\config\config-file.js:209:26)
	    at Object.load (C:\Users\User\.atom\packages\linter-eslint\node_modules\eslint\lib\config\config-file.js:385:18)
	    at loadConfig (C:\Users\User\.atom\packages\linter-eslint\node_modules\eslint\lib\config.js:74:33)
	    at new Config (C:\Users\User\.atom\packages\linter-eslint\node_modules\eslint\lib\config.js:241:38)

I'm not sure if this is important but on the first line of that error message the directory path is wrong. There's a / missing between User and .atom folders.

Eslint used to work fine before some update. After that I've uninstalled eslint multiple times and removed all editor-* files from .atom/storage.

**Comment by steelbrain** [comment]
Can you please post your global ESLint version as well as linter-eslint and Atom's?

**Comment by Arcanemagus** [comment]
Can you also post the `linter-eslint` section of your config file? For some reason the local (to the package) `eslint` is trying to load a configuration at the location of the package folder... every part of which is wrong if you are trying to use a global `eslint` installation :stuck_out_tongue:.

**Comment by steelbrain** [comment]
Fixed by https://github.com/AtomLinter/linter-eslint/pull/367
