### ISSUE TITLE
[Linter-ESLint] Worker died unexpectedly, es5-helpers.js `Unexpected token ,`

### ISSUE THREAD

**Issue by smedegaard** [AtomLinter/linter-eslint#392]
After updating to version 5.2.7 I'm getting spammed with the message `[Linter-ESLint] Worker died unexpectedly`. 

The console spawns a ton of this, so it's the es5-helper that is the culprit: 

```
ESLint Worker Info Object {stdout: "", stderr: "/home/anders/.atom/packages/linter-eslint/lib/es5-…Object.Module._extensions..js (module.js:470:10)"}stderr: "/home/anders/.atom/packages/linter-eslint/lib/es5-helpers.js:76
  findEslintDir,
SyntaxError: Unexpected token ,
   at exports.runInThisContext (vm.js:53:16)
   at Module._compile (module.js:435:25)
   at Object.Module._extensions..js (module.js:470:10)
   at Module.load (module.js:347:32)
   at Function.Module._load (module.js:302:12)
   at Module.require (module.js:357:17)
   at require (module.js:376:17)
   at Object.<anonymous> (/home/anders/.atom/packages/linter-eslint/lib/worker.js:9:17)
   at Module._compile (module.js:452:26)
   at Object.Module._extensions..js (module.js:470:10)
   "stdout: ""__proto__: Object__defineGetter__: function __defineGetter__() { [native code] }__defineSetter__: function __defineSetter__() { [native code] }__lookupGetter__: function __lookupGetter__() { [native code] }__lookupSetter__: function __lookupSetter__() { [native code] }constructor: function Object() { [native code] }hasOwnProperty: function hasOwnProperty() { [native code] }isPrototypeOf: function isPrototypeOf() { [native code] }propertyIsEnumerable: function propertyIsEnumerable() { [native code] }toLocaleString: function toLocaleString() { [native code] }toString: function toString() { [native code] }valueOf: function valueOf() { [native code] }get __proto__: function __proto__() { [native code] }set __proto__: function __proto__() { [native code] }
```

**Comment by steelbrain** [comment]
If I had to guess, either your Atom or `linter-eslint` is out of date. Please let me know if it's not the case

**Comment by smedegaard** [comment]
updating atom to 1.3.2 solved it, thanks.
