### ISSUE TITLE
Uncaught Error when declaring an ES6 import statement

### ISSUE THREAD

**Issue by cwaring** [AtomLinter/linter-eslint#40]
This error throws on every change when an ES6 import statement is in the document.

```js
import thing from 'lib';
```
I have a global .eslintrc in my home dir using babel-eslint with the following config. Any idea how to fix this?

```YAML
 # eslint config
parser: babel-eslint
env:
  browser: true
  node: true
  jquery: true
  meteor: true
globals:
  meteor: true
  React: true
rules:
  strict: 0
  no-undef: 0
  no-use-before-define: 0
  no-unused-vars: 0
  yoda: 0
  quotes: [0, 'single']
  semi: 0
  curly: 0
  eol-last: 0
  max-len: [1, 80]
  space-before-blocks: ['always']
  no-underscore-dangle: 0
```

**Atom Version**: 0.186.0
**System**: Mac OS X 10.10.2
**Thrown From**: [linter-eslint](https://github.com/AtomLinter/linter-eslint) package, v0.4.1

### Stack Trace

Uncaught Error

```
At /Users/cw/.atom/packages/linter-eslint/node_modules/eslint/node_modules/escope/escope.js:73

Error
  at assert (/Users/cw/.atom/packages/linter-eslint/node_modules/eslint/node_modules/escope/escope.js:73:19)
  at Referencer.extend.ImportDeclaration (/Users/cw/.atom/packages/linter-eslint/node_modules/eslint/node_modules/escope/escope.js:1363:13)
  at Referencer.Visitor.visit (/Users/cw/.atom/packages/linter-eslint/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:109:34)
  at Referencer.Visitor.visitChildren (/Users/cw/.atom/packages/linter-eslint/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:88:38)
  at Referencer.extend.Program (/Users/cw/.atom/packages/linter-eslint/node_modules/eslint/node_modules/escope/escope.js:1216:18)
  at Referencer.Visitor.visit (/Users/cw/.atom/packages/linter-eslint/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:109:34)
  at Object.analyze (/Users/cw/.atom/packages/linter-eslint/node_modules/eslint/node_modules/escope/escope.js:1407:20)
  at EventEmitter.module.exports.api.verify (/Users/cw/.atom/packages/linter-eslint/node_modules/eslint/lib/eslint.js:623:35)
  at LinterESLint.lintFile (/Users/cw/.atom/packages/linter-eslint/lib/linter-eslint.coffee:69:21)
  at /Users/cw/.atom/packages/linter/lib/linter-view.coffee:158:18
  at Array.forEach (native)
  at /Users/cw/.atom/packages/linter/lib/linter-view.coffee:157:18
  at FSReqWrap.oncomplete (fs.js:100:15)

```

### Commands

```
     -0:38.7 core:backspace (input.hidden-input)
     -0:38.2 core:confirm (input.hidden-input)
     -0:35.5 core:save (input.hidden-input)
     -0:30.4 core:backspace (input.hidden-input)
     -0:28.9 core:save (input.hidden-input)
     -0:23.8 core:backspace (input.hidden-input)
     -0:14.9 editor:delete-to-beginning-of-word (input.hidden-input)
  8x -0:10.8 core:backspace (input.hidden-input)
     -0:08.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -0:07.5 emmet:insert-formatted-line-break-only (input.hidden-input)
     -0:07.5 docblockr:parse-enter (input.hidden-input)
     -0:07.5 editor:newline (input.hidden-input)
     -0:01.7 emmet:insert-formatted-line-break-only (input.hidden-input)
     -0:01.7 docblockr:parse-enter (input.hidden-input)
     -0:01.7 editor:newline (input.hidden-input)
     -0:00.9 core:backspace (input.hidden-input)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "oceanic-next"
    ],
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "Thumbs.db",
      ".meteor"
    ],
    "disabledPackages": [
      "minimap",
      "welcome",
      "markdown-scroll-sync",
      "markdown-format"
    ]
  },
  "linter-eslint": {}
}
```

### Installed Packages

```coffee
# User
atom-terminal, v0.7.0
autocomplete-plus, v2.4.1
autocomplete-snippets, v1.0.1
docblockr, v0.6.3
emmet, v2.3.4
fancy-new-file, v0.7.0
file-types, v0.3.0
git-control, v0.1.8
language-spacebars, v0.2.2
linter, v0.12.0
linter-csslint, v0.0.11
linter-eslint, v0.4.1
linter-jsonlint, v0.1.2
meteor-api, v2.12.0
oceanic-next, v0.1.1
react, v0.9.10
terminal-panel, v1.9.2
underscorejs-snippets, v0.2.2
vim-mode, v0.36.0
vim-surround, v0.4.2

# Dev
No dev packages
```

**Comment by cwaring** [comment]
Looks like ba535c64ffb fixes this issue.

**Comment by jfaissolle** [comment]
Thanks. I'm closing it.
