### ISSUE TITLE
Error: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by isuttell** [AtomLinter/linter-eslint#400]
Every time I try to run linter-eslint in Atom I get the following error. I'm running the latest version of eslint and I've tried both the most up to date version of Atom and the Atom Beta but it hasn't fixed it yet. Eslint runs run from the console. So, I know it's not just an eslint error. Any thoughts on how to fix it?

```
RangeError: Maximum call stack size exceeded
    at keys (native)
    at Referencer.Visitor.visitChildren (/usr/local/lib/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:78:24)
    at Referencer.Visitor.visit (/usr/local/lib/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:112:14)
    at Referencer.Visitor.visitChildren (/usr/local/lib/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:93:26)
    at Referencer.Visitor.visit (/usr/local/lib/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:112:14)
    at Referencer.Visitor.visitChildren (/usr/local/lib/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:88:38)
    at Referencer.Visitor.visit (/usr/local/lib/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:112:14)
    at Referencer.Visitor.visitChildren (/usr/local/lib/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:93:26)
    at Referencer.Visitor.visit (/usr/local/lib/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:112:14)
    at Referencer.Visitor.visitChildren (/usr/local/lib/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:88:38)
```

**Comment by Arcanemagus** [comment]
Does it work when you use a stable version of `eslint`? The stack trace you posted shows a cycle in the `esrecurse` module... which is a dependency of `eslint`.

**Comment by isuttell** [comment]
I'm using v1.10.3 of eslint that appears to be the more recent stable version.

**Comment by Arcanemagus** [comment]
Hmm, that's the same version I'm using in all projects... what operating system are you on?

**Comment by isuttell** [comment]
I'm on OSX 10.11.2. If I run eslint directly it runs as expected. It's just inside Atom that the error occurs.

**Comment by Arcanemagus** [comment]
If you go to `~/.atom/packages/linter-eslint` and run `apm test` do all the specs pass for you?

**Comment by isuttell** [comment]
Nope. I get the following error
```
Error: Cannot find module 'shelljs'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/Isaac/.atom/packages/linter-eslint/spec/es5-helpers-spec.js:4:20)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at requireSpecs (/Applications/Atom.app/Contents/Resources/app.asar/spec/jasmine-test-runner.js:96:9)
    at module.exports (/Applications/Atom.app/Contents/Resources/app.asar/spec/jasmine-test-runner.js:49:7)
    at module.exports (/Applications/Atom.app/Contents/Resources/app.asar/src/initialize-test-window.js:88:17)
    at setupWindow (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:86:5)
    at window.onload (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:41:9)
Tests failed
```
I did a quick `apm rm linter-eslint` following be `apm install linter-eslint` to ensure the package was installed correctly but I still get the error.

**Comment by Arcanemagus** [comment]
Ah, looks like `apm` has finally stopped installing `devDependencies` in the production environment of Atom. If you have Node installed on your machine run `npm install` to install that dependency and try `apm test` again.

**Comment by isuttell** [comment]
Ahhh. Alright, so running `npm install` and `apm test` results in all tests passed.

**Comment by Arcanemagus** [comment]
Does this error show up for all files you edit, or only ones in a specific project? Do you have the global eslint option enabled or disabled?

**Comment by isuttell** [comment]
Global eslint is enabled. I've tested two different projects and every single file it shows up every time.

**Comment by Arcanemagus** [comment]
@isuttell Do you still see this with v6.0.0?

**Comment by ambidexterich** [comment]
I had the same exact problem but I just updated linter-eslint a couple of minutes ago and I am no longer getting the 'Maximum call stack size exceeded' error. Thanks

**Comment by isuttell** [comment]
Yeah, I'm still getting the error. I tried deleting `~/.atom` and installing just `linter` and `linter-eslint` fresh and I still get the error.

**Comment by Arcanemagus** [comment]
If you disable the global `eslint` (thus using the built in one) do you still see this? What about if you install `eslint` to a project's folder?

**Comment by isuttell** [comment]
I installed eslint 2.0.0-beta.2 globally and it appears to have fixed the problem. 

As an FYI, I tried disabling the global version of eslint but that caused another error: `ImportDeclaration should appear when the mode is ES6 and in the module context.`

**Comment by Arcanemagus** [comment]
Looks like that's an issue with configuration (https://github.com/eslint/eslint/issues/4344), however the built in one is only meant to be a last resort fallback if you don't have an instance local to the project, so it sounds like for whatever file you had open there you need to add a configuration (and you really should be using per-project dependencies on `eslint` instead of global).

In any case I'm glad that the latest beta is working for you, marking this as closed.

**Comment by atombender** [comment]
Is there another workaround?

The ESLint 2.0 beta doesn't work for me — it complains about `babel-eslint` (which I've set to use as the ESLint parser) not being installed, and I don't find any fixes for that. The 2.0 branch seems to have a lot of changes that plugins etc. need to adapt to.

FWIW, this call stack issue appeared in 6.0.

We use ESLint globally installed because we have dozens of projects and maintaining per-project linter configs would be insane.

**Comment by Arcanemagus** [comment]
@atombender I'm assuming you are using a global installation? Do you have the latest beta `babel-eslint` installed globally as well?

**Comment by atombender** [comment]
Yes to both questions. Even with `babel-eslint@next`, ESLint no longer loads the plugin:

```
# eslint $(find lib -name "*.js")

/usr/local/lib/node_modules/eslint/node_modules/resolve/lib/sync.js:33
    throw new Error("Cannot find module '" + x + "' from '" + y + "'");
          ^
Error: Cannot find module 'babel-eslint' from '/Users/alex'
    at Function.module.exports [as sync] (/usr/local/lib/node_modules/eslint/node_modules/resolve/lib/sync.js:33:11)
    at Object.load (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:424:43)
    at loadConfig (/usr/local/lib/node_modules/eslint/lib/config.js:67:33)
    at getPersonalConfig (/usr/local/lib/node_modules/eslint/lib/config.js:89:22)
    at getLocalConfig (/usr/local/lib/node_modules/eslint/lib/config.js:147:85)
    at Config.getConfig (/usr/local/lib/node_modules/eslint/lib/config.js:222:22)
    at processText (/usr/local/lib/node_modules/eslint/lib/cli-engine.js:155:27)
    at processFile (/usr/local/lib/node_modules/eslint/lib/cli-engine.js:227:18)
    at executeOnFile (/usr/local/lib/node_modules/eslint/lib/cli-engine.js:602:23)
    at /usr/local/lib/node_modules/eslint/lib/cli-engine.js:629:17
```

**Comment by atombender** [comment]
Apparently ESLint doesn't know about `/usr/local/lib/node_modules`. Trying to find out where its path resolution gets `opts.moduleDirectory`...

**Comment by Arcanemagus** [comment]
Everything _should_ be under the path returned by `npm get prefix`, unless you are on one of the broken setups that doesn't follow that.

**Comment by atombender** [comment]
...answer being it doesn't. You have to specify the parser using an absolute path in `.eslintrc`:

```json
{
  "parser": "/usr/local/lib/node_modules/babel-eslint",
  ...
}
```

**Comment by atombender** [comment]
In case it wasn't clear, that seems to fix my issue — the 2.0 beta seems to work.

**Comment by Arcanemagus** [comment]
You shouldn't need to do that, just `"babel-eslint"` works perfectly fine if node is able to resolve the path to the module.

**Comment by atombender** [comment]
```
# npm get prefix
/usr/local
```

ESLint uses [this](https://github.com/substack/node-resolve/blob/master/lib/node-modules-paths.js) to  resolve the parser file name. I don't see anything about getting the prefix.

**Comment by IanVS** [comment]
There have been some changes regarding how global and local installations of ESLint resolve their dependencies.  You can see https://github.com/eslint/eslint/issues/5164 and linked issues for some discussion.

**Comment by Arcanemagus** [comment]
Wow, talk about a breaking change! Thanks for pointing that out @IanVS.
