### ISSUE TITLE
Cannot find module 'process-communication'

### ISSUE THREAD

**Issue by IanVS** [AtomLinter/linter-eslint#406]
Updated to the lastest master, and I'm now getting the following:

```
Error: Cannot find module 'process-communication'
  at Module._resolveFilename (module.js:334:15)
  at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:284:25)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (/home/ian/Local_code/eslint/linter-eslint/lib/helpers.js:16:29)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (/home/ian/Local_code/eslint/linter-eslint/lib/main.js:6:16)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app.asar/src/package.js:725:34)
  at /usr/share/atom/resources/app.asar/src/package.js:176:28
  at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:153:15)
  at Package.module.exports.Package.load (/usr/share/atom/resources/app.asar/src/package.js:167:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/usr/share/atom/resources/app.asar/src/package-manager.js:396:14)
  at PackageManager.module.exports.PackageManager.loadPackages (/usr/share/atom/resources/app.asar/src/package-manager.js:363:14)
  at Atom.module.exports.Atom.startEditorWindow (/usr/share/atom/resources/app.asar/src/atom.js:622:21)
  at Object.<anonymous> (/usr/share/atom/resources/app.asar/src/window-bootstrap.js:12:8)
  at Object.<anonymous> (/usr/share/atom/resources/app.asar/src/window-bootstrap.js:23:4)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at setupWindow (file:///usr/share/atom/resources/app.asar/static/index.js:79:25)
  at window.onload (file:///usr/share/atom/resources/app.asar/static/index.js:35:9)
```

Versions:

Atom: 1.4
Linter: 1.11.3
Linter-eslint: master
ESLint: master (2.0.0-beta.2)

**Comment by steelbrain** [comment]
@IanVS Looks like you didn't run `apm install` after `git pull`

**Comment by IanVS** [comment]
Yep, my bad. Thanks. 
On Jan 24, 2016 4:32 PM, Steel Brain <notifications@github.com> wrote:@IanVS Looks like you didn't run apm install after git pull
