### ISSUE TITLE
Error: Invalid TextEditor provided

### ISSUE THREAD

**Issue by karlbateman** [AtomLinter/linter-eslint#429]
Opening a file in Atom with the linter-eslint plugin installed gives me the following error?

```
Error: Invalid TextEditor provided
    at _validateEditor (/home/karlbateman/.atom/packages/linter-eslint/node_modules/atom-linter/lib/helpers.js:143:11)
    at Object.rangeFromLineNumber (/home/karlbateman/.atom/packages/linter-eslint/node_modules/atom-linter/lib/helpers.js:164:3)
    at /home/karlbateman/.atom/packages/linter-eslint/lib/main.js:162:35
    at Array.map (native)
    at /home/karlbateman/.atom/packages/linter-eslint/lib/main.js:155:27
```

I have the following options set on atom:
```
"linter-eslint":
    disableEslintIgnore: true
    globalNodePath: "/home/karlbateman/.nvm/versions/node/v5.3.0"
    useGlobalEslint: true
    disableFSCache: true
```

And my .eslintrc file contains the following:
```
{
    "env": {
        "browser": false,
        "node": true,
    },
    "extends": "eslint:recommended",
    "parser": "babel-eslint",
    "rules": {
      "curly": 2,
      "consistent-return": 2,
      "complexity": [2, 10],
      "max-nested-callbacks": [2, 3],
      "default-case": 2,
      "dot-location": [2, "property"],
      "dot-notation": 2,
      "guard-for-in": 2,
      "no-else-return": 2,
      "no-eval": 2,
      "no-eq-null": 2,
      "no-empty-label": 2,
      "no-extend-native": [2, {"exceptions": ["Object"]}],
      "no-invalid-this": 2,
      "no-unexpected-multiline": 2,
      "semi": [2, "always"],
      "strict": [2, "function"],
      "no-trailing-spaces": 2,
      "no-mixed-requires": [2, {"grouping": true}]
    }
}
```

I am running Atom on Debian 8.2 amd64 with Atom v1.3.2. Thanks in advance for any help :smile:

**Comment by alvinsw** [comment]
Same error happened to me!

**Comment by steelbrain** [comment]
@Arcanemagus This is coming from :stuck_out_tongue: https://github.com/AtomLinter/atom-linter/pull/102

**Comment by Arcanemagus** [comment]
First of all you should update your Atom installation :wink:
That PR should have only changed things if you are on Atom >1.4.0, anything older than that should have identical behavior...

**Comment by karlbateman** [comment]
Thanks for that :+1: will test when I get back.

**Comment by Arcanemagus** [comment]
Closing due to a lack of response. If you are still experiencing this please file a new issue.
