### ISSUE TITLE
Cannot read config file if the file is set in a separate folder

### ISSUE THREAD

**Issue by ole3021** [AtomLinter/linter-eslint#443]
I have the issue when i use the eslintrc.js config file in my project folder it works well, but when i use the same file but in a different folder i get the following error every time i open a .js file ...

Error: Cannot read config file: /Users/ole3021/workspace/node-dotfiles 
Error: EISDIR: illegal operation on a directory, read

```
Error: Cannot read config file: /Users/ole3021/workspace/node-dotfiles
Error: EISDIR: illegal operation on a directory, read
    at Error (native)
    at Object.fs.readSync (fs.js:603:19)
    at Object.fs.readFileSync (fs.js:438:24)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:385:29)
    at readFile (/Users/ole3021/.nvm/versions/node/v5.4.0/lib/node_modules/eslint/lib/config/config-file.js:66:15)
    at loadLegacyConfigFile (/Users/ole3021/.nvm/versions/node/v5.4.0/lib/node_modules/eslint/lib/config/config-file.js:137:44)
    at loadConfigFile (/Users/ole3021/.nvm/versions/node/v5.4.0/lib/node_modules/eslint/lib/config/config-file.js:218:22)
    at Object.load (/Users/ole3021/.nvm/versions/node/v5.4.0/lib/node_modules/eslint/lib/config/config-file.js:435:18)
    at loadConfig (/Users/ole3021/.nvm/versions/node/v5.4.0/lib/node_modules/eslint/lib/config.js:67:33)
    at new Config (/Users/ole3021/.nvm/versions/node/v5.4.0/lib/node_modules/eslint/lib/config.js:194:38)
```

please have a check :smiley_cat: 

Cherrs

**Comment by Arcanemagus** [comment]
Looks like you are using a global `eslint` installation, and for some reason it's trying to read `/Users/ole3021/workspace/node-dotfiles` as your configuration directly.

What do your `linter-eslint` settings look like?

**Comment by ole3021** [comment]
@Arcanemagus  Yes, i do have a global `eslint` installed, and i want to load a configuration from `~/ole3021/node-dotfiles/` for the configuration is shared with other members.

my configuration of `linter-eslint` is like this 


![image](https://cloud.githubusercontent.com/assets/2676686/13163667/e36f80ac-d6e9-11e5-8524-3f128c51a6ac.png)

**Comment by Perrishnikov** [comment]
Any word on this yet?

**Comment by IanVS** [comment]
It looks to me like `.eslintrc Path` needs to specify an absolute filename, not just a path to look in.  We should probably be smarter about testing if the path is a directory or a file.  I will have a look into it, but for now, try using a filename and let me know if that indeed solves it.

**Comment by Arcanemagus** [comment]
Marking this as closed, that option (Like all the other Path options) requires a full path to the file.
