### ISSUE TITLE
cannot find babel-eslint

### ISSUE THREAD

**Issue by devboell** [AtomLinter/linter-eslint#459]
I just updated the package (v 7.0.0 ), and I got this error:

Error: Cannot find module 'babel-eslint' from '/Users/home/.atom/packages/linter-eslint/node_modules'

I have babel-eslint installed locally to my project, and previously linter seemed to be using that.
in my .eslintrc I have : 
```
{
  "parser": "babel-eslint",
}
```

**Comment by steelbrain** [comment]
Can you please create a minimal repro and post it somewhere?

**Comment by devboell** [comment]
I reproduced it with this package.json:

```
  "name": "linter-issue",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "devboell <devboell@gmail.com>",
  "license": "ISC",
  "devDependencies": {
    "babel-core": "^6.5.2",
    "babel-eslint": "^5.0.0",
    "babel-preset-es2015": "^6.5.0"
  },
  "babel" : {
    "presets" : ["es2015"]
  },
  "eslintConfig" : {
    "parser": "babel-eslint"
  }
}

```

just create an index.js and start typing and the error appears.
Let me know if you need any other info. Thanks.

**Comment by devboell** [comment]
and this is the full error:

```
Error: Cannot find module 'babel-eslint' from '/Users/home/.atom/packages/linter-eslint/node_modules'
    at Function.module.exports [as sync] (/Users/home/.atom/packages/linter-eslint/node_modules/eslint/node_modules/resolve/lib/sync.js:33:11)
    at Object.load (/Users/home/.atom/packages/linter-eslint/node_modules/eslint/lib/config/config-file.js:453:43)
    at loadConfig (/Users/home/.atom/packages/linter-eslint/node_modules/eslint/lib/config.js:67:33)
    at new Config (/Users/home/.atom/packages/linter-eslint/node_modules/eslint/lib/config.js:192:38)
    at CLIEngine.executeOnText (/Users/home/.atom/packages/linter-eslint/node_modules/eslint/lib/cli-engine.js:665:28)
    at Object.cli.execute (/Users/home/.atom/packages/linter-eslint/node_modules/eslint/lib/cli.js:178:36)
    at lintJob (/Users/home/.atom/packages/linter-eslint/lib/worker.js:30:10)
    at /Users/home/.atom/packages/linter-eslint/lib/worker.js:66:20
    at Emitter.emit (/Users/home/.atom/packages/linter-eslint/node_modules/process-communication/node_modules/sb-event-kit/lib/emitter.js:70:19)
    at /Users/home/.atom/packages/linter-eslint/node_modules/process-communication/node_modules/sb-communication/lib/main.js:22:23

```

**Comment by devboell** [comment]
mmh, I just noticed issue #457 reported the same thing.

```
npm i eslint -D
```

seems to have solved my issue. Sorry about that.

**Comment by steelbrain** [comment]
Glad you found it

**Comment by timini** [comment]
Having this issue too

**Comment by Arcanemagus** [comment]
@timini As the possible causes of this message vary widely please file a new issue.
