### ISSUE TITLE
Error: Configuration for rule "curly" is invalid: Value "0" no schemas match.

### ISSUE THREAD

**Issue by iamale** [AtomLinter/linter-eslint#460]
Trying to use linter-eslint with this `.eslintrc` (minimal reproduction):

```json
{
  "rules": {
    "curly": [2]
  }
}

```

I get this error:

```
Error: /home/ale/dev/postcss-web-gtk/.eslintrc: Configuration for rule "curly" is invalid: Value "0" no schemas match.
Error: /home/ale/dev/postcss-web-gtk/.eslintrc:
	Configuration for rule "curly" is invalid:
	Value "0" no schemas match.
    at validateRuleOptions (/home/ale/dev/postcss-web-gtk/node_modules/eslint/lib/config/config-validator.js:102:15)
    at /home/ale/dev/postcss-web-gtk/node_modules/eslint/lib/config/config-validator.js:148:13
    at Array.forEach (native)
    at Object.validate (/home/ale/dev/postcss-web-gtk/node_modules/eslint/lib/config/config-validator.js:147:35)
    at Object.load (/home/ale/dev/postcss-web-gtk/node_modules/eslint/lib/config/config-file.js:390:19)
    at loadConfig (/home/ale/dev/postcss-web-gtk/node_modules/eslint/lib/config.js:74:33)
    at new Config (/home/ale/dev/postcss-web-gtk/node_modules/eslint/lib/config.js:241:38)
    at CLIEngine.executeOnText (/home/ale/dev/postcss-web-gtk/node_modules/eslint/lib/cli-engine.js:679:28)
    at Object.cli.execute (/home/ale/dev/postcss-web-gtk/node_modules/eslint/lib/cli.js:162:36)
    at lintJob (/home/ale/.atom/packages/linter-eslint/lib/worker.js:29:10)
```

However, if `eslint` is ran by hand, it runs normally:

```
~/dev/postcss-web-gtk $ node_modules/.bin/eslint index.js 

/home/ale/dev/postcss-web-gtk/index.js
  14:5  error  Expected { after 'for-in'        curly
  15:9  error  Expected { after 'if' condition  curly

✖ 2 problems (2 errors, 0 warnings)
```

What can be the source of the problem here?

**Comment by iamale** [comment]
Oh, updating to 7.0.0 helped. Sorry!
