### ISSUE TITLE
"AssertionError: ImportDeclaration..." thrown when opening JS files in Atom.

### ISSUE THREAD

**Issue by phyllisstein** [AtomLinter/linter-eslint#469]
Hey there! I'm seeing the following error thrown in Atom when I open JavaScript source files with the linter enabled:

```
AssertionError: ImportDeclaration should appear when the mode is ES6 and in the module context.
    at Referencer.ImportDeclaration (/Users/daniel/Repos/Submish/Hildy/node_modules/escope/lib/referencer.js:591:34)
    at Referencer.Visitor.visit (/Users/daniel/Repos/Submish/Hildy/node_modules/esrecurse/esrecurse.js:118:34)
    at Referencer.Visitor.visitChildren (/Users/daniel/Repos/Submish/Hildy/node_modules/esrecurse/esrecurse.js:97:38)
    at Referencer.Program (/Users/daniel/Repos/Submish/Hildy/node_modules/escope/lib/referencer.js:419:18)
    at Referencer.Visitor.visit (/Users/daniel/Repos/Submish/Hildy/node_modules/esrecurse/esrecurse.js:118:34)
    at Object.analyze (/Users/daniel/Repos/Submish/Hildy/node_modules/escope/lib/index.js:153:16)
    at EventEmitter.module.exports.api.verify (/Users/daniel/Repos/Submish/Hildy/node_modules/eslint/lib/eslint.js:795:35)
    at processText (/Users/daniel/Repos/Submish/Hildy/node_modules/eslint/lib/cli-engine.js:187:27)
    at CLIEngine.executeOnText (/Users/daniel/Repos/Submish/Hildy/node_modules/eslint/lib/cli-engine.js:672:26)
    at Object.cli.execute (/Users/daniel/Repos/Submish/Hildy/node_modules/eslint/lib/cli.js:178:36)
```

I think it has something to do with this package, because I can run the linter without any difficulty from Sublime Text and the command line. I first noticed the error after updating ESLint to 2.3.0 and `eslint-plugin-react` to 4.2.0, but downgrading didn't clear up the problem. I've dropped my `.eslintrc` and a sample file in [this Gist](https://gist.github.com/phyllisstein/a528c64fc88a057b22f6), in case that's useful, and I'd be grateful for any suggestions you have. Thanks in advance for your help!

**Comment by phyllisstein** [comment]
Oops, appears to be an upstream issue! Checked the Atom dev console and saw that `babel-eslint` couldn't find a dependency on `estraverse-fb`; installing it and reloading the Atom window fixed the problem. Sorry about the misleading stacktrace!

**Comment by Arcanemagus** [comment]
This is due to an interaction between `eslint@2.3.0` and `babel-eslint`, tracked here: https://github.com/eslint/eslint/issues/5476

**Comment by guidobouman** [comment]
Solution: Upgrade your `babel-eslint` to version 6+.

**Comment by ndelangen** [comment]
Fix that worked for me: 
`npm install -g estraverse-fb`

**Comment by Arcanemagus** [comment]
@ndelangen As stated before, this was a bug in the interaction between (now _very_ outdated) versions of `eslint` and `babel-eslint`, if you are still seeing this on current versions you should file an issue on the respective packages.
