### ISSUE TITLE
Uncaught TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by ro-ka** [AtomLinter/linter-eslint#47]
[Enter steps to reproduce below:]

1. Just editing some file…

**Atom Version**: 0.187.0
**System**: Mac OS X 10.10.2
**Thrown From**: [linter-eslint](https://github.com/AtomLinter/linter-eslint) package, v0.5.0

### Stack Trace

Uncaught TypeError: Cannot read property 'name' of undefined

```
At /Users/me/project/node_modules/eslint/lib/rules/no-func-assign.js:42

TypeError: Cannot read property 'name' of undefined
  at checkIfIdentifierIsFunction (/Users/me/project/node_modules/eslint/lib/rules/no-func-assign.js:42:29)
  at checkIfIdentifierIsFunction (/Users/me/project/node_modules/eslint/lib/rules/no-func-assign.js:56:20)
  at checkIfIdentifierIsFunction (/Users/me/project/node_modules/eslint/lib/rules/no-func-assign.js:56:20)
  at checkIfIdentifierIsFunction (/Users/me/project/node_modules/eslint/lib/rules/no-func-assign.js:56:20)
  at EventEmitter.AssignmentExpression (/Users/me/project/node_modules/eslint/lib/rules/no-func-assign.js:73:17)
  at EventEmitter.emit (events.js:138:20)
  at Controller.controller.traverse.enter (/Users/me/project/node_modules/eslint/lib/eslint.js:735:25)
  at Controller.__execute (/Users/me/project/node_modules/eslint/node_modules/estraverse/estraverse.js:393:31)
  at Controller.traverse (/Users/me/project/node_modules/eslint/node_modules/estraverse/estraverse.js:491:28)
  at EventEmitter.module.exports.api.verify (/Users/me/project/node_modules/eslint/lib/eslint.js:728:24)
  at LinterESLint.lintFile (/Users/me/.atom/packages/linter-eslint/lib/linter-eslint.coffee:78:21)
  at /Users/me/.atom/packages/linter/lib/linter-view.coffee:158:18
  at Array.forEach (native)
  at /Users/me/.atom/packages/linter/lib/linter-view.coffee:157:18
  at FSReqWrap.oncomplete (fs.js:100:15)

```

### Commands

```
     -1:17.8 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -1:17.8 editor:newline (atom-text-editor.editor.is-focused)
     -1:17.6 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -1:17.6 snippets:expand (atom-text-editor.editor.is-focused)
     -1:17.6 docblockr:parse-tab (atom-text-editor.editor.is-focused)
     -1:17.6 editor:indent (atom-text-editor.editor.is-focused)
     -1:17.1 core:save (atom-text-editor.editor.is-focused)
     -0:34.6 core:backspace (atom-text-editor.editor.is-focused)
     -0:33.3 core:save (atom-text-editor.editor.is-focused)
     -0:07.1 editor:toggle-line-comments (atom-text-editor.editor.is-focused)
     -0:06.6 core:save (atom-text-editor.editor.is-focused)
  2x -0:04.4 core:move-up (atom-text-editor.editor.is-focused)
     -0:03.8 core:move-down (atom-text-editor.editor.is-focused)
  7x -0:03.6 core:select-down (atom-text-editor.editor.is-focused)
  2x -0:02.1 core:backspace (atom-text-editor.editor.is-focused)
     -0:00.5 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "spacegray-eighties-dark-syntax"
    ],
    "audioBeep": false,
    "disabledPackages": [
      "language-objective-c",
      "background-tips",
      "language-c",
      "language-clojure",
      "language-coffee-script",
      "language-csharp",
      "language-perl",
      "language-python",
      "language-toml"
    ]
  },
  "linter-eslint": {
    "disableWhenNoEslintrcFileInPath": true
  }
}
```

### Installed Packages

```coffee
# User
Stylus, v0.6.2
atom-beautify, v0.23.0
autocomplete-plus, v2.6.0
autocomplete-snippets, v1.2.0
docblockr, v0.6.3
editorconfig, v0.3.3
ember-snippets, v1.0.0
file-icons, v1.5.2
language-jade, v0.3.0
linter, v0.12.0
linter-csslint, v0.0.11
linter-eslint, v0.5.0
minimap, v4.6.0
react, v0.10.1
spacegray-eighties-dark-syntax, v0.7.1

# Dev
No dev packages
```

**Comment by jfaissolle** [comment]
From the stack trace, this is most certainly an eslint bug.

**Comment by iam4x** [comment]
This should be fixed with new versions of `eslint`

https://github.com/eslint/eslint/pull/2076
https://github.com/eslint/eslint/pull/2061

Please make sure your local installation of `eslint` is up to date.
