### ISSUE TITLE
Error: Unexpected token : in .eslintrc.js

### ISSUE THREAD

**Issue by abeninskibede** [AtomLinter/linter-eslint#470]
Hello guys,

ESlint version: v2.3.0
Node: 4.1.2

No matter what I put inside my .eslintrc.js locally in my project folder I get this error:
```
Error: Unexpected token :
SyntaxError: Cannot read config file: User/.eslintrc.js
Error: Unexpected token :
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at module.exports (/Users/alexanderbeninski/.nvm/versions/node/v4.1.2/lib/node_modules/eslint/node_modules/require-uncached/index.js:14:12)
    at loadJSConfigFile (/Users/alexanderbeninski/.nvm/versions/node/v4.1.2/lib/node_modules/eslint/lib/config/config-file.js:157:16)
    at loadConfigFile (/Users/alexanderbeninski/.nvm/versions/node/v4.1.2/lib/node_modules/eslint/lib/config/config-file.js:197:22)
```
On a Macbook.

What Am I doing wrong?

Sample config file:
```
{
"extends": "defaults"
}
```

**Comment by steelbrain** [comment]
`.eslint.js` means that you should export your config, `.js` and `.json` are not the same thing. If you want to make it work you should write it like this
```
module.exports = {
  "extends": "defaults"
}
```

**Comment by abeninskibede** [comment]
Oh God! Thank you man.
