### ISSUE TITLE
Uncaught TypeError: Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by ro-ka** [AtomLinter/linter-eslint#48]
1. Editing the following file:

```
import Ember from 'ember';
import {
  moduleForComponent,
  test
} from 'ember-qunit';

moduleForComponent('colorscheme-select', 'ColorschemeSelectComponent', {
  setup: function() {
    this.container.register('view:select', Ember.Select);
  }
});
```

**Atom Version**: 0.187.0
**System**: Mac OS X 10.10.2
**Thrown From**: [linter-eslint](https://github.com/AtomLinter/linter-eslint) package, v0.5.0

### Stack Trace

Uncaught TypeError: Cannot read property 'type' of undefined

```
At /Users/me/project/node_modules/eslint/lib/rules/no-unused-vars.js:43

TypeError: Cannot read property 'type' of undefined
  at isExported (/Users/me/project/node_modules/eslint/lib/rules/no-unused-vars.js:43:27)
  at EventEmitter.Program:exit (/Users/me/project/node_modules/eslint/lib/rules/no-unused-vars.js:120:70)
  at EventEmitter.emit (events.js:138:20)
  at Controller.controller.traverse.leave (/Users/me/project/node_modules/eslint/lib/eslint.js:743:25)
  at Controller.__execute (/Users/me/project/node_modules/eslint/node_modules/estraverse/estraverse.js:393:31)
  at Controller.traverse (/Users/me/project/node_modules/eslint/node_modules/estraverse/estraverse.js:481:28)
  at EventEmitter.module.exports.api.verify (/Users/me/project/node_modules/eslint/lib/eslint.js:728:24)
  at LinterESLint.lintFile (/Users/me/.atom/packages/linter-eslint/lib/linter-eslint.coffee:78:21)
  at /Users/me/.atom/packages/linter/lib/linter-view.coffee:158:18
  at Array.forEach (native)
  at /Users/me/.atom/packages/linter/lib/linter-view.coffee:157:18
  at FSReqWrap.oncomplete (fs.js:100:15)
```

### Commands

```
     -0:47.1 editor:move-to-end-of-word (atom-text-editor.editor.mini)
     -0:46.0 core:backspace (atom-text-editor.editor.mini)
     -0:44.8 core:confirm (atom-text-editor.editor.mini)
     -0:43.8 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:43.8 core:cancel (atom-text-editor.editor.is-focused)
     -0:40.6 core:save (atom-text-editor.editor.is-focused)
  2x -0:40.1 core:close (atom-text-editor.editor.is-focused)
  4x -0:30.3 editor:move-to-beginning-of-word (atom-text-editor.editor.mini)
     -0:27.6 core:confirm (atom-text-editor.editor.mini)
  2x -0:19.3 editor:move-to-beginning-of-word (atom-text-editor.editor)
  4x -0:17.2 editor:move-to-end-of-word (atom-text-editor.editor)
  5x -0:16.0 core:move-right (atom-text-editor.editor)
  5x -0:13.7 core:move-left (atom-text-editor.editor)
     -0:12.7 core:backspace (atom-text-editor.editor)
     -0:11.6 autocomplete-plus:cancel (atom-text-editor.editor)
  3x -0:10.5 core:save (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "spacegray-eighties-dark-syntax"
    ],
    "audioBeep": false,
    "disabledPackages": [
      "language-objective-c",
      "background-tips",
      "language-c",
      "language-clojure",
      "language-coffee-script",
      "language-csharp",
      "language-perl",
      "language-python",
      "language-toml"
    ]
  },
  "linter-eslint": {
    "disableWhenNoEslintrcFileInPath": true
  }
}
```

### Installed Packages

```coffee
# User
Stylus, v0.6.2
atom-beautify, v0.23.0
autocomplete-plus, v2.6.0
autocomplete-snippets, v1.2.0
docblockr, v0.6.3
editorconfig, v0.3.3
ember-snippets, v1.0.0
file-icons, v1.5.2
language-jade, v0.3.0
linter, v0.12.0
linter-csslint, v0.0.11
linter-eslint, v0.5.0
minimap, v4.6.0
react, v0.10.1
spacegray-eighties-dark-syntax, v0.7.1

# Dev
No dev packages
```

**Comment by jfaissolle** [comment]
From the stack trace, this is most certainly an eslint bug.

**Comment by iam4x** [comment]
This was a bug from `eslint` it's already fixed, please make sure your local installation of `eslint` is up to date.

https://github.com/eslint/eslint/issues/2114

**Comment by bucaran** [comment]
Getting the same error after `npm update` in my project. Is there anything else I need to do?

**Comment by iam4x** [comment]
@bucaran update eslint

**Comment by moretti** [comment]
I have a similar problem with eslint@0.20.0, linter@0.12.1 and linter-eslint@0.5.3:
```
TypeError: Cannot read property 'type' of undefined
  at getUnusedLocals (/Users/me/project/node_modules/eslint/lib/rules/no-unused-vars.js:121:60)
  at Array.map (native)
  at getUnusedLocals (/Users/me/project/node_modules/eslint/lib/rules/no-unused-vars.js:141:58)
  at Array.map (native)
  at getUnusedLocals (/Users/me/project/node_modules/eslint/lib/rules/no-unused-vars.js:141:58)
  at Array.map (native)
  at getUnusedLocals (/Users/me/project/node_modules/eslint/lib/rules/no-unused-vars.js:141:58)
  at Array.map (native)
  at getUnusedLocals (/Users/me/project/node_modules/eslint/lib/rules/no-unused-vars.js:141:58)
  at EventEmitter.Program:exit (/Users/me/project/node_modules/eslint/lib/rules/no-unused-vars.js:147:26)
  at emitOne (events.js:82:20)
  at EventEmitter.emit (events.js:166:7)
  at Controller.controller.traverse.leave (/Users/me/project/node_modules/eslint/lib/eslint.js:734:25)
  at Controller.__execute (/Users/me/project/node_modules/eslint/node_modules/estraverse/estraverse.js:393:31)
  at Controller.traverse (/Users/me/project/node_modules/eslint/node_modules/estraverse/estraverse.js:481:28)
  at EventEmitter.module.exports.api.verify (/Users/me/project/node_modules/eslint/lib/eslint.js:719:24)
  at /Users/me/.atom/packages/linter-eslint/lib/linter-eslint.coffee:84:23
  at exports.allowUnsafeNewFunction (/Users/me/.atom/packages/linter-eslint/node_modules/loophole/lib/loophole.js:25:14)
  at LinterESLint.lintFile (/Users/me/.atom/packages/linter-eslint/lib/linter-eslint.coffee:83:5)
  at /Users/me/.atom/packages/linter/lib/linter-view.coffee:163:18
  at Array.forEach (native)
  at /Users/me/.atom/packages/linter/lib/linter-view.coffee:162:18
  at FSReqWrap.oncomplete (fs.js:77:15)
```

**Comment by bucaran** [comment]
@iam4x That was not very helpful considering I mentioned I _did_ `npm update` :wink:

**Comment by iam4x** [comment]
Sorry, I was on the rush I was at the airport.

Have you tried to update eslint into your project? `npm install eslint --save-dev` ? Should fix it :)

**Comment by moretti** [comment]
I am using eslint@0.20.0, which is the latest stable version on npm. But I'm also using several eslint plugins such as babel-eslint and eslint-plugin-react. I'll try to setup small example this weekend that can reproduce the error I'm getting.

Thanks! :smile:

**Comment by bucaran** [comment]
Nope. Still having the same problem. Bummer.

**Comment by akofman** [comment]
Hello ! 
@bucaran : Looks good with the lastest version of babel-eslint (3.1.1).
You also have eslint@0.21.0 now.

**Comment by bucaran** [comment]
Yup! I forgot to update here. Looking good to me too.
