### ISSUE TITLE
Error: Cannot find module 'shell-path' on Python files

### ISSUE THREAD

**Issue by SBoudrias** [AtomLinter/linter-eslint#488]
Each time I open or save a `.py` file in Atom, I get this error coming from linter-eslint. Not sure why eslint is called when loading Python files.

```
Error: Cannot find module 'shell-path'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at findOutPath (/Users/simonb/.atom/packages/linter-eslint/node_modules/consistent-path/lib/index.js:24:21)
    at getPath (/Users/simonb/.atom/packages/linter-eslint/node_modules/consistent-path/lib/index.js:17:16)
    at Object.exec (/Users/simonb/.atom/packages/linter-eslint/node_modules/atom-linter/lib/helpers.js:116:59)
    at Object.exec (/Users/simonb/.atom/packages/linter-eslint/node_modules/atom-linter/lib/index.js:158:18)
    at Object.provider.lint (/Users/simonb/.atom/packages/linter-flake8/lib/main.coffee:206:24)
    at promises.push.Promise.then._this.emitter.emit.linter (/Users/simonb/.atom/packages/linter/lib/linter-registry.js:63:26)
    at /Users/simonb/.atom/packages/linter/lib/linter-registry.js:62:23
    at Set.forEach (native)
    at LinterRegistry.lint (/Users/simonb/.atom/packages/linter/lib/linter-registry.js:60:18)
    at /Users/simonb/.atom/packages/linter/lib/linter.coffee:98:16
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /Users/simonb/.atom/packages/linter/lib/editor-linter.js:80:22
    at /Users/simonb/.atom/packages/linter/lib/helpers.coffee:23:18
```

**Comment by steelbrain** [comment]
See https://github.com/AtomLinter/linter-jshint/issues/236
