### ISSUE TITLE
Uncaught Error: Definition for rule 'no-param-reassign' was not found.

### ISSUE THREAD

**Issue by Hurtak** [AtomLinter/linter-eslint#49]
Code snippet which throws error

```js
    var validateInput = function(value, min, max, defaultValue) {
      value = Math.floor(value);

      if (!value) {
        value = defaultValue;
      } else if (value < min * 1) {
        value = min;
      } else if (value > max * 1) {
        value = max;
      }

      return value * 1;
    };
```

**Atom Version**: 0.188.0
**System**: Microsoft Windows 7 Home Premium 
**Thrown From**: [linter-eslint](https://github.com/AtomLinter/linter-eslint) package, v0.5.0

### Stack Trace

Uncaught Error: Definition for rule 'no-param-reassign' was not found.

```
At C:\Users\Petr\.atom\packages\linter-eslint\node_modules\eslint\lib\eslint.js:657

Error: Definition for rule 'no-param-reassign' was not found.
  at C:\Users\Petr\.atom\packages\linter-eslint\node_modules\eslint\lib\eslint.js:657:27
  at Array.forEach (native)
  at EventEmitter.module.exports.api.verify (C:\Users\Petr\.atom\packages\linter-eslint\node_modules\eslint\lib\eslint.js:630:16)
  at LinterESLint.lintFile (C:\Users\Petr\.atom\packages\linter-eslint\lib\linter-eslint.coffee:78:21)
  at C:\Users\Petr\.atom\packages\linter\lib\linter-view.coffee:158:18
  at Array.forEach (native)
  at C:\Users\Petr\.atom\packages\linter\lib\linter-view.coffee:157:18
  at FSReqWrap.oncomplete (fs.js:100:15)

```

### Commands

```
     -0:48.3 core:paste (atom-text-editor.editor)
     -0:46.1 emmet:insert-formatted-line-break-only (atom-text-editor.editor)
     -0:46.1 docblockr:parse-enter (atom-text-editor.editor)
     -0:46.1 editor:newline (atom-text-editor.editor)
     -0:40.9 core:paste (atom-text-editor.editor)
     -0:40.3 emmet:insert-formatted-line-break-only (atom-text-editor.editor)
     -0:40.3 docblockr:parse-enter (atom-text-editor.editor)
     -0:40.3 editor:newline (atom-text-editor.editor)
     -0:25.6 core:close (atom-text-editor.editor.is-focused)
     -0:23.5 emmet:insert-formatted-line-break-only (atom-text-editor.editor)
     -0:23.5 docblockr:parse-enter (atom-text-editor.editor)
     -0:23.5 editor:newline (atom-text-editor.editor)
     -0:20.7 core:move-up (atom-text-editor.editor)
     -0:20.5 core:save (atom-text-editor.editor)
     -0:11.4 core:cut (atom-text-editor.editor)
     -0:11.2 core:save (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ],
    "destroyEmptyPanes": false,
    "followSymlinks": true,
    "disabledPackages": [
      "autocomplete-snippets",
      "linter-jscs",
      "linter-jshint"
    ]
  },
  "linter-eslint": {}
}
```

### Installed Packages

```coffee
# User
atom-color-highlight, v3.0.8
autocomplete-css, v0.6.0
autocomplete-html, v0.5.0
autocomplete-paths, v1.0.2
autocomplete-plus, v2.7.0
block-travel, v1.0.2
color-picker, v1.5.0
cursor-count, v0.2.0
docblockr, v0.6.3
editorconfig, v0.3.3
emmet, v2.3.4
highlight-selected, v0.9.1
last-cursor-position, v0.7.0
linter, v0.12.0
linter-csslint, v0.0.11
linter-eslint, v0.5.0
linter-htmlhint, v0.0.10
linter-jsonlint, v0.1.2
linter-less, v0.3.1
markdown-scroll-sync, v0.3.2
monokai, v0.13.0
pretty-json, v0.3.2
save-session, v0.12.4
sync-settings, v0.2.2
tabs-to-spaces, v0.9.1

# Dev
No dev packages
```

**Comment by jfaissolle** [comment]
This is because this rule was introduced by eslint 18 which is not yet integrated in linter-eslint. As a reminder: the preferred way of working is to have you own version of eslint, plugins, babel, etc. defined in your project. This is the only way to follow the eslint evolution pace at you own rythm.

**Comment by Hurtak** [comment]
Ok, thanks for help. Anyway I don't think it should throw type errors when somebody uses unsupported rule

**Comment by iam4x** [comment]
@Hurtak Can you create another issue for it? Thank's
