### ISSUE TITLE
Uncaught Error: Definition for rule 'space-before-function-paren' was not found.

### ISSUE THREAD

**Issue by Hurtak** [AtomLinter/linter-eslint#50]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.188.0
**System**: Microsoft Windows 7 Home Premium 
**Thrown From**: [linter-eslint](https://github.com/AtomLinter/linter-eslint) package, v0.5.0

### Stack Trace

Uncaught Error: Definition for rule 'space-before-function-paren' was not found.

```
At C:\Users\Petr\.atom\packages\linter-eslint\node_modules\eslint\lib\eslint.js:657

Error: Definition for rule 'space-before-function-paren' was not found.
  at C:\Users\Petr\.atom\packages\linter-eslint\node_modules\eslint\lib\eslint.js:657:27
  at Array.forEach (native)
  at EventEmitter.module.exports.api.verify (C:\Users\Petr\.atom\packages\linter-eslint\node_modules\eslint\lib\eslint.js:630:16)
  at LinterESLint.lintFile (C:\Users\Petr\.atom\packages\linter-eslint\lib\linter-eslint.coffee:78:21)
  at C:\Users\Petr\.atom\packages\linter\lib\linter-view.coffee:158:18
  at Array.forEach (native)
  at C:\Users\Petr\.atom\packages\linter\lib\linter-view.coffee:157:18
  at FSReqWrap.oncomplete (fs.js:100:15)

```

### Commands

```
 12x -2:21.3 core:backspace (atom-text-editor.editor.mini)
     -1:12.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -1:01.2 core:select-all (atom-text-editor.editor.mini)
     -1:00.0 core:backspace (atom-text-editor.editor.mini)
  3x -0:57.9 core:move-down (atom-text-editor.editor.mini)
     -0:52.4 editor:consolidate-selections (atom-text-editor.editor.mini)
     -0:52.4 core:cancel (atom-text-editor.editor.mini)
  2x -0:51.9 core:move-down (atom-text-editor.editor.is-focused)
  5x -0:51.5 core:move-up (atom-text-editor.editor.is-focused)
     -0:50.6 core:move-down (atom-text-editor.editor.is-focused)
     -0:49.7 core:close (atom-text-editor.editor.is-focused)
     -0:48.9 core:move-down (div.settings-view.pane-item)
  2x -0:48.7 core:move-up (div.settings-view.pane-item)
     -0:03.8 core:save (atom-text-editor.editor.is-focused)
 26x -0:02.6 core:move-down (atom-text-editor.editor.is-focused)
 20x -0:01.1 core:move-up (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ],
    "destroyEmptyPanes": false,
    "followSymlinks": true,
    "disabledPackages": [
      "autocomplete-snippets",
      "welcome",
      "deprecation-cop",
      "metrics",
      "styleguide",
      "linter-jscs",
      "linter-jshint"
    ]
  },
  "linter-eslint": {}
}
```

### Installed Packages

```coffee
# User
atom-color-highlight, v3.0.8
autocomplete-css, v0.6.0
autocomplete-html, v0.5.0
autocomplete-paths, v1.0.2
autocomplete-plus, v2.7.1
block-travel, v1.0.2
color-picker, v1.5.0
cursor-count, v0.2.0
docblockr, v0.6.3
editorconfig, v0.3.3
emmet, v2.3.4
highlight-selected, v0.9.1
last-cursor-position, v0.7.0
linter, v0.12.0
linter-csslint, v0.0.11
linter-eslint, v0.5.0
linter-htmlhint, v0.0.10
linter-jsonlint, v0.1.2
linter-less, v0.3.1
markdown-scroll-sync, v0.3.2
monokai, v0.13.0
pretty-json, v0.3.2
save-session, v0.12.5
sync-settings, v0.2.2
tabs-to-spaces, v0.9.2

# Dev
No dev packages
```

**Comment by jfaissolle** [comment]
Either upgrade your project's eslint or remove it completely to use linter-eslint bundled version.
