### ISSUE TITLE
Error: Configuration for rule "accessor-pairs" is invalid

### ISSUE THREAD

**Issue by piranna** [AtomLinter/linter-eslint#500]
I've just enabled eslint in one project using `eslint --init` but linter-eslint is throwing me the next error:

```javascript
Error: /Users/piranna/github/logon/.eslintrc.json: Configuration for rule "accessor-pairs" is invalid: Severity should be one of the following: 0 = off, 1 = warning, 2 = error (you passed "error").
Error: /Users/piranna/github/logon/.eslintrc.json:
	Configuration for rule "accessor-pairs" is invalid:
	Severity should be one of the following: 0 = off, 1 = warning, 2 = error (you passed "error").
    at validateRuleOptions (/Users/piranna/.atom/packages/linter-eslint/node_modules/eslint/lib/config/config-validator.js:111:15)
    at /Users/piranna/.atom/packages/linter-eslint/node_modules/eslint/lib/config/config-validator.js:157:13
    at Array.forEach (native)
    at Object.validate (/Users/piranna/.atom/packages/linter-eslint/node_modules/eslint/lib/config/config-validator.js:156:35)
    at Object.load (/Users/piranna/.atom/packages/linter-eslint/node_modules/eslint/lib/config/config-file.js:459:19)
    at loadConfig (/Users/piranna/.atom/packages/linter-eslint/node_modules/eslint/lib/config.js:67:33)
    at new Config (/Users/piranna/.atom/packages/linter-eslint/node_modules/eslint/lib/config.js:192:38)
    at CLIEngine.executeOnText (/Users/piranna/.atom/packages/linter-eslint/node_modules/eslint/lib/cli-engine.js:665:28)
    at Object.cli.execute (/Users/piranna/.atom/packages/linter-eslint/node_modules/eslint/lib/cli.js:178:36)
    at lintJob (/Users/piranna/.atom/packages/linter-eslint/lib/worker.js:30:10)
```

Seems eslint now prefer to use strings to define the severity of the linter rules but linter-eslint can't be able to understand them and should be updated... :-/

**Comment by piranna** [comment]
Seems to be related to issue #471.

**Comment by Arcanemagus** [comment]
@piranna I'm guessing that the version of `eslint` that you used for `eslint --init` is different from the one bundled in this package.

It looks like this package is falling back to the bundled version of `eslint`, have you enabled the "Use global" option? The best option is to install `eslint` in your project itself of course to avoid the whole mess of version issues.

**Comment by Arcanemagus** [comment]
Just read the issue on the `eslint` repository, that's definitely the issue as the released version of this package bundles `eslint@2.2.0` which doesn't support that style of configuration. You will need to either enable the "Use Global" option, or wait for #485 to be released.

**Comment by piranna** [comment]
Using the `use global` option worked, but later [I've got other issues](https://github.com/AtomLinter/linter-eslint/issues/514) regarding local configs.
