### ISSUE TITLE
Uncaught Error: Cannot find module 'es5-ext/string/#/contains'

### ISSUE THREAD

**Issue by fibric** [AtomLinter/linter-eslint#51]
1. Create new project
2. Create new JavaScript file
3. Start adding some valid JS code like `var gulp = require('gulp');`
**Note** No npm package installed, because its a green field project aka 'new'

**Atom Version**: 0.189.0
**System**: Microsoft Windows 7 Enterprise 
**Thrown From**: [linter-eslint](https://github.com/AtomLinter/linter-eslint) package, v0.5.0

### Stack Trace

Uncaught Error: Cannot find module 'es5-ext/string/#/contains'

```
At module.js:330

Error: Cannot find module 'es5-ext/string/#/contains'
  at Module._resolveFilename (module.js:328:15)
  at Function.Module._resolveFilename (C:\Users\denny.trebbin\AppData\Local\atom\app-0.189.0\resources\app\src\module-cache.js:383:52)
  at Function.Module._load (module.js:270:25)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (C:\Users\denny.trebbin\.atom\packages\linter-eslint\node_modules\eslint\node_modules\escope\node_modules\es6-weak-map\node_modules\d\index.js:6:21)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (C:\Users\denny.trebbin\AppData\Local\atom\app-0.189.0\resources\app\src\babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (C:\Users\denny.trebbin\.atom\packages\linter-eslint\node_modules\eslint\node_modules\escope\node_modules\es6-weak-map\polyfill.js:6:25)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (C:\Users\denny.trebbin\AppData\Local\atom\app-0.189.0\resources\app\src\babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (C:\Users\denny.trebbin\.atom\packages\linter-eslint\node_modules\eslint\node_modules\escope\node_modules\es6-weak-map\index.js:4:13)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (C:\Users\denny.trebbin\AppData\Local\atom\app-0.189.0\resources\app\src\babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at C:\Users\denny.trebbin\.atom\packages\linter-eslint\node_modules\eslint\node_modules\escope\escope.js:67:15
  at Object.<anonymous> (C:\Users\denny.trebbin\.atom\packages\linter-eslint\node_modules\eslint\node_modules\escope\escope.js:1449:2)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (C:\Users\denny.trebbin\AppData\Local\atom\app-0.189.0\resources\app\src\babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (C:\Users\denny.trebbin\.atom\packages\linter-eslint\node_modules\eslint\lib\eslint.js:12:14)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (C:\Users\denny.trebbin\AppData\Local\atom\app-0.189.0\resources\app\src\babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (C:\Users\denny.trebbin\.atom\packages\linter-eslint\node_modules\eslint\lib\api.js:9:13)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (C:\Users\denny.trebbin\AppData\Local\atom\app-0.189.0\resources\app\src\babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at LinterESLint._requireEsLint (C:\Users\denny.trebbin\.atom\packages\linter-eslint\lib\linter-eslint.coffee:28:12)
  at LinterESLint.lintFile (C:\Users\denny.trebbin\.atom\packages\linter-eslint\lib\linter-eslint.coffee:35:30)
  at C:\Users\denny.trebbin\.atom\packages\linter\lib\linter-view.coffee:158:18
  at Array.forEach (native)
  at C:\Users\denny.trebbin\.atom\packages\linter\lib\linter-view.coffee:157:18
  at C:\Users\denny.trebbin\.atom\packages\preview-plus\node_modules\chokidar\node_modules\readdirp\node_modules\graceful-fs\graceful-fs.js:104:5
  at FSReqWrap.oncomplete (fs.js:77:15)

```

### Commands

```
     -2:37.0 editor:move-to-end-of-screen-line (atom-text-editor.editor)
     -2:36.7 core:backspace (atom-text-editor.editor)
  2x -2:36.1 core:move-up (atom-text-editor.editor)
     -2:35.3 core:move-down (atom-text-editor.editor)
     -2:32.8 core:save (atom-text-editor.editor)
 27x -2:32.4 core:move-down (atom-text-editor.editor)
 44x -2:30.7 core:move-up (atom-text-editor.editor)
 12x -2:27.0 core:move-down (atom-text-editor.editor)
     -1:42.0 settings-view:open (a.stack-toggle)
  8x -0:14.3 core:move-down (atom-text-editor.editor.is-focused)
  3x -0:09.5 core:move-up (atom-text-editor.editor.is-focused)
     -0:08.5 core:move-down (atom-text-editor.editor.is-focused)
  3x -0:07.3 core:move-left (atom-text-editor.editor.is-focused)
     -0:05.7 core:delete (atom-text-editor.editor.is-focused)
  3x -0:03.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:00.2 core:move-right (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "symbols-view",
      "linter-flow"
    ],
    "themes": [
      "newton-dark-ui",
      "newton-dark-syntax"
    ]
  },
  "linter-eslint": {
    "disableWhenNoEslintrcFileInPath": true
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.23.1
atom-color-highlight, v3.0.8
atom-ctags, v2.6.1
atom-ternjs, v0.5.8
autocomplete-bibtex, v0.5.6
autocomplete-paths, v1.0.2
autocomplete-plus, v2.7.1
editorconfig, v0.3.3
git-tab-status, v1.6.0
highlight-column, v0.4.0
highlight-line, v0.10.1
highlight-selected, v0.9.1
linter, v0.12.0
linter-coffeelint, v0.2.1
linter-csslint, v0.0.11
linter-eslint, v0.5.0
linter-jsonlint, v0.1.2
linter-stylint, v0.4.0
newton-dark-syntax, v1.1.1
newton-dark-ui, v1.0.4
preview-plus, v1.1.19
project-manager, v1.15.5
project-palette-finder, v2.4.16
react, v0.10.1
save-session, vundefined
Stylus, v0.7.0
text-manipulation, v0.4.0

# Dev
No dev packages
```

![image](https://cloud.githubusercontent.com/assets/623932/6961026/d014c0be-d927-11e4-8ae3-bfda7af57109.png)

**Comment by fibric** [comment]
this error seems to happen because `eslint` isn't installed in current project.
that seems to be a bug. what if that would be a java rhino project where eslint exists?

**Comment by jfaissolle** [comment]
This is a feature yet to be developed. But for now, nothing prevents a Java project to have a package.json with eslint etc.

**Comment by iam4x** [comment]
This should be fixed with new versions

**Comment by Dealazer** [comment]
Solution to:
Cannot find module 'es5-ext':
npm install es5-ext
