### ISSUE TITLE
TypeError: Cannot read property 'line' of undefined

### ISSUE THREAD

**Issue by Aweary** [AtomLinter/linter-eslint#516]
I get this error when I have a React component written in JSX that uses `prop={true}` instead of just `prop`. An example that throws this error:

#### example.js 

```js
import React from 'react';

export default () => {
  return (
    <div someTrueProp={true}/>
  );
};
```

This is version `7.1.3` with Atom `1.6.0`.

#### Stack trace
```js
TypeError: Cannot read property 'line' of undefined
    at EventEmitter.module.exports.api.report (/usr/local/lib/node_modules/eslint/lib/eslint.js:878:27)
    at RuleContext.report (/usr/local/lib/node_modules/eslint/lib/rule-context.js:99:16)
    at EventEmitter.JSXAttribute (/Users/brandon.dail/Development/frontend/node_modules/eslint-plugin-react/lib/rules/jsx-boolean-value.js:34:21)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
    at Controller.controller.traverse.enter (/usr/local/lib/node_modules/eslint/lib/eslint.js:815:25)
    at Controller.__execute (/usr/local/lib/node_modules/eslint/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (/usr/local/lib/node_modules/eslint/node_modules/estraverse/estraverse.js:495:28)
    at EventEmitter.module.exports.api.verify (/usr/local/lib/node_modules/eslint/lib/eslint.js:808:24)
    at processText (/usr/local/lib/node_modules/eslint/lib/cli-engine.js:199:27)
```

**Comment by Arcanemagus** [comment]
Looks like that error is coming from `eslint-plugin-react`, do you see the same issue when running from the command line?

**Comment by Arcanemagus** [comment]
Marking as closed, this was almost certainly coming from the `eslint-plugin-react` code, and there was no response.

**Comment by Aweary** [comment]
Sorry, I forgot about this. It was coming from `eslint-plugin-react`.
