### ISSUE TITLE
Unable to find shared config

### ISSUE THREAD

**Issue by richleland** [AtomLinter/linter-eslint#533]
Hi - I'm trying to troubleshoot using a shared config. My `.eslintrc` looks like this:

```
{
  "extends": "sparkpost/api"
}
```

I've got the module `eslint-config-sparkpost` installed with an `api.js` file in it. The directory structure looks like this:

```
tree node_modules/eslint-config-sparkpost -a
node_modules/eslint-config-sparkpost
├── .npmignore
├── README.md
├── api.js
├── index.js
├── package.json
└── ui.js

0 directories, 6 files
```

The error I'm seeing in Atom is:

```
Error: Cannot find module 'eslint-config-sparkpost/api' Referenced from: /Users/rleland/src/projects/integrations-api/api/.eslintrc
Error: Cannot find module 'eslint-config-sparkpost/api'
Referenced from: /Users/rleland/src/projects/integrations-api/api/.eslintrc
    at Object.ModuleResolver.resolve (/Users/rleland/.atom/packages/linter-eslint/node_modules/eslint/lib/util/module-resolver.js:74:19)
    at resolve (/Users/rleland/.atom/packages/linter-eslint/node_modules/eslint/lib/config/config-file.js:475:33)
    at load (/Users/rleland/.atom/packages/linter-eslint/node_modules/eslint/lib/config/config-file.js:492:24)
    at /Users/rleland/.atom/packages/linter-eslint/node_modules/eslint/lib/config/config-file.js:388:36
    at Array.reduceRight (native)
    at applyExtends (/Users/rleland/.atom/packages/linter-eslint/node_modules/eslint/lib/config/config-file.js:365:28)
    at Object.load (/Users/rleland/.atom/packages/linter-eslint/node_modules/eslint/lib/config/config-file.js:527:22)
    at loadConfig (/Users/rleland/.atom/packages/linter-eslint/node_modules/eslint/lib/config.js:67:33)
    at new Config (/Users/rleland/.atom/packages/linter-eslint/node_modules/eslint/lib/config.js:200:38)
    at CLIEngine.executeOnText (/Users/rleland/.atom/packages/linter-eslint/node_modules/eslint/lib/cli-engine.js:655:28)
```

I'm not sure where to start with this and could use a hand as to which direction to go in to make this work. Happy to submit a PR if it's not human/my setup-related and there is something obvious. Thanks!

**Comment by Arcanemagus** [comment]
Does this work with `eslint` from the CLI?

**Comment by richleland** [comment]
Aaaand that's a no. I didn't even think to try that and troubleshoot there - thanks I'll dig in.

**Comment by Arcanemagus** [comment]
I'm going to mark this as closed for now, if you find that `linter-eslint` is still having issues after you get `eslint` working from the CLI then feel free to either re-open this or file a new issue :wink:.

**Comment by sunorry** [comment]
I have the same question. How can i get `eslint` working from the CLI? Do i need do something? thx.
