### ISSUE TITLE
Error: Line number (8) greater than maximum line (0)

### ISSUE THREAD

**Issue by willin** [AtomLinter/linter-eslint#535]
```
Error: Line number (8) greater than maximum line (0)
Error: Line number (8) greater than maximum line (0)
    at Object.rangeFromLineNumber (/Users/willin/.atom/packages/linter-eslint/node_modules/atom-linter/lib/index.js:179:11)
    at /Users/willin/.atom/packages/linter-eslint/lib/main.js:191:33
    at Array.map (native)
    at /Users/willin/.atom/packages/linter-eslint/lib/main.js:174:27
    at process._tickCallback (node.js:392:9)
```

js source:

```
var mysql = require('mysql');
var fs = require('fs');

var connection = mysql.createConnection({
  host: 'mysql',
  user: 'root',
  password: '',
  multipleStatements: true
});

connection.connect();

var sql = fs.readFileSync('./test.sql');

connection.query(`${sql}`, (err, rows, fields) => {
  if (err) {
    throw err;
  }
});

setTimeout(() => {
  connection.query('SELECT * FROM `docker_test`.`test`', (err, rows, fields) => {
    if (err) {
      throw err;
    }
    console.log('The solution is: ', rows[0].solution);
  });

  connection.end();
}, 1000);
```

when i edit this file directly, atom crashed.

when i rename it to another file name, it can be edited ok.

**Comment by Arcanemagus** [comment]
What is the file name that supposedly crashes Atom? What is the `eslint` configuration that causes this to show up?

**Comment by willin** [comment]
`mysql.js`
`server.js`


```
"*":
  "activate-power-mode":
    particles:
      size: {}
      spawnCount: {}
      totalCount: {}
    screenShake: {}
  "atom-beautify":
    apex: {}
    arduino: {}
    c: {}
    cfml: {}
    coffeescript:
      indent_size: 2
    cpp: {}
    cs: {}
    css: {}
    d: {}
    ejs: {}
    erb: {}
    fortran: {}
    general:
      _analyticsUserId: "ea162638-166c-40b5-835b-108ef72f93f3"
      analytics: false
    gherkin: {}
    handlebars: {}
    html:
      end_with_newline: true
      indent_inner_html: true
      indent_size: 2
      max_preserve_newlines: 1
    jade: {}
    java: {}
    js:
      beautify_on_save: true
      brace_style: "collapse-preserve-inline"
      end_with_comma: true
      end_with_newline: true
      indent_size: 2
      keep_function_indentation: true
    json:
      beautify_on_save: true
      indent_size: 2
    jsx: {}
    latex: {}
    less: {}
    marko: {}
    mustache: {}
    objectivec: {}
    pawn: {}
    perl: {}
    php: {}
    python: {}
    riot: {}
    ruby: {}
    rust: {}
    sass: {}
    scss: {}
    spacebars: {}
    sql: {}
    svg: {}
    swig: {}
    tss: {}
    twig: {}
    typescript: {}
    vala: {}
    visualforce: {}
    xml: {}
    xtemplate: {}
  "autoclose-html": {}
  autosave:
    enabled: true
  core:
    disabledPackages: [
      "atom-terminal-panel"
      "symbols-view"
      "atom-beautify"
    ]
    themes: [
      "atom-material-ui"
      "atom-material-syntax"
    ]
  editor:
    fontFamily: "'Source Code Pro for Powerline'"
    invisibles: {}
    showIndentGuide: true
    softWrap: true
  "exception-reporting":
    userId: "69f2bdd3-5fcf-f92b-ecd5-461248e4bd3f"
  "file-icons":
    onChanges: true
  "highlight-selected": {}
  "js-hyperclick": {}
  linter:
    errorPanelHeight: 32
    showErrorTabLine: true
  "linter-eslint": {}
  "merge-conflicts": {}
  minimap:
    plugins:
      "git-diff": true
      "git-diffDecorationsZIndex": 0
      "highlight-selected": true
      "highlight-selectedDecorationsZIndex": 0
      pigments: true
      pigmentsDecorationsZIndex: 0
  "rest-client": {}
  "simplified-chinese-menu": {}
  "terminal-plus":
    core:
      mapTerminalsTo: "Folder"
    style:
      fontFamily: "'Source Code Pro for Powerline'"
  "todo-show":
    ignoreThesePaths: [
      "**/node_modules/"
      "**/vendor/"
      "**/bower_components/"
      "**/public/"
    ]
  "tool-bar":
    position: "Left"
  "tool-bar-config": [
    {
      icon: "document"
      iconSet: "ion"
      title: "New File"
      callback: "application:new-file"
    }
    {
      icon: "folder"
      iconSet: "ion"
      title: "Open..."
      callback: "application:open-folder"
    }
    {
      icon: "archive"
      iconSet: "ion"
      title: "Save"
      callback: "core:save"
    }
    {
      icon: "spacer"
    }
    {
      icon: "search"
      iconSet: "ion"
      title: "Find in Buffer"
      callback: "find-and-replace:show"
    }
    {
      icon: "shuffle"
      iconSet: "ion"
      title: "Replace in Buffer"
      callback: "find-and-replace:show-replace"
    }
    {
      icon: "spacer"
    }
    {
      icon: "navicon-round"
      iconSet: "ion"
      title: "Toggle Command Palette"
      callback: "command-palette:toggle"
    }
    {
      icon: "gear-a"
      iconSet: "ion"
      title: "Open Settings View"
      callback: "settings-view:open"
    }
    {
      icon: "spacer"
    }
    {
      icon: "refresh"
      iconSet: "ion"
      title: "Reload Window"
      callback: "window:reload"
    }
  ]
  welcome:
    showOnStartup: false
```

**Comment by willin** [comment]
i found that when i disabled auto-beautify plugin, it's ok
