### ISSUE TITLE
Disregard package.json, optimistically look for local eslint and plugins

### ISSUE THREAD

**Issue by buschtoens** [AtomLinter/linter-eslint#551]
Using [`ember-cli-eslint`](https://github.com/ember-cli/ember-cli-eslint) we get to enjoy automatic linting in `ember-cli`. Installing this addon - by adding it to the `package.json` of the project and running the blueprint - also installs `babel-eslint@^6.0.0-beta.6` and `eslint-config-ember@^0.3.0`, as they are listed in [`devDependencies`](https://github.com/ember-cli/ember-cli-eslint/blob/master/package.json#L27).

I would expect this addon to find this local ("nested") installation of eslint, even though it is not explicitly listed in the project's `package.json`.

**Comment by buschtoens** [comment]
```
Error: Cannot find module 'eslint-config-ember' Referenced from: /home/jan/veltro/veltro-desktop/.eslintrc
Error: Cannot find module 'eslint-config-ember'
Referenced from: /home/jan/veltro/veltro-desktop/.eslintrc
    at Object.ModuleResolver.resolve (/home/jan/.atom/packages/linter-eslint/node_modules/eslint/lib/util/module-resolver.js:77:19)
    at resolve (/home/jan/.atom/packages/linter-eslint/node_modules/eslint/lib/config/config-file.js:475:33)
    at load (/home/jan/.atom/packages/linter-eslint/node_modules/eslint/lib/config/config-file.js:492:24)
    at /home/jan/.atom/packages/linter-eslint/node_modules/eslint/lib/config/config-file.js:388:36
    at Array.reduceRight (native)
    at applyExtends (/home/jan/.atom/packages/linter-eslint/node_modules/eslint/lib/config/config-file.js:365:28)
    at Object.load (/home/jan/.atom/packages/linter-eslint/node_modules/eslint/lib/config/config-file.js:527:22)
    at loadConfig (/home/jan/.atom/packages/linter-eslint/node_modules/eslint/lib/config.js:67:33)
    at new Config (/home/jan/.atom/packages/linter-eslint/node_modules/eslint/lib/config.js:200:38)
    at CLIEngine.executeOnText (/home/jan/.atom/packages/linter-eslint/node_modules/eslint/lib/cli-engine.js:655:28)
```

**Comment by buschtoens** [comment]
I just realized that I'm stupid and that this is not how `node_modules` work. Haha, sorry for the buzz!

**Comment by IanVS** [comment]
Are you able to successfully use linter-eslint, then?

**Comment by buschtoens** [comment]
```bash
$ npm install --save-dev babel-eslint@^6.0.0-beta.6 eslint eslint-config-ember
```

Yes, after manually installing these dependencies.
