### ISSUE TITLE
Error: pluginNames.forEach is not a function

### ISSUE THREAD

**Issue by pertrai1** [AtomLinter/linter-eslint#555]
I am not sure how to solve this. I have had it happen before and I am not able to solve it after I stopped using Atom and I now have started using it again:

```
TypeError: pluginNames.forEach is not a function
    at Object.module.exports.loadAll (/Users/robsimpson/.atom/packages/linter-eslint/node_modules/eslint/lib/config/plugins.js:138:21)
    at Object.load (/Users/robsimpson/.atom/packages/linter-eslint/node_modules/eslint/lib/config/config-file.js:502:21)
    at loadConfig (/Users/robsimpson/.atom/packages/linter-eslint/node_modules/eslint/lib/config.js:67:33)
    at new Config (/Users/robsimpson/.atom/packages/linter-eslint/node_modules/eslint/lib/config.js:200:38)
    at CLIEngine.executeOnText (/Users/robsimpson/.atom/packages/linter-eslint/node_modules/eslint/lib/cli-engine.js:655:28)
    at Object.cli.execute (/Users/robsimpson/.atom/packages/linter-eslint/node_modules/eslint/lib/cli.js:180:36)
    at lintJob (/Users/robsimpson/.atom/packages/linter-eslint/lib/worker.js:30:10)
    at /Users/robsimpson/.atom/packages/linter-eslint/lib/worker.js:66:20
    at Emitter.emit (/Users/robsimpson/.atom/packages/linter-eslint/node_modules/process-communication/node_modules/sb-event-kit/lib/emitter.js:70:19)
    at /Users/robsimpson/.atom/packages/linter-eslint/node_modules/process-communication/node_modules/sb-communication/lib/main.js:22:23
```

**Comment by pertrai1** [comment]
This can be closed as I found that the project needs to have a `.eslintrc` file for this not to happen

**Comment by IanVS** [comment]
This was an error coming from ESLint that is bundled with linter-eslint.  Which means it couldn't find ESLint installed in your project.  I'd suggest installing eslint into your project directly with `npm i --save-dev eslint`.  That tends to solve many problems.

I'll close the issue, but post back if you have any further troubles.
