### ISSUE TITLE
Error: fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.

### ISSUE THREAD

**Issue by MoOx** [AtomLinter/linter-eslint#564]
```
Error: (node:1458) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
    at ChildProcess.<anonymous> (/Users/MoOx/setup/dotfiles/.atom/packages/linter-eslint/node_modules/atom-linter/node_modules/sb-exec/lib/index.js:36:20)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

This appears when I update Node to 6.x.

**Comment by Arcanemagus** [comment]
Can you file this on [exec](https://github.com/steelbrain/exec), the package that was thrown from?

**Comment by MoOx** [comment]
Done https://github.com/steelbrain/exec/issues/13

**Comment by hgwood** [comment]
It means it will break in Node 7. See https://github.com/nodejs/node/pull/5102. A dependency is probably using `graceful-fs@<4`.
