### ISSUE TITLE
Error: Failed to load plugin meteor: Cannot find module 'eslint-plugin-meteor'

### ISSUE THREAD

**Issue by at-anhuibl** [AtomLinter/linter-eslint#570]
I installed these packages regarding to[ Meteor docs](http://guide.meteor.com/code-style.html#eslint-editor), I ran these 3 command, all success:
```
apm install language-babel
apm install linter
apm install linter-eslint
```
but when I reload Atom, I got these following error:
```
Error: Failed to load plugin meteor: Cannot find module 'eslint-plugin-meteor'
    at Function.Module._resolveFilename (module.js:334:15)
    at Function.Module._load (module.js:284:25)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.module.exports.load (/home/xv/.atom/packages/linter-eslint/node_modules/eslint/lib/config/plugins.js:114:26)
    at Array.forEach (native)
    at Object.module.exports.loadAll (/home/xv/.atom/packages/linter-eslint/node_modules/eslint/lib/config/plugins.js:136:21)
    at Object.load (/home/xv/.atom/packages/linter-eslint/node_modules/eslint/lib/config/config-file.js:500:21)
    at loadConfig (/home/xv/.atom/packages/linter-eslint/node_modules/eslint/lib/config.js:64:33)
    at new Config (/home/xv/.atom/packages/linter-eslint/node_modules/eslint/lib/config.js:197:38)
```
I researched this error in Google, but I did not see any the same one. Please help.
I know that you are very busy, thanks for reading this.

**Comment by at-anhuibl** [comment]
I'm sorry, my stupid brain.
I must run `npm install eslint-plugin-meteor` first.
