### ISSUE TITLE
Uncaught Error: Unknown node type ExportDeclaration.

### ISSUE THREAD

**Issue by wolverian** [AtomLinter/linter-eslint#58]
[Enter steps to reproduce below:]

1. Open a file with an exported function:

~~~js
export function foo() {
}
~~~

**Atom Version**: 0.190.0
**System**: Mac OS X 10.10.2
**Thrown From**: [linter-eslint](https://github.com/AtomLinter/linter-eslint) package, v0.5.0

### Stack Trace

Uncaught Error: Unknown node type ExportDeclaration.

```
At /Users/iv/src/vdom-example/node_modules/eslint/node_modules/escope/node_modules/estraverse/estraverse.js:511

Error: Unknown node type ExportDeclaration.
  at Controller.traverse (/Users/iv/src/vdom-example/node_modules/eslint/node_modules/escope/node_modules/estraverse/estraverse.js:511:31)
  at Object.traverse (/Users/iv/src/vdom-example/node_modules/eslint/node_modules/escope/node_modules/estraverse/estraverse.js:703:27)
  at Object.analyze (/Users/iv/src/vdom-example/node_modules/eslint/node_modules/escope/escope.js:855:20)
  at EventEmitter.module.exports.api.verify (/Users/iv/src/vdom-example/node_modules/eslint/lib/eslint.js:601:36)
  at LinterESLint.lintFile (/Users/iv/.atom/packages/linter-eslint/lib/linter-eslint.coffee:78:21)
  at /Users/iv/.atom/packages/linter/lib/linter-view.coffee:158:18
  at Array.forEach (native)
  at /Users/iv/.atom/packages/linter/lib/linter-view.coffee:157:18
  at FSReqWrap.oncomplete (fs.js:77:15)

```

### Commands

```
     -0:25.3 vim-mode:delete (atom-text-editor.editor.vim-mode.command-mode)
     -0:25.3 vim-mode:move-to-next-word (atom-text-editor.editor.vim-mode.command-mode)
     -0:25.1 vim-mode:delete (atom-text-editor.editor.vim-mode.command-mode)
     -0:25.0 vim-mode:move-to-next-word (atom-text-editor.editor.vim-mode.command-mode)
     -0:24.7 vim-mode:move-down (atom-text-editor.editor.vim-mode.command-mode)
     -0:24.6 vim-mode:delete (atom-text-editor.editor.vim-mode.command-mode)
     -0:24.6 vim-mode:move-to-next-word (atom-text-editor.editor.vim-mode.command-mode)
     -0:24.4 vim-mode:delete (atom-text-editor.editor.vim-mode.command-mode)
     -0:24.3 vim-mode:move-to-next-word (atom-text-editor.editor.vim-mode.command-mode)
     -0:24.1 vim-mode:move-down (atom-text-editor.editor.vim-mode.command-mode)
     -0:24.0 vim-mode:delete (atom-text-editor.editor.vim-mode.command-mode)
     -0:24.0 vim-mode:move-to-next-word (atom-text-editor.editor.vim-mode.command-mode)
     -0:23.7 vim-mode:delete (atom-text-editor.editor.vim-mode.command-mode)
     -0:23.6 vim-mode:move-to-next-word (atom-text-editor.editor.vim-mode.command-mode)
     -0:23.3 vim-mode:move-down (atom-text-editor.editor.vim-mode.command-mode)
  3x -0:22.6 blur (atom-text-editor.editor.vim-mode.command-mode)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "atom-light-syntax"
    ],
    "audioBeep": false
  },
  "linter-eslint": {}
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.9.0
dash, v1.1.0
go-plus, v3.3.6
linter, v0.12.0
linter-eslint, v0.5.0
vim-mode, v0.43.0

# Dev
No dev packages
```

**Comment by wolverian** [comment]
Restarting Atom fixed this issue for me, strange. Closing.
