### ISSUE TITLE
Error: Failed to load plugin standard: Cannot find module 'eslint-plugin-standard'

### ISSUE THREAD

**Issue by KingWu** [AtomLinter/linter-eslint#586]
i get this error

```
Error: Failed to load plugin standard: Cannot find module 'eslint-plugin-standard'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.module.exports.load (/Users/dev-kingwu/.atom/packages/linter-eslint/node_modules/eslint/lib/config/plugins.js:114:26)
    at Array.forEach (native)
    at Object.module.exports.loadAll (/Users/dev-kingwu/.atom/packages/linter-eslint/node_modules/eslint/lib/config/plugins.js:136:21)
    at Object.load (/Users/dev-kingwu/.atom/packages/linter-eslint/node_modules/eslint/lib/config/config-file.js:500:21)
    at loadConfig (/Users/dev-kingwu/.atom/packages/linter-eslint/node_modules/eslint/lib/config.js:64:33)
    at new Config (/Users/dev-kingwu/.atom/packages/linter-eslint/node_modules/eslint/lib/config.js:197:38)
```

**Comment by Arcanemagus** [comment]
Do you have `eslint` and `eslint-plugin-standard` installed in your project?

**Comment by Mr-Wallet** [comment]
If I may jump in on this one: I upgraded from 6.0.0 to 7.2.2 and I started getting a similar error for `eslint-plugin-jasmine`. I've run `npm install --save eslint-plugin-jasmine` and confirmed the plugin is in `node_modules`. I do not have any eslint-related things installed globally.

**Comment by KingWu** [comment]
Yes. i found the issue. i add this

"plugins": ["eslint-plugin-standard"],
but, i does not npm install it yet.

**Comment by Arcanemagus** [comment]
@KingWu You would also need to add that to your list of dependencies. The easiest way to do that is to run:

```shell
npm install --save-dev eslint-plugin-standard
```

**Comment by KingWu** [comment]
@Arcanemagus  Work perfect

**Comment by Caspain** [comment]
npm install --save eslint
that worked for me

**Comment by cal0064** [comment]
npm install --save eslint worked for me 
Negatively - 
npm install -g --save-dev eslint-plugin-standard  - at Global did not work 
npm install -g eslint babel-eslint eslint-plugin-react eslint-plugin-import eslint-plugin-jsx-a11y eslint-plugin-flowtype - individual installation did not work .

**Comment by Arcanemagus** [comment]
@cal0064 Your first "didn't work" would only work if you had ESLint installed globally (**not** recommended). The second one _might_ work with some configuration of `linter-eslint` to enable using the global ESLint instance.

**Comment by michaelguild13** [comment]
`npm install -D eslint-plugin-import eslint-plugin-node eslint-plugin-promise eslint webpack`
and include any other dependance that npm tells you.
