### ISSUE TITLE
Error: ignoredMessages.includes is not a function

### ISSUE THREAD

**Issue by Anichale** [AtomLinter/linter-eslint#614]
Linter suddenly started throwing errors after working yesterday.

I use the following eslint-plugins:
```
    "eslint": "^2.9.0",
    "eslint-config-airbnb": "^8.0.0",
    "eslint-plugin-import": "^1.6.1",
    "eslint-plugin-jsx-a11y": "^1.0.4",
    "eslint-plugin-react": "^5.0.1",

```

Remainder of error shown in atom:
```

TypeError: ignoredMessages.includes is not a function
    at /home/alexanich/.atom/packages/linter-eslint/lib/worker.js:37:29
    at Array.filter (native)
    at lintJob (/home/alexanich/.atom/packages/linter-eslint/lib/worker.js:36:42)
    at /home/alexanich/.atom/packages/linter-eslint/lib/worker.js:69:20
    at Emitter.emit (/home/alexanich/.atom/packages/linter-eslint/node_modules/process-communication/node_modules/sb-event-kit/lib/emitter.js:70:19)
    at /home/alexanich/.atom/packages/linter-eslint/node_modules/process-communication/node_modules/sb-communication/lib/main.js:22:23
    at /home/alexanich/.atom/packages/linter-eslint/node_modules/process-communication/node_modules/sb-communication/lib/main.js:21:24
    at Emitter.emit (/home/alexanich/.atom/packages/linter-eslint/node_modules/process-communication/node_modules/sb-event-kit/lib/emitter.js:68:19)
    at Communication.parseMessage (/home/alexanich/.atom/packages/linter-eslint/node_modules/process-communication/node_modules/sb-communication/lib/main.js:63:18)
    at process.ProcessCommunication.messageCallback (/home/alexanich/.atom/packages/linter-eslint/node_modules/process-communication/lib/communication.js:35:27)

```

Here is my .eslintrc.js:
```

module.exports = {
  'env': {
    'es6': true,
    'meteor': true,
    'node': true,
    'browser': true
  },
  'extends': 'airbnb',
  'ecmaFeatures': {
      'sourceType': 'module',
      'jsx': true,
      'modules': true,
      'experimentalObjectRestSpread': true
  },
  'parser': 'babel-eslint',
  'parserOptions': {
    'sourceType': 'module'
  },
  'plugins': [
  ],
  'globals': {
    'Bert': true,
    'BlazeLayout': true,
    'Documents': true,
    'FlowRouter': true,
    'Kadira': true,
    'moment': true,
    'parseMarkdown': true,
    'Roles': true,
    'SimpleSchema': true,
    'ServiceConfiguration': true,
    'uuid': true,

    // Testing
    'describe': true,
    'it': true,
    'beforeEach': true,
    'before': true,
    'afterEach': true,
    'after': true,
    'expect': true,
    'assert': true,
    'browser': true,
    'server': true,

    // Collections
    'Handlebars': true,
    'Intercom': true
  },
  'rules': {
    'arrow-body-style': [ 0 ],
    'comma-dangle': [ 2, 'never' ],
    'computed-property-spacing': [ 2, 'always' ],
    'eqeqeq': [ 2, 'smart' ],
    'indent': [ 2, 2, { 'VariableDeclarator': 2 } ],
    'linebreak-style': [ 2, 'unix' ],
    'no-console': [ 0 ],
    'no-underscore-dangle': [ 0 ],
    'no-unneeded-ternary': [ 2 ],
    'no-underscore-dangle': [ 0 ],
    'object-curly-spacing': [ 2, 'always' ],
    'quotes': [ 2, 'single' ],
    'semi': [ 2, 'always' ],
    'space-infix-ops': [ 2 ],
    'import/no-unresolved': 'off',
    'new-cap': 'off'
  }
};

```

Here is my atom -v & apm -v:
```

1.6.0
apm  1.6.0
npm  2.13.3
node 0.10.40
python 2.7.10
git 2.5.0

```

**Comment by s7dhansh** [comment]
+1

**Comment by Arcanemagus** [comment]
Your Atom is quite old, update to the latest stable and this should be fixed. Thanks for providing that information though as that gives a lower bound on the versions that don't work (the last person never responded).

**Comment by s7dhansh** [comment]
@Arcanemagus ph thank you. my version was even older 1.5.4. Added the webupd8 repo to ensure latest atom.
