### ISSUE TITLE
Error: ignoredMessages.includes is not a function (linter-eslint@7.2.3)

### ISSUE THREAD

**Issue by logol** [AtomLinter/linter-eslint#617]
Upon atom usage I get these pop-up messages:

> TypeError: ignoredMessages.includes is not a function
    at ~/.atom/packages/linter-eslint/lib/worker.js:37:29
    at Array.filter (native)
    at lintJob (~/.atom/packages/linter-eslint/lib/worker.js:36:42)
    at ~/.atom/packages/linter-eslint/lib/worker.js:69:20
    at Emitter.emit (~/.atom/packages/linter-eslint/node_modules/process-communication/node_modules/sb-event-kit/lib/emitter.js:70:19)
    at ~/.atom/packages/linter-eslint/node_modules/process-communication/node_modules/sb-communication/lib/main.js:22:23
    at ~/.atom/packages/linter-eslint/node_modules/process-communication/node_modules/sb-communication/lib/main.js:21:24
    at Emitter.emit (~/.atom/packages/linter-eslint/node_modules/process-communication/node_modules/sb-event-kit/lib/emitter.js:68:19)
    at Communication.parseMessage (~/.atom/packages/linter-eslint/node_modules/process-communication/node_modules/sb-communication/lib/main.js:63:18)
    at process.ProcessCommunication.messageCallback (~/.atom/packages/linter-eslint/node_modules/process-communication/lib/communication.js:35:27)

linter-eslint@7.2.3
atom 1.6.0

ps: have to check - maybe I should update atom :)

**Comment by Arcanemagus** [comment]
Yes, you definitely need to update Atom, pushing out a bugfix release to up the minimum version since it seems quite a few people are having this issue.

**Comment by Arcanemagus** [comment]
v7.2.4 published with a corrected minimum Atom version 😉.
