### ISSUE TITLE
Crashes in my codebase

### ISSUE THREAD

**Issue by Globegitter** [AtomLinter/linter-eslint#62]
I am working on a [SailsJS](http://sailsjs.org/#!/) using ES6/7 syntax via babeljs. I just activated the plugin, having `babel-eslint` as my parser, and having installed `npm i eslint babel-eslint --save-dev` in the project but the plugin throws errors on a few places in my code (the ones that make atom open the red popup)

[Enter steps to reproduce below:]

1. Use babel require hook with `stage: 0` setting: https://babeljs.io/docs/usage/require/ to be able to write `async/await` syntax.
2. Write any code with it.

**Atom Version**: 0.190.0
**System**: Mac OS X 10.10.3
**Thrown From**: [linter-eslint](https://github.com/AtomLinter/linter-eslint) package, v0.5.1

### Stack Trace

Uncaught SyntaxError: server/api/controllers/CrawlController.js:31
async function findOrCreateProjectMeta(metas, type) {
      ^^^^^^^^
Unexpected token function

```
At server/api/controllers/CrawlController.js:31

server/api/controllers/CrawlController.js:31
async function findOrCreateProjectMeta(metas, type) {
      ^^^^^^^^
SyntaxError: Unexpected token function
  at exports.runInThisContext (vm.js:53:16)
  at Module._compile (module.js:435:25)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at server/node_modules/eslint/lib/load-rules.js:36:36
  at Array.forEach (native)
  at module.exports (server/node_modules/eslint/lib/load-rules.js:32:30)
  at Object.load (eslint/lib/rules.js:42:20)
  at eslint/lib/cli-engine.js:260:19
  at Array.forEach (native)
  at new CLIEngine (server/node_modules/eslint/lib/cli-engine.js:258:32)
  at LinterESLint.lintFile (/Users/markus/.atom/packages/linter-eslint/lib/linter-eslint.coffee:54:18)
  at /Users/markus/.atom/packages/linter/lib/linter-view.coffee:158:18
  at Array.forEach (native)
  at /Users/markus/.atom/packages/linter/lib/linter-view.coffee:157:18
  at FSReqWrap.oncomplete (fs.js:77:15)

```

### Commands

```
     -6:45.6 editor:consolidate-selections (atom-text-editor.editor)
     -6:45.6 core:cancel (atom-text-editor.editor)
  3x -6:29.6 core:undo (atom-text-editor.editor)
     -4:59.3 core:confirm (atom-text-editor.editor.mini)
     -0:38.0 core:backspace (atom-text-editor.editor)
     -0:36.4 emmet:insert-formatted-line-break-only (atom-text-editor.editor)
     -0:36.4 editor:newline (atom-text-editor.editor)
     -0:35.8 core:move-down (atom-text-editor.editor)
  2x -0:35.6 core:backspace (atom-text-editor.editor)
     -0:34.7 core:move-right (atom-text-editor.editor)
     -0:08.3 core:paste (atom-text-editor.editor)
     -0:07.7 core:save (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "disabledPackages": [
      "tabs",
      "tree-view",
      "language-sass"
    ],
    "excludeVcsIgnoredPaths": false
  },
  "linter-eslint": {
    "eslintRulesDir": "."
  }
}
```

### Installed Packages

```coffee
# User
Atom-Syntax-highlighting-for-Sass, v0.5.0
better-handlebars, v0.1.1
color-picker, v1.6.0
dash, v1.1.0
editor-stats, v0.17.0
emmet, v2.3.7
es-navigation, v0.1.5
indent-guide-ext, v0.1.0
language-docker, v1.1.3
language-javascript-better, v1.3.0
language-json5, v1.1.0
linter, v0.12.0
linter-eslint, v0.5.1
sublime-tabs, v0.5.3

# Dev
No dev packages
```

**Comment by Globegitter** [comment]
I am getting a second issue as well with the following error:

**Atom Version**: 0.190.0
**System**: Mac OS X 10.10.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught ReferenceError: sails is not defined

```
At server/api/blueprints/find.js:16

ReferenceError: sails is not defined
    at Object.<anonymous> (server/api/blueprints/find.js:16:26)
    at Module._compile (module.js:452:26)
    at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app/src/babel.js:162:21)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at server/node_modules/eslint/lib/load-rules.js:36:36
    at Array.forEach (native)
    at module.exports (server/node_modules/eslint/lib/load-rules.js:32:30)
```

I assume this is due to the fact that sails provides a global `sails` object that is accessed in that file. Even though I should add this to my `.eslintrc env` I think this should not throw an exception but rather show the normal error that `sails` is not defined.

**Comment by iam4x** [comment]
Hello @Globegitter,

Can you paste your `.eslintrc` ?

**Comment by Globegitter** [comment]
Yes of course: https://github.com/artificialio/sane/blob/master/.eslintrc

**Comment by iam4x** [comment]
It might be your version of `babel-eslint`, with version `^2.0.0` it's using `babel^4.0.0` and `{stage: 0}` doesn't yet exists on this version. It was the `experimental=true` option.

Try to update babel-eslint `npm i --save-dev babel-eslint@3.0.0` and your local eslint: `npm i --save-dev eslint@0.19.0`

**Comment by iam4x** [comment]
And add a `.babelrc` with your configuration:

```
{
  "stage": 0
}
```

**Comment by iam4x** [comment]
Working?
