### ISSUE TITLE
Error: EPERM: operation not permitted, write

### ISSUE THREAD

**Issue by jjdp** [AtomLinter/linter-eslint#650]
I got this error when testing out es-lint.

> 
Error: EPERM: operation not permitted, write
    at Error (native)
    at Object.fs.writeSync (fs.js:706:20)
    at SyncWriteStream.write (fs.js:2059:6)
    at Console.warn (console.js:44:16)
    at Object.module.exports.error (D:\Projects\react-study\node_modules\eslint\lib\logging.js:26:23)
    at printResults (D:\Projects\react-study\node_modules\eslint\lib\cli.js:80:13)
    at Object.cli.execute (D:\Projects\react-study\node_modules\eslint\lib\cli.js:192:17)
    at lintJob (C:\Users\Jan\.atom\packages\linter-eslint\lib\worker.js:35:10)
    at C:\Users\Jan\.atom\packages\linter-eslint\lib\worker.js:69:20
    at Emitter.emit (C:\Users\Jan\.atom\packages\linter-eslint\node_modules\process-communication\node_modules\sb-event-kit\lib\emitter.js:70:19)

I am on windows 10 64-bit
Node 4.4.7
Atom 1.8.0
linter-eslint 7.2.4

**Comment by jjdp** [comment]
turns out that the package didnt install correctly

**Comment by Arcanemagus** [comment]
Thanks for reporting back what was wrong for you ;)
