### ISSUE TITLE
Uncaught TypeError: Cannot read property 'value' of undefined

### ISSUE THREAD

**Issue by MoOx** [AtomLinter/linter-eslint#66]
[Enter steps to reproduce below:]

```
import React, {Component, PropTypes} from "react"

export default class Contributors extends Component {

  static displayName = "Contributors"

  sta <---- THIS LOOKS LIKE IT BREAK SOMETHING :)
  static propTypes = {
    pkg: PropTypes.object.isRequired,
    contributors: PropTypes.object.isRequired,
    collections: PropTypes.object.isRequired,
    file: PropTypes.object.isRequired,
    i18n: PropTypes.object.isRequired,
  }

  render() {
    const pkg = this.props.pkg
    const i18n = this.props.i18n
    const file = this.props.file

    return (
      <div>
        Contributors
      </div>
    )
  }
}
```

**Atom Version**: 0.194.0
**System**: Mac OS X 10.10.3
**Thrown From**: [linter-eslint](https://github.com/AtomLinter/linter-eslint) package, v0.5.2

### Stack Trace

Uncaught TypeError: Cannot read property 'value' of undefined

```
At /Users/MoOx/Sync/Development/putaindecode/putaindecode.fr/node_modules/eslint-plugin-react/lib/rules/prop-types.js:50

TypeError: Cannot read property 'value' of undefined
  at isPropTypesDeclaration (/Users/MoOx/Sync/Development/putaindecode/putaindecode.fr/node_modules/eslint-plugin-react/lib/rules/prop-types.js:50:55)
  at EventEmitter.ClassProperty (/Users/MoOx/Sync/Development/putaindecode/putaindecode.fr/node_modules/eslint-plugin-react/lib/rules/prop-types.js:214:12)
  at emitOne (events.js:82:20)
  at EventEmitter.emit (events.js:166:7)
  at Controller.controller.traverse.enter (/Users/MoOx/Sync/Development/putaindecode/putaindecode.fr/node_modules/eslint/lib/eslint.js:726:25)
  at Controller.__execute (/Users/MoOx/Sync/Development/putaindecode/putaindecode.fr/node_modules/eslint/node_modules/estraverse/estraverse.js:393:31)
  at Controller.traverse (/Users/MoOx/Sync/Development/putaindecode/putaindecode.fr/node_modules/eslint/node_modules/estraverse/estraverse.js:491:28)
  at EventEmitter.module.exports.api.verify (/Users/MoOx/Sync/Development/putaindecode/putaindecode.fr/node_modules/eslint/lib/eslint.js:719:24)
  at /Users/MoOx/setup/dotfiles/atom/packages/linter-eslint/lib/linter-eslint.coffee:84:23
  at exports.allowUnsafeNewFunction (/Users/MoOx/setup/dotfiles/atom/packages/linter-eslint/node_modules/loophole/lib/loophole.js:25:14)
  at LinterESLint.lintFile (/Users/MoOx/setup/dotfiles/atom/packages/linter-eslint/lib/linter-eslint.coffee:83:5)
  at /Users/MoOx/setup/dotfiles/atom/packages/linter/lib/linter-view.coffee:163:18
  at Array.forEach (native)
  at /Users/MoOx/setup/dotfiles/atom/packages/linter/lib/linter-view.coffee:162:18
  at FSReqWrap.oncomplete (fs.js:77:15)

```

### Commands

```
     -0:14.1.0 find-and-replace:select-next (atom-text-editor.editor.is-focused)
     -0:10.8.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
  4x -0:10.6.0 core:move-down (atom-text-editor.editor.is-focused)
  2x -0:09.8.0 core:move-up (atom-text-editor.editor.is-focused)
  2x -0:09.2.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
  2x -0:08.6.0 core:select-down (atom-text-editor.editor.is-focused)
     -0:07.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:07.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:04.7.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -0:04.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:04.4.0 core:move-up (atom-text-editor.editor.is-focused)
  2x -0:02.8.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -0:01.5.0 editor:select-to-end-of-line (atom-text-editor.editor.is-focused)
     -0:00.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:00.7.0 core:delete (atom-text-editor.editor.is-focused)
     -0:00.2.0 core:move-down (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "projectHome": "/Users/MoOx/Sync/Development",
    "disabledPackages": [
      "language-mustache",
      "welcome",
      "language-toml",
      "language-sass",
      "language-ruby-on-rails",
      "language-ruby",
      "language-python",
      "language-php",
      "language-perl",
      "language-objective-c",
      "language-less",
      "language-java",
      "language-hyperlink",
      "language-go",
      "language-csharp",
      "language-coffee-script",
      "language-clojure",
      "language-jsx",
      "close-tags"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.24.1
atom-color-highlight, v3.0.9
atom-semicolons, v0.1.5
auto-update-packages, v0.2.2
bezier-curve-editor, v0.6.6
color-picker, v1.7.0
docblockr, v0.6.3
editorconfig, v1.0.0
file-type-icons, v0.5.4
gist-it, v0.6.10
git-log, v0.3.0
git-projects, v1.13.0
git-tab-status, v1.7.0
language-apache, v1.3.0
linter, v0.12.1
linter-eslint, v0.5.2
linter-jsonlint, v0.1.2
live-archive, v0.1.13
project-manager, v1.15.5
react, v0.11.6
term2, v0.9.5
terminal, v0.28.0
travis-ci-status, v0.13.0
web-browser, v1.4.4
yuno-commit, v0.0.2

# Dev
No dev packages
```

**Comment by iam4x** [comment]
Hello @MoOx 

I can reproduce it but it seems more an issue of https://github.com/yannickcr/eslint-plugin-react

There's an open issue to catch errors throws from eslint and his plugin #65

**Comment by MoOx** [comment]
Ok good. Thanks.
