### ISSUE TITLE
Error: EPERM: operation not permitted, write

### ISSUE THREAD

**Issue by TheoMer** [AtomLinter/linter-eslint#706]
OS: Windows 10 Pro
Node: 6.1.0
NPM: 3.8.6
Atom: 1.10.2

So, I'm receiving the following error in my project, and am not sure how best to address it:

```
Error: EPERM: operation not permitted, write
    at Error (native)
    at Object.fs.writeSync (fs.js:706:20)
    at SyncWriteStream.write (fs.js:2064:6)
    at Console.log (console.js:39:16)
    at EventEmitter.Program (C:\Users\d0475\Documents\Projects\esteMasterApp4\node_modules\eslint-plugin-react\lib\rules\require-extension.js:103:17)
    at emitOne (events.js:95:20)
    at EventEmitter.emit (events.js:182:7)
    at NodeEventGenerator.enterNode (C:\Users\d0475\Documents\Projects\esteMasterApp4\node_modules\eslint\lib\util\node-event-generator.js:40:22)
    at CodePathAnalyzer.enterNode (C:\Users\d0475\Documents\Projects\esteMasterApp4\node_modules\eslint\lib\code-path-analysis\code-path-analyzer.js:608:23)
    at CommentEventGenerator.enterNode (C:\Users\d0475\Documents\Projects\esteMasterApp4\node_modules\eslint\lib\util\comment-event-generator.js:97:23)
```

**Comment by IanVS** [comment]
Hi, It looks like you've run into the same issue as reported in https://github.com/AtomLinter/linter-eslint/issues/579.  I'm going to close this as a duplicate, and take a look at https://github.com/AtomLinter/linter-eslint/issues/579#issuecomment-239143599 for a solution.
