### ISSUE TITLE
Uncaught SyntaxError in authentication.js

### ISSUE THREAD

**Issue by leifdalan** [AtomLinter/linter-eslint#71]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.196.0
**System**: Mac OS X 10.10.3
**Thrown From**: [linter-eslint](https://github.com/AtomLinter/linter-eslint) package, v0.5.3

### Stack Trace

Uncaught SyntaxError: /Users/leifdalan/Sites/boilerplate/services/authentication.js:1
(function (exports, require, module, __filename, __dirname) { import passport 
                                                              ^^^^^^
Unexpected reserved word

```
At /Users/leifdalan/Sites/boilerplate/services/authentication.js:1

/Users/leifdalan/Sites/boilerplate/services/authentication.js:1
(function (exports, require, module, __filename, __dirname) { import passport 
                                                              ^^^^^^
SyntaxError: Unexpected reserved word
  at exports.runInThisContext (vm.js:53:16)
  at Module._compile (module.js:435:25)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at /Users/leifdalan/Sites/boilerplate/node_modules/eslint/lib/load-rules.js:36:36
  at Array.forEach (native)
  at module.exports (/Users/leifdalan/Sites/boilerplate/node_modules/eslint/lib/load-rules.js:32:30)
  at Object.load (/Users/leifdalan/Sites/boilerplate/node_modules/eslint/lib/rules.js:42:20)
  at /Users/leifdalan/Sites/boilerplate/node_modules/eslint/lib/cli-engine.js:264:19
  at Array.forEach (native)
  at new CLIEngine (/Users/leifdalan/Sites/boilerplate/node_modules/eslint/lib/cli-engine.js:262:32)
  at LinterESLint.lintFile (/Users/leifdalan/.atom/packages/linter-eslint/lib/linter-eslint.coffee:55:18)
  at /Users/leifdalan/.atom/packages/linter/lib/linter-view.coffee:163:18
  at Array.forEach (native)
  at /Users/leifdalan/.atom/packages/linter/lib/linter-view.coffee:162:18
  at FSReqWrap.oncomplete (fs.js:77:15)

```

### Commands

```
     -2:31.9.0 editor:consolidate-selections (atom-text-editor.editor)
     -2:31.9.0 core:cancel (atom-text-editor.editor)
     -2:14.2.0 find-and-replace:show (atom-text-editor.editor)
  2x -2:12.4.0 find-and-replace:find-next (atom-text-editor.editor.mini)
     -2:00.7.0 core:move-right (atom-text-editor.editor)
     -2:00.2.0 core:backspace (atom-text-editor.editor)
     -1:41.6.0 core:move-right (atom-text-editor.editor)
 18x -1:41.4.0 core:select-left (atom-text-editor.editor)
  2x -1:38.9.0 core:backspace (atom-text-editor.editor)
     -1:24.4.0 core:save (atom-text-editor.editor)
     -1:20.1.0 editor:consolidate-selections (atom-text-editor.editor)
     -1:20.1.0 core:cancel (atom-text-editor.editor)
  3x -1:02.8.0 core:backspace (atom-text-editor.editor)
     -0:13.4.0 editor:consolidate-selections (atom-text-editor.editor)
     -0:13.4.0 core:cancel (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "themes": [
      "seti-ui",
      "base16-tomorrow-dark-theme"
    ],
    "disabledPackages": [
      "jsformat",
      "tabs",
      "ember-snippets",
      "language-javascript-jsx",
      "npm-autocomplete",
      "encoding-selector",
      "language-clojure",
      "language-coffee-script",
      "language-go",
      "tree-view"
    ]
  },
  "linter-eslint": {
    "disableWhenNoeslintrcFileInPath": false,
    "eslintRulesDir": "./"
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.23.1
atom-handlebars, v0.4.0
autocomplete-css, v0.6.0
autocomplete-plus, v2.7.1
color-picker, v1.5.0
emmet, v2.3.7
javascript-snippets, v1.0.0
language-freemarker, v0.2.0
language-jade, v0.3.0
language-javascript-better, v1.1.0
linter, v0.12.1
linter-eslint, v0.5.3
react, v0.10.1
react-snippets, v0.1.1
seti-ui, v0.6.3
styleguide, v0.44.0
sublime-tabs, v0.5.2

# Dev
No dev packages
```

**Comment by iam4x** [comment]
Should be fixed with newer versions
