### ISSUE TITLE
Uncaught TypeError: Cannot read property 'range' of undefined

### ISSUE THREAD

**Issue by barendb** [AtomLinter/linter-eslint#73]
[Enter steps to reproduce below:]

1. ... was just editing code

**Atom Version**: 0.196.0
**System**: Mac OS X 10.10.3
**Thrown From**: [linter-eslint](https://github.com/AtomLinter/linter-eslint) package, v0.5.3

### Stack Trace

Uncaught TypeError: Cannot read property 'range' of undefined

```
At /Users/barendb/.atom/packages/linter-eslint/node_modules/eslint/lib/token-store.js:90

TypeError: Cannot read property 'range' of undefined
  at EventEmitter.api.getTokenBefore (/Users/barendb/.atom/packages/linter-eslint/node_modules/eslint/lib/token-store.js:90:34)
  at RuleContext.(anonymous function) [as getTokenBefore] (/Users/barendb/.atom/packages/linter-eslint/node_modules/eslint/lib/rule-context.js:84:33)
  at EventEmitter.ExportNamedDeclaration (/Users/barendb/.atom/packages/linter-eslint/node_modules/eslint/lib/rules/space-in-brackets.js:248:33)
  at emitOne (events.js:82:20)
  at EventEmitter.emit (events.js:166:7)
  at Controller.controller.traverse.enter (/Users/barendb/.atom/packages/linter-eslint/node_modules/eslint/lib/eslint.js:726:25)
  at Controller.__execute (/Users/barendb/.atom/packages/linter-eslint/node_modules/eslint/node_modules/estraverse/estraverse.js:393:31)
  at Controller.traverse (/Users/barendb/.atom/packages/linter-eslint/node_modules/eslint/node_modules/estraverse/estraverse.js:491:28)
  at EventEmitter.module.exports.api.verify (/Users/barendb/.atom/packages/linter-eslint/node_modules/eslint/lib/eslint.js:719:24)
  at /Users/barendb/.atom/packages/linter-eslint/lib/linter-eslint.coffee:84:23
  at exports.allowUnsafeNewFunction (/Users/barendb/.atom/packages/linter-eslint/node_modules/loophole/lib/loophole.js:25:14)
  at LinterESLint.lintFile (/Users/barendb/.atom/packages/linter-eslint/lib/linter-eslint.coffee:83:5)
  at /Users/barendb/.atom/packages/linter/lib/linter-view.coffee:163:18
  at Array.forEach (native)
  at /Users/barendb/.atom/packages/linter/lib/linter-view.coffee:162:18
  at FSReqWrap.oncomplete (fs.js:77:15)

```

### Commands

```
     -1:25 editor:toggle-line-comments (atom-text-editor.editor.is-focused)
     -1:24.6.0 core:save (atom-text-editor.editor.is-focused)
     -1:15.1.0 typescript:sync (atom-text-editor.editor.is-focused)
  2x -1:12.9.0 editor:toggle-line-comments (atom-text-editor.editor.is-focused)
     -1:02.8.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:58.1.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
  4x -0:57.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:52.1.0 core:save (atom-text-editor.editor.is-focused)
     -0:37.3.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:37.3.0 core:cancel (atom-text-editor.editor.is-focused)
  2x -0:32.4.0 core:delete (atom-text-editor.editor.is-focused)
     -0:23.1.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:22.8.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:21.9.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:03.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:03.1.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "excludeVcsIgnoredPaths": false,
    "disabledPackages": [
      "linter-jshint"
    ]
  },
  "linter-eslint": {}
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
atom-beautify, v0.26.2
atom-typescript, v4.1.0
atom-yeoman, v0.2.0
autocomplete-plus, v2.12.1
editorconfig, v1.0.0
language-cshtml, v0.1.1
linter, v0.12.1
linter-eslint, v0.5.3
minimap, v4.8.0
omnisharp-atom, v0.4.9
tasks, v2.0.0

# Dev
No dev packages
```

.eshintrc config

```
{
	"ecmaFeatures": {
		"arrowFunctions":true,
		"modules": true
	},
	"env": {
    "browser": true,
		"es6": true,
  },
  "globals": {

  },
  "rules": {
    "block-scoped-var": 2,
    "brace-style": [2, "stroustrup", {"allowSingleLine": true}],
    "comma-style": [2, "last"],
    "eqeqeq": [2, "smart"],
    "guard-for-in": 2,
    "key-spacing": [2, {"beforeColon": false, "afterColon": true}],
    "no-implied-eval": 2,
    "no-mixed-spaces-and-tabs": 2,
    "no-nested-ternary": 2,
    "no-reserved-keys": 2,
    "no-trailing-spaces": 2,
    "no-undef": 2,
    "no-undefined": 2,
    "no-unused-vars": [2, {"vars": "local", "args": "none"}],
    "semi": [2, "always"],
    "space-after-keywords": [2, "always", {"checkFunctionKeyword": true}],
    "space-before-blocks": [2, "always"],
    "space-in-brackets": [2, "never"],
    "space-in-parens": [2, "never"],
    "spaced-line-comment": [2, "always"],
    "strict": 2,

    "max-nested-callbacks": [1, 3],

    "camelcase": 0,
    "consistent-return": 0,
    "dot-notation": 0,
    "new-cap": 0,
    "no-alert": 0,
    "no-new": 0,
    "no-shadow": 0,
    "no-underscore-dangle": 0,
    "no-use-before-define": 0,
    "quotes": 0
  }
}
```

**Comment by chrisvariety** [comment]
Seems easy to reproduce if you close a tab with cmd+w before eslint finishes linting the file. Just open a bunch of files and close them in rapid succession.

**Comment by barendb** [comment]
In my case once it entered this error state, it was stuck, even after opening and closing Atom the error kept coming back.

**Comment by mehcode** [comment]
If I roll back eslint manually to 0.19 it fixes it for me. Perhaps opening an issue over at eslint might help?

**Comment by barendb** [comment]
:arrow_up: Yup that is what I did in the end to resolve it :smile:

**Comment by iam4x** [comment]
Will be fixed with next version of eslint https://github.com/eslint/eslint/pull/2396
