### ISSUE TITLE
Uncaught Error: Definition for rule 'react/jsx-uses-react' was not found.

### ISSUE THREAD

**Issue by eXon** [AtomLinter/linter-eslint#74]
I'm trying to use the react plugin and it throws this error. eslint and eslint-plugin-react are installed in my project folder. I absolutely need it because I have wrong unused var otherwise. Here is the content of my file to reproduce:

```json
{
  "rules": {
    "eqeqeq": 2,
    "curly": 2,
    "quotes": "single",
    "strict": 0,
    "new-cap": false,
    "no-underscore-dangle": false,
    "eol-last": false,

    "react/display-name": 1,
    "react/jsx-boolean-value": 1,
    "react/jsx-quotes": 1,
    "react/jsx-no-undef": 1,
    "react/jsx-sort-props": 1,
    "react/jsx-sort-prop-types": 1,
    "react/jsx-uses-react": 1,
    "react/jsx-uses-vars": 1,
    "react/no-did-mount-set-state": 1,
    "react/no-did-update-set-state": 1,
    "react/no-multi-comp": 1,
    "react/no-unknown-property": 1,
    "react/prop-types": 1,
    "react/react-in-jsx-scope": 1,
    "react/self-closing-comp": 1,
    "react/wrap-multilines": 1
  },
  "env": {
    "node": true,
    "browser": true,
    "es6": true
  },
  "ecmaFeatures": {
    "modules": true,
    "jsx": true
  },
  "plugins": [
    "react"
  ]
}
```

**Atom Version**: 0.198.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [linter-eslint](https://github.com/AtomLinter/linter-eslint) package, v0.5.4

### Stack Trace

Uncaught Error: Definition for rule 'react/jsx-uses-react' was not found.

```
At C:\octopus\egg\frontend\node_modules\eslint\lib\eslint.js:648

Error: Definition for rule 'react/jsx-uses-react' was not found.
  at C:\octopus\egg\frontend\node_modules\eslint\lib\eslint.js:648:27
  at Array.forEach (native)
  at EventEmitter.module.exports.api.verify (C:\octopus\egg\frontend\node_modules\eslint\lib\eslint.js:621:16)
  at C:\Users\Admin\.atom\packages\linter-eslint\lib\linter-eslint.coffee:84:23
  at exports.allowUnsafeNewFunction (C:\Users\Admin\.atom\packages\linter-eslint\node_modules\loophole\lib\loophole.js:25:14)
  at LinterESLint.lintFile (C:\Users\Admin\.atom\packages\linter-eslint\lib\linter-eslint.coffee:83:5)
  at C:\Users\Admin\.atom\packages\linter\lib\linter-view.coffee:163:18
  at Array.forEach (native)
  at C:\Users\Admin\.atom\packages\linter\lib\linter-view.coffee:162:18
  at FSReqWrap.oncomplete (fs.js:77:15)

```

### Commands

```
     -4:59.2.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -4:59.2.0 core:cancel (atom-text-editor.editor.is-focused)
     -4:51 core:save (atom-text-editor.editor.is-focused)
     -2:27.5.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -2:27.5.0 editor:newline (atom-text-editor.editor.is-focused)
     -2:27.3.0 core:paste (atom-text-editor.editor.is-focused)
     -2:10.6.0 core:save (atom-text-editor.editor.is-focused)
     -1:14.5.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:45.4.0 core:close (div.settings-view.pane-item)
     -0:09.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:09.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:08.9.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:08.9.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:07.8.0 core:paste (atom-text-editor.editor.is-focused)
     -0:06.5.0 core:save (atom-text-editor.editor.is-focused)
     -0:03.4.0 pane:show-previous-item (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-babel",
      "linter-jshint",
      "linter-jsxhint",
      "refactor",
      "js-refactor",
      "language-mustache",
      "autosave"
    ],
    "destroyEmptyPanes": false
  },
  "linter-eslint": {}
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.13.1
emmet, v2.3.9
linter, v0.12.2
linter-eslint, v0.5.4
npm-autocomplete, v0.1.2
react, v0.11.8

# Dev
No dev packages
```

**Comment by iam4x** [comment]
In your project:

* `npm install --save-dev eslint eslint-plugin-react`

**Comment by marudor** [comment]
With eslint 0.21 this is no longer working.
The options.plugin method is removed.
I have downgraded to eslint 0.20 for now. Would be nice if you could fix this though.

**Comment by mrtnbroder** [comment]
+1, no longer working for me with eslint 0.21. Would be great to get this fixed!

**Comment by AlexKVal** [comment]
ref: https://github.com/eslint/eslint/pull/2469/files#diff-3daec82d5218d64d8f2fed4d21f8e6ccL289

**Comment by AlexKVal** [comment]
I have a solution. Now making PR.

**Comment by eXon** [comment]
Awesome thank you for being so responsive :+1:
