### ISSUE TITLE
Error: Configuration for rule "quotes" is invalid: Value "[object Object]" must be an enum value.

### ISSUE THREAD

**Issue by luisrudge** [AtomLinter/linter-eslint#741]
my .eslintrc file has this line:
`"quotes": [2, "single", {"allowTemplateLiterals": true}],`

my linting is working fine, but linter-eslint is not recognizing my params :(

**Comment by IanVS** [comment]
Can you please run the command `Linter Eslint: Debug` and paste the output here?

**Comment by luisrudge** [comment]
hmm.. after disabling and enabling the plugin the problem went away.. I'll reopen if it happens again.

**Comment by luisrudge** [comment]
@IanVS it happened again. here's the debug output:

```
atom version: 1.11.2
linter-eslint version: 8.0.0
eslint version: 1.10.3
hours since last atom restart: 0.1
platform: win32
Using local project eslint from c:\git\rr\cis-v2-frontend\src\node_modules\eslint
linter-eslint configuration: {
  "lintHtmlFiles": false,
  "useGlobalEslint": false,
  "showRuleIdInMessage": true,
  "disableWhenNoEslintConfig": true,
  "eslintrcPath": "",
  "globalNodePath": "",
  "advancedLocalNodeModules": "",
  "eslintRulesDir": "",
  "disableEslintIgnore": false,
  "disableFSCache": false,
  "fixOnSave": false,
  "scopes": [
    "source.js",
    "source.jsx",
    "source.js.jsx",
    "source.babel",
    "source.js-semantic"
  ],
  "rulesToSilenceWhileTyping": []
}
```

**Comment by luisrudge** [comment]
Here's the error:

```
Error: c:\git\rr\cis-v2-frontend\src.eslintrc: Configuration for rule "quotes" is invalid: Value "[object Object]" must be an enum value.
Error: c:\git\rr\cis-v2-frontend\src\.eslintrc:
	Configuration for rule "quotes" is invalid:
	Value "[object Object]" must be an enum value.
    at validateRuleOptions (c:\git\rr\cis-v2-frontend\src\node_modules\eslint\lib\config\config-validator.js:102:15)
    at c:\git\rr\cis-v2-frontend\src\node_modules\eslint\lib\config\config-validator.js:148:13
    at Array.forEach (native)
    at Object.validate (c:\git\rr\cis-v2-frontend\src\node_modules\eslint\lib\config\config-validator.js:147:35)
    at Object.load (c:\git\rr\cis-v2-frontend\src\node_modules\eslint\lib\config\config-file.js:390:19)
    at loadConfig (c:\git\rr\cis-v2-frontend\src\node_modules\eslint\lib\config.js:74:33)
    at new Config (c:\git\rr\cis-v2-frontend\src\node_modules\eslint\lib\config.js:241:38)
    at CLIEngine.executeOnText (c:\git\rr\cis-v2-frontend\src\node_modules\eslint\lib\cli-engine.js:679:28)
    at Object.cli.execute (c:\git\rr\cis-v2-frontend\src\node_modules\eslint\lib\cli.js:162:36)
    at lintJob (C:\Users\luis\.atom\packages\linter-eslint\lib\worker.js:38:10)
```

**Comment by IanVS** [comment]
Your eslint version is _very_ old.  I'd suggest you try upgrading it.  My guess is that your `.eslintrc` is using a configuration for the rule that was added in a later version of ESLint.

**Comment by luisrudge** [comment]
ahhhhhhh. sorry man!

**Comment by IanVS** [comment]
No worries!  Happy linting.

**Comment by dr-nafanya** [comment]
Got very similar issue on Atom 1.17.2 with `linter-eslint` v8.1.2 after updating project dependencies.
```
Configuration for rule "quotes" is invalid: Value "[object Object]" must be an enum value.
```
Restarting Atom magically solved the problem.

**Comment by Arcanemagus** [comment]
@dr-nafanya The worker process tries to keep ESLint running whenever possible to avoid the time it takes to start up a new instance. If you update ESLint you need to restart Atom to get the worker process to take the update into account 😉.
