### ISSUE TITLE
Uncaught TypeError: Cannot read property 'request' of null

### ISSUE THREAD

**Issue by Jguardado** [AtomLinter/linter-eslint#751]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.12.2
**Electron Version**: 1.3.6
**System**: Mac OS X 10.12
**Thrown From**: [linter-eslint](https://github.com/AtomLinter/linter-eslint) package, v8.0.0

### Stack Trace

Uncaught TypeError: Cannot read property 'request' of null

```
At /Users/jguard4/.atom/packages/linter-eslint/lib/main.js:62

TypeError: Cannot read property 'request' of null
    at /Users/jguard4/.atom/packages/linter-eslint/lib/main.js:62:23
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1154:27)
    at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1124:19)
    at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:871:26)
    at MergeConflictsView.resolveFile (/Users/jguard4/.atom/packages/merge-conflicts/lib/view/merge-conflicts-view.coffee:120:9)
    at HTMLButtonElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/lib/space-pen.js:220:36)
    at HTMLButtonElement.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -1:38.8.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -1:36.8.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:34.6.0 merge-conflicts:detect (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-jshint",
      "jshint",
      "linter-jscs"
    ],
    "telemetryConsent": "limited",
    "themes": [
      "atom-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  },
  "linter-eslint": {
    "disableWhenNoEslintConfig": false,
    "eslintRulesDir": "/Users/jguard4/electrode-archetype-react-component/node_modules/eslint-config-defaults/rules/",
    "eslintrcPath": "/Users/jguard4/electrode-archetype-react-component/config/eslint/.eslintrc-react",
    "fixOnSave": true
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.13 (inactive)
atom-fix-path, v0.1.0 (active)
atom-live-server, v1.2.5 (inactive)
atom-runner, v2.7.1 (inactive)
browser-plus, v0.0.76 (active)
duotone-blue-dark-syntax, v1.4.0 (inactive)
duotone-bright-sea-syntax, v1.0.0-mod.1 (inactive)
duotone-dark-sea-syntax, v2.0.0 (inactive)
duotone-stark-sea-syntax, v1.0.0-mod.1 (inactive)
file-type-icons, v1.3.3 (active)
git-plus, v5.23.2 (active)
highlight-line, v0.11.1 (active)
highlight-selected, v0.11.2 (active)
linter, v1.11.18 (active)
linter-eslint, v8.0.0 (active)
linter-jscs, v4.1.0 (inactive)
linter-stylint, v2.2.5 (active)
merge-conflicts, v1.4.4 (active)
pumpkin-syntax, v0.1.0 (inactive)
rain-syntax, v1.0.2 (inactive)
rain-ui, v1.0.1 (inactive)
react, v0.16.1 (active)
script, v3.11.1 (inactive)
seti-classic-syntax, v0.5.0 (inactive)
seti-ui, v1.3.2 (inactive)
solarized-seti-ui, v0.8.6 (inactive)
Stylus, v3.1.0 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (active)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (active)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (inactive)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (inactive)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.1 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.46.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by Arcanemagus** [comment]
Are you getting any messages about not being able to initialize the worker process?

**Comment by Arcanemagus** [comment]
Closing due to a lack of response, if you are still experiencing this issue please include the output of the `Linter Eslint: Debug` command, thanks!
