### ISSUE TITLE
Error: ignoredMessages.includes is not a function

### ISSUE THREAD

**Issue by The-Alchemist** [AtomLinter/linter-eslint#752]
## Issue Type
Bug

## Issue Description

```
TypeError: ignoredMessages.includes is not a function
    at /Users/alchemist/.atom/packages/linter-eslint/lib/worker.js:39:29
    at Array.filter (native)
    at lintJob (/Users/alchemist/.atom/packages/linter-eslint/lib/worker.js:38:42)
    at /Users/alchemist/.atom/packages/linter-eslint/lib/worker.js:71:20
    at Emitter.emit (/Users/alchemist/.atom/packages/linter-eslint/node_modules/process-communication/node_modules/sb-event-kit/lib/emitter.js:70:19)
    at /Users/alchemist/.atom/packages/linter-eslint/node_modules/process-communication/node_modules/sb-communication/lib/main.js:22:23
    at /Users/alchemist/.atom/packages/linter-eslint/node_modules/process-communication/node_modules/sb-communication/lib/main.js:21:24
    at Emitter.emit (/Users/alchemist/.atom/packages/linter-eslint/node_modules/process-communication/node_modules/sb-event-kit/lib/emitter.js:68:19)
    at Communication.parseMessage (/Users/alchemist/.atom/packages/linter-eslint/node_modules/process-communication/node_modules/sb-communication/lib/main.js:63:18)
    at process.ProcessCommunication.messageCallback (/Users/alchemist/.atom/packages/linter-eslint/node_modules/process-communication/lib/communication.js:35:27)
```

![image](https://cloud.githubusercontent.com/assets/812287/20326264/fcd22144-ab55-11e6-90d3-2dc5eabfbc0a.png)

## Other Details

* I'm technically using the Learn IDE (Atom 1.9.0-2edf93d)
* The project I have open is https://github.com/learn-co-curriculum/javascript-logging-lab
* The file that breaks linter-eslint is https://github.com/learn-co-curriculum/javascript-logging-lab/blob/master/test/index-test.js
* ``eslint test/index-test.js`` works properly

**Comment by Arcanemagus** [comment]
As you can see from the [Atom requirements](https://github.com/AtomLinter/linter-eslint/blob/v8.0.0/package.json#L9), this package requires at least Atom v1.10.0. Your problem is that the version of Atom you are running is just too old to have the `Array.prototype.includes` function available.
