### ISSUE TITLE
Getting linter-eslint error on project that does not have ESLint set up

### ISSUE THREAD

**Issue by jrop** [AtomLinter/linter-eslint#770]
## Issue Type
Bug

## Issue Description
When I open a JS file in a project that does not have ESLint installed or setup, I am getting the following error: 

```
Error: Failed to load plugin react: Cannot find module 'eslint-plugin-react'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.load (/Users/jrapodac/.atom/packages/linter-eslint/node_modules/eslint/lib/config/plugins.js:129:26)
    at Array.forEach (native)
    at Object.loadAll (/Users/jrapodac/.atom/packages/linter-eslint/node_modules/eslint/lib/config/plugins.js:151:21)
    at Object.load (/Users/jrapodac/.atom/packages/linter-eslint/node_modules/eslint/lib/config/config-file.js:504:21)
    at loadConfig (/Users/jrapodac/.atom/packages/linter-eslint/node_modules/eslint/lib/config.js:63:33)
    at new Config (/Users/jrapodac/.atom/packages/linter-eslint/node_modules/eslint/lib/config.js:226:38)
```

Expected behavior: I expect not linter action at all, as I do not have ESLint setup for every JavaScript project (for example, "toy" projects) on my filesystem.  This issue does not occur on v7.

BTW, thanks for such a great plugin!  This atom plugin is amazing, as it streamlines my development workflow!

## Bug Checklist
- [x] Restart Atom
- [x] Verify the `eslint` CLI gives the proper result, while `linter-eslint` does not
- [x] Paste the output of the `Linter Eslint: Debug` command from the Command Palette below

```
atom version: 1.12.7
linter-eslint version: 8.0.0
eslint version: 3.12.2
hours since last atom restart: 0.1
platform: darwin
Using bundled fallback eslint from /Users/jrapodac/.atom/packages/linter-eslint/node_modules/eslint
linter-eslint configuration: {
  "lintHtmlFiles": false,
  "useGlobalEslint": false,
  "showRuleIdInMessage": true,
  "disableWhenNoEslintConfig": true,
  "eslintrcPath": "",
  "globalNodePath": "",
  "advancedLocalNodeModules": "",
  "eslintRulesDir": "",
  "disableEslintIgnore": false,
  "disableFSCache": false,
  "fixOnSave": false,
  "scopes": [
    "source.js",
    "source.jsx",
    "source.js.jsx",
    "source.babel",
    "source.js-semantic"
  ],
  "rulesToSilenceWhileTyping": []
}
```

**Comment by jrop** [comment]
I should have also mentioned this: I have this setting marked in the package settings, to no avail:

![Screenshot](http://i.imgur.com/DO3J33K.png)

**Comment by IanVS** [comment]
Do you happen to have an eslint config in your home directory?  

Choose one of the files that is throwing that warning, and then `eslint --print-config <filename>`.  My guess is there is a config somewhere which is looking for `eslint-plugin-react`.

**Comment by jrop** [comment]
@IanVS can't believe it was that simple: somehow an ESLint config file got copied to my home directory.  Thanks for the help.
