### ISSUE TITLE
Uncaught TypeError: Cannot assign to read only property 'capIsNewExceptions' of 2

### ISSUE THREAD

**Issue by jeffcharles** [AtomLinter/linter-eslint#78]
[Enter steps to reproduce below:]

1. Add `"new-cap": { "capIsNewExceptions": ["Router"] },` to `.eslintrc`
2. Visit a js file with `var router = express.Router();`

**Atom Version**: 0.199.0
**System**: Mac OS X 10.10.3
**Thrown From**: [linter-eslint](https://github.com/AtomLinter/linter-eslint) package, v0.5.6

### Stack Trace

Uncaught TypeError: Cannot assign to read only property 'capIsNewExceptions' of 2

```
At /Users/jeff/projects/let-me-in/node_modules/eslint/lib/util.js:52

TypeError: Cannot assign to read only property 'capIsNewExceptions' of 2
  at /Users/jeff/projects/let-me-in/node_modules/eslint/lib/util.js:52:23
  at Array.forEach (native)
  at mergeConfigs (/Users/jeff/projects/let-me-in/node_modules/eslint/lib/util.js:25:25)
  at /Users/jeff/projects/let-me-in/node_modules/eslint/lib/util.js:50:25
  at Array.forEach (native)
  at mergeConfigs (/Users/jeff/projects/let-me-in/node_modules/eslint/lib/util.js:25:25)
  at /Users/jeff/projects/let-me-in/node_modules/eslint/lib/util.js:50:25
  at Array.forEach (native)
  at Object.mergeConfigs (/Users/jeff/projects/let-me-in/node_modules/eslint/lib/util.js:25:25)
  at Config.getConfig (/Users/jeff/projects/let-me-in/node_modules/eslint/lib/config.js:365:19)
  at CLIEngine.getConfigForFile (/Users/jeff/projects/let-me-in/node_modules/eslint/lib/cli-engine.js:392:29)
  at LinterESLint.lintFile (/Users/jeff/.atom/packages/linter-eslint/lib/linter-eslint.coffee:80:21)
  at /Users/jeff/.atom/packages/linter/lib/linter-view.coffee:163:18
  at Array.forEach (native)
  at /Users/jeff/.atom/packages/linter/lib/linter-view.coffee:162:18
  at FSReqWrap.oncomplete (fs.js:77:15)

```

### Commands

```
     -2:49.9.0 editor:newline (atom-text-editor.editor.is-focused)
     -2:40.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:38 core:save (atom-text-editor.editor.is-focused)
  2x -1:08.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:28.4.0 core:save (atom-text-editor.editor.is-focused)
  7x -0:23.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:16.9.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:14.8.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
editorconfig, v1.0.0
linter, v0.12.2
linter-eslint, v0.5.6

# Dev
No dev packages
```

**Comment by iam4x** [comment]
Related to `eslint`
