### ISSUE TITLE
Error: Failed to load plugin react: Cannot find module 'eslint-plugin-react'

### ISSUE THREAD

**Issue by lumio** [AtomLinter/linter-eslint#799]
## Issue Type
Bug

## Issue Description
Just updated to 8.1.0 and am getting the following error message:

I am working on a tiny jekyll project without a eslint config file or anything like that. Also this project has nothing to do with React.

## Bug Checklist
- Restart Atom... ✅ 
- Verify the `eslint` CLI gives the proper result, while `linter-eslint` does not... ✅ 
- Paste the output of the `Linter Eslint: Debug` command from the Command Palette below... ✅ 

```
Error: Failed to load plugin react: Cannot find module 'eslint-plugin-react'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.load (/Users/lumio/.atom/packages/linter-eslint/node_modules/eslint/lib/config/plugins.js:129:26)
    at Array.forEach (native)
    at Object.loadAll (/Users/lumio/.atom/packages/linter-eslint/node_modules/eslint/lib/config/plugins.js:151:21)
    at Object.load (/Users/lumio/.atom/packages/linter-eslint/node_modules/eslint/lib/config/config-file.js:504:21)
    at loadConfig (/Users/lumio/.atom/packages/linter-eslint/node_modules/eslint/lib/config.js:63:33)
    at getLocalConfig (/Users/lumio/.atom/packages/linter-eslint/node_modules/eslint/lib/config.js:130:29)
```

**Comment by IanVS** [comment]
Thanks for the report.  Can you explain how your filestructure looks?  Do you have an eslint config in your user home directory?  Or one in any folder between your project and `/`?  Is your project located within your user home?

**Comment by lumio** [comment]
Oh this is embarassing. It seems I'm not capable of multitasking and copied another .eslintrc to that specific project. Yet I got confused since eslint would work just fine.

I'm sorry. Thank you for your support though! 😄
