### ISSUE TITLE
Uncaught Error: Definition for rule 'object-shorthand' was not found.

### ISSUE THREAD

**Issue by openam** [AtomLinter/linter-eslint#81]
**Atom Version**: 0.200.0
**System**: Mac OS X 10.10.3
**Thrown From**: [linter-eslint](https://github.com/AtomLinter/linter-eslint) package, v0.5.8

### Stack Trace

Uncaught Error: Definition for rule 'object-shorthand' was not found.

```
At repo/node_modules/eslint/lib/eslint.js:657

Error: Definition for rule 'object-shorthand' was not found.
  at repo/node_modules/eslint/lib/eslint.js:657:27
  at Array.forEach (native)
  at EventEmitter.module.exports.api.verify (repo/node_modules/eslint/lib/eslint.js:630:16)
  at /Users/username/.atom/packages/linter-eslint/lib/linter-eslint.coffee:129:25
  at exports.allowUnsafeNewFunction (/Users/username/.atom/packages/linter-eslint/node_modules/loophole/lib/loophole.js:25:14)
  at LinterESLint.lintFile (/Users/username/.atom/packages/linter-eslint/lib/linter-eslint.coffee:128:7)
  at /Users/username/.atom/packages/linter/lib/linter-view.coffee:163:18
  at Array.forEach (native)
  at /Users/username/.atom/packages/linter/lib/linter-view.coffee:162:18
  at FSReqWrap.oncomplete (fs.js:77:15)

```

### Commands

```
  2x -7:15.7.0 core:move-right (atom-text-editor.editor.is-focused)
     -7:15 core:backspace (atom-text-editor.editor.is-focused)
  5x -7:14.3.0 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -6:43.4.0 core:move-down (atom-text-editor.editor.is-focused)
     -6:43.1.0 core:move-up (atom-text-editor.editor.is-focused)
     -6:41.8.0 editor:delete-line (atom-text-editor.editor.is-focused)
     -6:40.9.0 core:move-up (atom-text-editor.editor.is-focused)
     -6:39.2.0 core:save (atom-text-editor.editor.is-focused)
     -4:01.2.0 core:move-up (atom-text-editor.editor.is-focused)
  2x -3:59.6.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
  2x -3:58.8.0 core:select-down (atom-text-editor.editor.is-focused)
     -3:57.3.0 core:copy (atom-text-editor.editor.is-focused)
  4x -1:25.9.0 core:select-down (atom-text-editor.editor.is-focused)
     -1:22.6.0 core:cut (atom-text-editor.editor.is-focused)
     -0:57.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:56.9.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ]
  },
  "linter-eslint": {}
}
```

### Installed Packages

```coffee
# User
aligner, v0.13.0
aligner-css, v1.2.0
duplicate-line-or-selection, v0.5.0
editorconfig, v1.0.0
highlight-selected, v0.9.3
language-docker, v1.1.3
linter, v0.12.6
linter-eslint, v0.5.8
linter-jscs, v1.12.0
linter-jshint, v0.1.4
react, v0.11.8
subword-navigation, v2.7.0

# Dev
No dev packages
```

**Comment by iam4x** [comment]
`eslint` related, the rule is incorrect in your `.eslintrc`
