### ISSUE TITLE
Error: ESLint not found, Please install or make sure Atom is getting $PATH correctly

### ISSUE THREAD

**Issue by nylki** [AtomLinter/linter-eslint#828]
## Issue Type
"Bug"

## Issue Description
Saving a JS file (executing linter: lint) results in this error:

```
Error: ESLint not found, Please install or make sure Atom is getting $PATH correctly
    at findESLintDirectory (/home/tom/.atom/packages/linter-eslint/lib/worker-helpers.js:90:13)
    at getESLintFromDirectory (/home/tom/.atom/packages/linter-eslint/lib/worker-helpers.js:100:30)
    at Object.getESLintInstance (/home/tom/.atom/packages/linter-eslint/lib/worker-helpers.js:127:10)
    at global.onRequest (/home/tom/.atom/packages/linter-eslint/lib/worker.js:68:26)
    at Emitter.emit (/home/tom/.atom/packages/linter-eslint/node_modules/sb-event-kit/lib/emitter.js:70:19)
    at /home/tom/.atom/packages/linter-eslint/node_modules/sb-communication/lib/main.js:22:23
    at /home/tom/.atom/packages/linter-eslint/node_modules/sb-communication/lib/main.js:21:24
    at Emitter.emit (/home/tom/.atom/packages/linter-eslint/node_modules/sb-event-kit/lib/emitter.js:68:19)
    at Communication.parseMessage (/home/tom/.atom/packages/linter-eslint/node_modules/sb-communication/lib/main.js:63:18)
    at process.messageCallback (/home/tom/.atom/packages/linter-eslint/node_modules/process-communication/lib/communication.js:35:27)
```

I have used `linter-eslint` for a long time before and this error just occured suddenly today after deleting some file in a project repo and remains even when restarting Atom. I might have updated linter some days ago, which may be an issue here, but I can't remember. I am using Atom 1.14.3 with `linter-eslint` 8.1.1 on Fedora 25.

## Bug Checklist
- Verify the `eslint` CLI gives the proper result, while `linter-eslint` does not:

```.sh
$ eslint
eslint [options] file.js [file.js] [dir]

Basic configuration:
  -c, --config path::String   Use configuration from this file or shareable config
  --no-eslintrc               Disable use of configuration from .eslintrc
  --env [String]              Specify environments
  […snip, more help page stuff]

$ linter-eslint
zsh: linter-eslint: Befehl nicht gefunden...
zsh: command not found: linter-eslint

```

- Paste the output of the `Linter Eslint: Debug` command from the Command Palette below

```
Error: ESLint not found, Please install or make sure Atom is getting $PATH correctly
```

but: 
```.sh
which eslint
~/node_modules/bin/eslint
```

**Comment by IanVS** [comment]
How do you have `Global Node Installation Path` set?

**Comment by nylki** [comment]
`npm config get prefix` tells me its: `/home/tom/.nvm/versions/node/v7.5.0`.
Interesting. Shouldn't the install dir of `which eslint` match `npm config get prefix`?

…

I did a manual `npm install -g eslint` and removed my deprecated old install path, restarted Atom and it works again. Might have something to do with me updating nvm recently. Thanks for the hint @IanVS !

**Comment by iarobinson** [comment]
Thanks for this.

`npm install -g eslint` solved my problem

**Comment by WebrangerC** [comment]
Thanks. Running the npm install -g eslint and settng the global path was my solution
