### ISSUE TITLE
linter-eslint failed to activate, missing dependency `process-communication`

### ISSUE THREAD

**Issue by pbogdan03** [AtomLinter/linter-eslint#831]
## Issue Type
Bug

## Issue Description
linter-eslint failed to activate, missing dependency `process-communication`

```
Linter Eslint: Debug output here
```

1. Open Atom
2. The package should auto load

**Atom**: 1.14.3 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [linter-eslint](https://github.com/AtomLinter/linter-eslint) package 8.1.2

### Stack Trace

Failed to activate the linter-eslint package

```
At Cannot find module 'process-communication'

Error: Cannot find module 'process-communication'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/linter-eslint/lib/helpers.js:176:29)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/linter-eslint/lib/main.js:10:16)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:207:16)
    at /app.asar/src/package.js:190:32
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at /app.asar/src/package.js:183:26
    at Package.module.exports.Package.activate (/app.asar/src/package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:550:34)
    at /app.asar/src/package-manager.js:531:29
```

### Commands

```
     -1:37.5.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-solarized-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
advanced-open-file 0.16.5 
atom-beautify 0.29.17 
atom-handlebars 1.3.0 
autocomplete-emojis 2.5.0 
color-picker 2.2.5 
emmet 2.4.3 
file-icons 2.0.15 
Handlebars 1.7.1 
language-mjml 1.8.0 
linter 1.11.23 
linter-eslint 8.1.2 
linter-mjml 1.0.0 
minimap 4.26.8 
mjml-preview 1.2.0 
pigments 0.39.0 
Stylus 3.1.0 
tasks 2.6.6 
```

I already tried to remove `useGlobalEslint: true` from `config.cson` with no luck.

**Comment by Arcanemagus** [comment]
Can you try re-installing the package? It seems you have hit the infamous bug where `apm` fails to install all the dependencies.

**Comment by pbogdan03** [comment]
That worked! Thanks
