### ISSUE TITLE
Uncaught Error: Definition for rule 'no-dupe-arg' was not found.

### ISSUE THREAD

**Issue by jfairley** [AtomLinter/linter-eslint#84]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.201.0
**System**: Mac OS X 10.10.3
**Thrown From**: [linter-eslint](https://github.com/AtomLinter/linter-eslint) package, v0.5.8

### Stack Trace

Uncaught Error: Definition for rule 'no-dupe-arg' was not found.

```
At /Users/jfairley/Development/workspace-git/live-clipping-ui/node_modules/eslint/lib/eslint.js:647

Error: Definition for rule 'no-dupe-arg' was not found.
  at /Users/jfairley/Development/workspace-git/live-clipping-ui/node_modules/eslint/lib/eslint.js:647:27
  at Array.forEach (native)
  at EventEmitter.module.exports.api.verify (/Users/jfairley/Development/workspace-git/live-clipping-ui/node_modules/eslint/lib/eslint.js:620:16)
  at /Users/jfairley/.atom/packages/linter-eslint/lib/linter-eslint.coffee:129:25
  at exports.allowUnsafeNewFunction (/Users/jfairley/.atom/packages/linter-eslint/node_modules/loophole/lib/loophole.js:25:14)
  at LinterESLint.lintFile (/Users/jfairley/.atom/packages/linter-eslint/lib/linter-eslint.coffee:128:7)
  at /Users/jfairley/.atom/packages/linter/lib/linter-view.coffee:163:18
  at Array.forEach (native)
  at /Users/jfairley/.atom/packages/linter/lib/linter-view.coffee:162:18
  at FSReqWrap.oncomplete (fs.js:77:15)

```

### Commands

```
  2x -0:47.1.0 go-to-line:toggle (atom-text-editor.editor.is-focused)
  2x -0:40.9.0 find-and-replace:show (atom-text-editor.editor.is-focused)
     -0:22.7.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:22.7.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:22.5.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:22.5.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:22.2.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:22.2.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:20.5.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "themes": [
      "seti-ui",
      "greti-syntax"
    ],
    "disabledPackages": [
      "jshint",
      "eslint",
      "eslint",
      "eslint"
    ]
  },
  "linter-eslint": {
    "disableWhenNoEslintrcFileInPath": true
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.0
api-blueprint-preview, v0.5.1
editorconfig, v1.0.0
greti-syntax, v0.5.4
language-docker, v1.1.3
language-flex, v0.2.0
linter, v0.12.6
linter-eslint, v0.5.8
linter-jshint, v0.1.5
linter-jsxhint, v0.1.2
minimap, v4.9.0
react, v0.11.8
seti-ui, v0.7.1

# Dev
No dev packages
```

**Comment by jfairley** [comment]
My mistake. It should be "no-dupe-args" (plural)
