### ISSUE TITLE
Uncaught Error: Definition for rule 'linebreak-style' was not found.

### ISSUE THREAD

**Issue by mistadikay** [AtomLinter/linter-eslint#85]
.eslintrc to reproduce:
```json
---
  parser: babel-eslint

  rules:
    linebreak-style:
      - 2
      - unix
```

**Atom Version**: 0.201.0
**System**: Mac OS X 10.10.3
**Thrown From**: [linter-eslint](https://github.com/AtomLinter/linter-eslint) package, v0.5.8

### Stack Trace

Uncaught Error: Definition for rule 'linebreak-style' was not found.

```
At /Users/lazhcm10348/Projects/yummies/theme-primer/node_modules/eslint/lib/eslint.js:648

Error: Definition for rule 'linebreak-style' was not found.
  at /Users/lazhcm10348/Projects/yummies/theme-primer/node_modules/eslint/lib/eslint.js:648:27
  at Array.forEach (native)
  at EventEmitter.module.exports.api.verify (/Users/lazhcm10348/Projects/yummies/theme-primer/node_modules/eslint/lib/eslint.js:621:16)
  at /Users/lazhcm10348/.atom/packages/linter-eslint/lib/linter-eslint.coffee:129:25
  at exports.allowUnsafeNewFunction (/Users/lazhcm10348/.atom/packages/linter-eslint/node_modules/loophole/lib/loophole.js:25:14)
  at LinterESLint.lintFile (/Users/lazhcm10348/.atom/packages/linter-eslint/lib/linter-eslint.coffee:128:7)
  at /Users/lazhcm10348/.atom/packages/linter/lib/linter-view.coffee:163:18
  at Array.forEach (native)
  at /Users/lazhcm10348/.atom/packages/linter/lib/linter-view.coffee:162:18
  at FSReqWrap.oncomplete (fs.js:77:15)

```

### Commands

```
     -5:05.2.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -5:05.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -5:04.8.0 core:copy (atom-text-editor.editor.is-focused)
     -5:02.2.0 tree-view:remove (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -4:59.5.0 core:close (atom-text-editor.editor.is-focused)
     -4:53.2.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -4:53.2.0 editor:newline (atom-text-editor.editor.is-focused)
     -4:53 core:paste (atom-text-editor.editor.is-focused)
     -4:52.1.0 core:save (atom-text-editor.editor.is-focused)
  3x -4:50.8.0 core:move-down (atom-text-editor.editor.is-focused)
  3x -4:49.7.0 core:select-down (atom-text-editor.editor.is-focused)
     -4:48.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -4:48.6.0 core:save (atom-text-editor.editor.is-focused)
     -3:44.7.0 project-manager:toggle (atom-text-editor.editor.is-focused)
     -3:41.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -0:03.6.0 core:close (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "welcome",
      "metrics",
      "language-toml",
      "language-ruby-on-rails",
      "language-ruby",
      "language-python",
      "language-perl",
      "language-java",
      "language-csharp",
      "language-c",
      "background-tips",
      "archive-view",
      "project-palette-finder",
      "linter-csslint",
      "linter-less",
      "linter-scss-lint",
      "linter-jscs",
      "autocomplete-glsl",
      "github-issues",
      "language-javascript",
      "language-clojure",
      "language-coffee-script",
      "language-objective-c",
      "language-go",
      "language-javascript-jsx",
      "open-last-project",
      "javascript-refactoring",
      "bookmark-panel",
      "minimap-bookmarks",
      "atom-pair",
      "js-refactor",
      "refactor",
      "minimap-find-and-replace",
      "minimap-autohide",
      "autohide-tree-view",
      "autocomplete-atom-api",
      "node-resolver",
      "regex-railroad-diagram",
      "tool-bar-main",
      "mechanical-keyboard",
      "git-control",
      "language-javascript-better",
      "node-debugger"
    ]
  },
  "linter-eslint": {
    "disableWhenNoEslintrcFileInPath": true
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.27.6
autocomplete-emojis, v2.2.2
autocomplete-paths, v1.0.2
color-picker, v1.7.0
editorconfig, v1.0.0
emmet, v2.3.10
file-icons, v1.5.5
flex-tool-bar, v0.3.0
fonts, v0.4.2
git-projects, v1.14.1
highlight-selected, v0.9.3
language-babel, v0.5.6
language-gitignore, v0.2.0
linter, v0.12.6
linter-eslint, v0.5.8
minimap, v4.9.0
minimap-color-highlight, v4.1.3
minimap-git-diff, v4.1.3
minimap-highlight-selected, v4.2.3
minimap-selection, v4.2.0
pigments, v0.3.1
project-manager, v1.15.7
project-view, v0.1.2
react, v0.11.8
remote-edit, v1.7.2
svg-preview, v0.6.0
tool-bar, v0.1.2
travis-ci-status, v0.15.0
wakatime, v4.0.9

# Dev
No dev packages
```

**Comment by iam4x** [comment]
Error thrown from `eslint` it should has been updated and fixed now.
