### ISSUE TITLE
Failed to load plugin import: Cannot find module 'eslint-plugin-import'

### ISSUE THREAD

**Issue by yubaoquan** [AtomLinter/linter-eslint#861]
## Issue Description
It is not working . I try to reinstall linter-eslint and linter. but it seems still not working.

## Bug Checklist
- Restart Atom
- Verify the `eslint` CLI gives the proper result, while `linter-eslint` does not
- Paste the output of the `Linter Eslint: Debug` command from the Command Palette below

```
linter-eslint debugging information
Atom version: 1.15.0
linter-eslint version: 8.1.4
ESLint version: 3.18.0
Hours since last Atom restart: 0
Platform: win32
Using bundled fallback ESLint from: C:\Users\hzyubaoquan\.atom\packages\linter-eslint\node_modules\eslint
Current file's scopes: [
  "source.js",
  "meta.function-call.js",
  "meta.arguments.js",
  "meta.method-call.js",
  "meta.arguments.js"
]
linter-eslint configuration: {
  "lintHtmlFiles": false,
  "useGlobalEslint": false,
  "showRuleIdInMessage": true,
  "disableWhenNoEslintConfig": true,
  "eslintrcPath": "",
  "globalNodePath": "",
  "advancedLocalNodeModules": "",
  "eslintRulesDir": "",
  "disableEslintIgnore": false,
  "disableFSCache": false,
  "fixOnSave": false,
  "scopes": [
    "source.js",
    "source.jsx",
    "source.js.jsx",
    "source.babel",
    "source.js-semantic"
  ],
  "rulesToSilenceWhileTyping": [],
  "rulesToDisableWhileFixing": []
}


Linter Eslint: Debug output here
Error: Failed to load plugin import: Cannot find module 'eslint-plugin-import'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.load (C:\Users\xxx\.atom\packages\linter-eslint\node_modules\eslint\lib\config\plugins.js:129:26)
    at Array.forEach (native)
    at Object.loadAll (C:\Users\xxx\.atom\packages\linter-eslint\node_modules\eslint\lib\config\plugins.js:151:21)
    at Object.load (C:\Users\xxx\.atom\packages\linter-eslint\node_modules\eslint\lib\config\config-file.js:541:21)
    at loadConfig (C:\Users\xxx\.atom\packages\linter-eslint\node_modules\eslint\lib\config.js:63:33)
    at new Config (C:\Users\xxx\.atom\packages\linter-eslint\node_modules\eslint\lib\config.js:229:42)
```

**Comment by yubaoquan** [comment]
my fault . .eslintrc was modified by someone in team
