### ISSUE TITLE
Cannot find module 'eslint-plugin-html'

### ISSUE THREAD

**Issue by PierBover** [AtomLinter/linter-eslint#874]
## Issue Type
Not sure if this is a bug. ESLint works fine in another project with a similar configuration.

## Issue Description
I'm getting the error in the console:

> Error running ESLint Error: Failed to load plugin html: Cannot find module 'eslint-plugin-html'

I've installed `eslint-plugin-html` both locally in my project and globally just in case.

This is my `.eslintrc.js`

```
module.exports = {
  root: true,
  parser: 'babel-eslint',
  parserOptions: {
    sourceType: 'module'
  },
  env: {
    browser: true,
  },
  plugins: [
    'html'
  ],
  'rules': {
    ...
  }
}
```

## Bug Checklist

```
Atom version: 1.15.0
linter-eslint version: 8.1.4
ESLint version: 3.17.1
Hours since last Atom restart: 0.1
Platform: darwin
Using bundled fallback ESLint from: /Users/pier/.atom/packages/linter-eslint/node_modules/eslint
Current file's scopes: [
  "source.json",
  "meta.structure.dictionary.json",
  "meta.structure.dictionary.value.json",
  "meta.structure.dictionary.json",
  "meta.structure.dictionary.value.json",
  "punctuation.separator.dictionary.pair.json"
]
linter-eslint configuration: {
  "lintHtmlFiles": true,
  "useGlobalEslint": false,
  "showRuleIdInMessage": true,
  "disableWhenNoEslintConfig": true,
  "eslintrcPath": "",
  "globalNodePath": "",
  "advancedLocalNodeModules": "",
  "eslintRulesDir": "",
  "disableEslintIgnore": false,
  "disableFSCache": false,
  "fixOnSave": false,
  "scopes": [
    "source.js",
    "source.jsx",
    "source.js.jsx",
    "source.babel",
    "source.js-semantic"
  ],
  "rulesToSilenceWhileTyping": [],
  "rulesToDisableWhileFixing": []
}
```

**Comment by Arcanemagus** [comment]
Looks like it's unable to find an ESLint install in your project and falling back to the bundled one. Do you have `eslint` as a `devDependency` in your project?

**Comment by PierBover** [comment]
Yes that was it.

**Comment by lmj0011** [comment]
This problem usually occurs whenever you forget to do a `npm install` before opening a new project in Atom.

**Comment by nmfzone** [comment]
+1 also happen in here. I've installed `eslint-plugin-html` both locally and globally.

**Comment by CyberStrike** [comment]
After running `npm install` and not having any affect after a restart of the applications and system, this is what ended up working for me.

### My Solution
1. delete `node_modules` 
2. delete `package-lock.json`
3. npm install

**Comment by dcsan** [comment]
I'm having the same problem, cannot resolve with the steps above.

> Do you have eslint as a devDependency in your project?

can you explain why this might cause the issue?

I have
- delete node_modules
- delete package-lock.json
- clean install

I also tried

`npm i -g eslint-plugin-html`

this is a project built with the vue-cli
it has been working without issues for a couple of weeks but today stopped working.
I think the only thing i did was try to `yarn add ...` something.

but not sure what artifacts `yarn` might have added that would break the linter.

any other ideas to try and resolve this?

**Comment by dcsan** [comment]
In my case the atom dev debug side panel shows:

```
<embedded>:107023 IntersectionObserver.observe(target): target element is not a descendant of root.
TreeView @ <embedded>:107023
/Users/dc/.atom/packages/linter-python-pep8/lib/init.coffee:7 activate linter-python-pep8
<embedded>:71070 Failed to load plugin html: Cannot find module 'eslint-plugin-html' Error: Failed to load plugin html: Cannot find module 'eslint-plugin-html'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.resolve (internal/module.js:27:19)
    at Object.load (/Users/dc/dev/rikai/nlp-rnd/nlp-debug/node_modules/eslint/lib/config/plugins.js:134:29)
    at Array.forEach (native)
    at Object.loadAll (/Users/dc/dev/rikai/nlp-rnd/nlp-debug/node_modules/eslint/lib/config/plugins.js:162:21)
    at Object.load (/Users/dc/dev/rikai/nlp-rnd/nlp-debug/node_modules/eslint/lib/config/config-file.js:541:21)
    at loadConfig (/Users/dc/dev/rikai/nlp-rnd/nlp-debug/node_modules/eslint/lib/config.js:63:33)
    at getLocalConfig (/Users/dc/dev/rikai/nlp-rnd/nlp-debug/node_modules/eslint/lib/config.js:130:29)
    at Config.getConfig (/Users/dc/dev/rikai/nlp-rnd/nlp-debug/node_modules/eslint/lib/config.js:260:26)
    at processText (/Users/dc/dev/rikai/nlp-rnd/nlp-debug/node_modules/eslint/lib/cli-engine.js:224:33)
    at CLIEngine.executeOnText (/Users/dc/dev/rikai/nlp-rnd/nlp-debug/node_modules/eslint/lib/cli-engine.js:754:26)
    at lintJob (/Users/dc/.atom/packages/linter-eslint/src/worker.js:14:20)
    at process.<anonymous> (/Users/dc/.atom/packages/linter-eslint/src/worker.js:52:22)
    at emitTwo (events.js:111:20)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:752:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
(anonymous) @ <embedded>:71070
/Users/dc/.atom/packages/linter/lib/linter-registry.js:159 [Linter] Error running ESLint Error: Failed to load plugin html: Cannot find module 'eslint-plugin-html'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.resolve (internal/module.js:27:19)
    at Object.load (/Users/dc/dev/rikai/nlp-rnd/nlp-debug/node_modules/eslint/lib/config/plugins.js:134:29)
    at Array.forEach (native)
    at Object.loadAll (/Users/dc/dev/rikai/nlp-rnd/nlp-debug/node_modules/eslint/lib/config/plugins.js:162:21)
    at Object.load (/Users/dc/dev/rikai/nlp-rnd/nlp-debug/node_modules/eslint/lib/config/config-file.js:541:21)
    at loadConfig (/Users/dc/dev/rikai/nlp-rnd/nlp-debug/node_modules/eslint/lib/config.js:63:33)
    at getLocalConfig (/Users/dc/dev/rikai/nlp-rnd/nlp-debug/node_modules/eslint/lib/config.js:130:29)
    at Config.getConfig (/Users/dc/dev/rikai/nlp-rnd/nlp-debug/node_modules/eslint/lib/config.js:260:26)
    at processText (/Users/dc/dev/rikai/nlp-rnd/nlp-debug/node_modules/eslint/lib/cli-engine.js:224:33)
    at CLIEngine.executeOnText (/Users/dc/dev/rikai/nlp-rnd/nlp-debug/node_modules/eslint/lib/cli-engine.js:754:26)
    at lintJob (/Users/dc/.atom/packages/linter-eslint/src/worker.js:14:20)
    at process.<anonymous> (/Users/dc/.atom/packages/linter-eslint/src/worker.js:52:22)
    at emitTwo (events.js:111:20)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:752:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
(anonymous) @ /Users/dc/.atom/packages/linter/lib/linter-registry.js:159
```

**Comment by dcsan** [comment]
UI now looks like this, so this issue makes the linter completely unusable

![image](https://user-images.githubusercontent.com/514002/29392969-fb2d51be-82b5-11e7-88e2-4d6fbc150b9a.png)

**Comment by Arcanemagus** [comment]
@dcsan Can you please post a new issue and follow the issue template? Without the debug information it's hard to know where to start debugging what is wrong with your setup, and there is no reason to spam the other 4 people on this thread with getting that all figured out 😉.
