### ISSUE TITLE
Error running JSHint - linter-registry.js

### ISSUE THREAD

**Issue by squaredindex** [AtomLinter/linter-eslint#879]
## Issue Description
 Error running JSHint.
![linter error running jshint](http://imgur.com/ELT2mKm.png "linter error running jshint")

## Error from console - linter-registry.js

```
linter-registry.js [sm]:144 [Linter] Error running JSHint Error: /Users/lev/.atom/packages/linter-jshint/node_modules/jshint-json/json.js:4
		console.log(JSON.stringify({
		                 ^

TypeError: Converting circular structure to JSON
    at Object.stringify (native)
    at reporter (/Users/lev/.atom/packages/linter-jshint/node_modules/jshint-json/json.js:4:20)
    at Object.<anonymous> (/Users/lev/.atom/packages/linter-jshint/node_modules/jshint/src/cli.js:635:39)
    at Socket.<anonymous> (/Users/lev/.atom/packages/linter-jshint/node_modules/cli/cli.js:844:18)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Object.stringify (native)
    at reporter (/Users/lev/.atom/packages/linter-jshint/node_modules/jshint-json/json.js:4:20)
    at Object.<anonymous> (/Users/lev/.atom/packages/linter-jshint/node_modules/jshint/src/cli.js:635:39)
    at Socket.<anonymous> (/Users/lev/.atom/packages/linter-jshint/node_modules/cli/cli.js:844:18)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at ChildProcess.<anonymous> (/Users/lev/.atom/packages/linter-jshint/node_modules/sb-exec/lib/index.js:56:20)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)(anonymous function) @ linter-registry.js [sm]:144
linter-registry.js [sm]:144 [Linter] Error running JSHint Error: /Users/lev/.atom/packages/linter-jshint/node_modules/jshint-json/json.js:4(…)(anonymous function) @ linter-registry.js [sm]:144
```

**Comment by IanVS** [comment]
Sorry, I'm afraid you have the wrong repo. This is the Atom plugin for ESLint.

**Comment by kirykr** [comment]
It depends on the version of you linter: I had the same problem as you did. Trying to fix the error. Turns out you have to install the correct version of eslint:
Mine is:
```
{
  "name": "react-weather",
  "version": "1.0.0",
  "description": "Simple React App",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "kiry",
  "license": "MIT",
  "dependencies": {
    "express": "^4.15.3",
    "react": "^15.6.1",
    "react-dom": "^15.6.1",
    "react-router": "^4.1.1",
    "react-router-dom": "^4.1.1"
  },
  "devDependencies": {
    "babel-core": "^6.25.0",
    "babel-eslint": "^7.2.3",
    "babel-loader": "^7.1.0",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-0": "^6.24.1",
    "eslint": "^3.19.0",
    "eslint-plugin-react": "^6.10.3",
    "webpack": "^3.0.0"
  }
}
```
you just need the `eslint` and its plugins in this case I use react `eslint-plugin-react` and the configuration in the `.eslintrc.js` is:
```
module.exports = {
  "parser": 'babel-eslint',
  "env": {
    "browser": true,
    "commonjs": true,
    "es6": true,
    "node": true
  },
  "extends": ["eslint:recommended", "plugin:react/recommended"],
  "parserOptions": {
    "ecmaFeatures": {
      "experimentalObjectRestSpread": true,
      "jsx": true
    },
    "sourceType": "module"
  },
  "plugins": [ "react" ],
  "rules": {
    "indent": ["error", 2],
    "linebreak-style": ["error","unix"],
    "quotes": ["error","single"],
    "semi": ["error","always"],
    "no-console": ["warn", { "allow": ["info", "error"] }]
  }
};
```
