### ISSUE TITLE
Uncaught Error: Cannot find module 'atom-package-deps'

### ISSUE THREAD

**Issue by RobinNX** [AtomLinter/linter-eslint#881]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [linter-eslint](https://github.com/AtomLinter/linter-eslint) package 8.1.5

### Stack Trace

Uncaught Error: Cannot find module 'atom-package-deps'

```
At /private/var/folders/dx/t4gl19gd7ll8jy8d7491hky40000gn/T/AppTranslocation/F2D515E1-C8B7-462C-AC39-575C85407E89/d/Atom.app/Contents/Resources/app.asar/src/module-cache.js:379

Error: Cannot find module 'atom-package-deps'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/private/var/folders/dx/t4gl19gd7ll8jy8d7491hky40000gn/T/AppTranslocation/F2D515E1-C8B7-462C-AC39-575C85407E89/d/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at installLinterEslintDeps (/packages/linter-eslint-master/lib/main.js:42:43)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.29.18 
pigments 0.39.1 
atom-ternjs 0.18.2 
color-picker 2.2.5 
js-hyperclick 1.10.1 
linter-eslint 8.1.5 
linter 2.1.2 
minimap 4.27.1 
react-build 16.0.0-alpha.8 
```

**Comment by Arcanemagus** [comment]
Please re-install the package, looks like APM failed to install all dependencies for you.

**Comment by Pysis868** [comment]
How do we do this now with Atom sunset?  After a `npm i -g atom-package-deps` and linking in packages directory like the others didn't work..
