### ISSUE TITLE
Uncaught SyntaxError: Invalid or unexpected token

### ISSUE THREAD

**Issue by gennadiy1970** [AtomLinter/linter-eslint#899]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 ia32
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [linter-eslint](https://github.com/AtomLinter/linter-eslint) package 8.1.7

### Stack Trace

Uncaught SyntaxError: Invalid or unexpected token

```
At C:\Users\ggm\AppData\Local\atom\app-1.16.0\resources\app.asar\src\native-compile-cache.js:82

SyntaxError: Invalid or unexpected token
    at Module._compile (/app.asar/src/native-compile-cache.js:79:40)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/linter-eslint/lib/helpers.js:185:29)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at initializeWorker (/packages/linter-eslint/lib/main.js:64:19)
```

### Commands

```
     -1:36.5.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-base16-tomorrow-dark-theme.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-alignment 0.12.1 
atom-beautify 0.29.23 
atom-live-server 2.1.2 
autoclose-html 0.23.0 
busy-signal 1.4.1 
color-picker 2.2.5 
emmet 2.4.3 
file-icons 2.1.4 
intentions 1.1.2 
language-javascript-jsx 0.3.7 
linter 2.1.4 
linter-csslint 1.3.4 
linter-eslint 8.1.7 
linter-htmlhint 1.3.3 
linter-jshint 3.0.3 
linter-sass-lint 1.7.4 
linter-ui-default 1.2.3 
minimap 4.28.1 
minimap-pigments 0.2.2 
monokai-seti 0.7.0 
pigments 0.39.1 
react 0.16.2 
seti-ui 1.7.0 
```

**Comment by Arcanemagus** [comment]
Can you try re-installing the package? My only guess is that one of the dependencies was corrupted when you installed it.

**Comment by Arcanemagus** [comment]
Closing due to a lack of response. If you are still having issues please follow the steps above.
