### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by shipstar** [AtomLinter/linter-eslint#92]
(Not sure if this is a linter-eslint error or just an eslint error, but Atom recommended posting here.)

Whenever I open a JSX file, Atom locks up for about 30s then presents me with the following stacktrace:

    Uncaught RangeError: Maximum call stack size exceeded
    /Users/kshipley/Programming/healthpro/rms/client/node_modules/eslint/node_modules/escope/lib/reference.js:0
    Hide Stack Trace
    RangeError: Maximum call stack size exceeded
      at new Reference (/Users/kshipley/Programming/healthpro/rms/client/node_modules/eslint/node_modules/escope/lib/reference.js:null:null)
      at FunctionScope.__referencing (/Users/kshipley/Programming/healthpro/rms/client/node_modules/eslint/node_modules/escope/lib/scope.js:383:27)
      at Referencer.Identifier (/Users/kshipley/Programming/healthpro/rms/client/node_modules/eslint/node_modules/escope/lib/referencer.js:545:37)
      at Referencer.Visitor.visit (/Users/kshipley/Programming/healthpro/rms/client/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:109:34)
      at Referencer.MemberExpression (/Users/kshipley/Programming/healthpro/rms/client/node_modules/eslint/node_modules/escope/lib/referencer.js:559:22)
      at Referencer.Visitor.visit (/Users/kshipley/Programming/healthpro/rms/client/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:109:34)
      at Referencer.Visitor.visitChildren (/Users/kshipley/Programming/healthpro/rms/client/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:93:26)
      at Referencer.Visitor.visit (/Users/kshipley/Programming/healthpro/rms/client/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:112:14)
      at Referencer.Visitor.visitChildren (/Users/kshipley/Programming/healthpro/rms/client/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:93:26)
      at Referencer.Visitor.visit (/Users/kshipley/Programming/healthpro/rms/client/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:112:14)
      at Referencer.Visitor.visitChildren (/Users/kshipley/Programming/healthpro/rms/client/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:93:26)
      at Referencer.Visitor.visit (/Users/kshipley/Programming/healthpro/rms/client/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:112:14)
      at Referencer.Visitor.visitChildren (/Users/kshipley/Programming/healthpro/rms/client/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:88:38)
      at Referencer.Visitor.visit (/Users/kshipley/Programming/healthpro/rms/client/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:112:14)
      ... same 4 lines repeated hundreds of times
      at Referencer.Visitor.visitChildren (/Users/kshipley/Programming/healthpro/rms/client/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:93:26)
      at Referencer.Visitor.visit (/Users/kshipley/Programming/healthpro/rms/client/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:112:14)
      at Referencer.Visitor.visitChildren (/Users/kshipley/Programming/healthpro/rms/client/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:93:26)
      at Referencer.Visitor.visit (/Users/kshipley/Programming/healthpro/rms/client/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:112:14)
      at Referencer.Visitor.visitChildren (/Users/kshipley/Programming/healthpro/rms/client/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:88:38)
      at Referencer.visitFunction (/Users/kshipley/Programming/healthpro/rms/client/node_modules/eslint/node_modules/escope/lib/referencer.js:383:26)
      at Referencer.referencer.visitFunction (/Users/kshipley/Programming/healthpro/rms/client/node_modules/babel-eslint/index.js:227:19)
      at Referencer.ArrowFunctionExpression (/Users/kshipley/Programming/healthpro/rms/client/node_modules/eslint/node_modules/escope/lib/referencer.js:704:22)
      at Referencer.Visitor.visit (/Users/kshipley/Programming/healthpro/rms/client/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:109:34)
      at Referencer.Visitor.visitChildren (/Users/kshipley/Programming/healthpro/rms/client/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:88:38)
      at Referencer.CallExpression (/Users/kshipley/Programming/healthpro/rms/client/node_modules/eslint/node_modules/escope/lib/referencer.js:619:22)
      at Referencer.Visitor.visit (/Users/kshipley/Programming/healthpro/rms/client/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:109:34)
      at Referencer.Visitor.visitChildren (/Users/kshipley/Programming/healthpro/rms/client/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:93:26)
      at Referencer.Visitor.visit (/Users/kshipley/Programming/healthpro/rms/client/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:112:14)
      at Referencer.Visitor.visitChildren (/Users/kshipley/Programming/healthpro/rms/client/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:88:38)
      at Referencer.visitFunction (/Users/kshipley/Programming/healthpro/rms/client/node_modules/eslint/node_modules/escope/lib/referencer.js:383:26)
      at Referencer.referencer.visitFunction (/Users/kshipley/Programming/healthpro/rms/client/node_modules/babel-eslint/index.js:227:19)
      at Referencer.FunctionExpression (/Users/kshipley/Programming/healthpro/rms/client/node_modules/eslint/node_modules/escope/lib/referencer.js:689:22)
      at Referencer.Visitor.visit (/Users/kshipley/Programming/healthpro/rms/client/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:109:34)
      at Referencer.visitProperty (/Users/kshipley/Programming/healthpro/rms/client/node_modules/eslint/node_modules/escope/lib/referencer.js:421:22)
      at Referencer.referencer.visitProperty (/Users/kshipley/Programming/healthpro/rms/client/node_modules/babel-eslint/index.js:205:19)
      at Referencer.Property (/Users/kshipley/Programming/healthpro/rms/client/node_modules/eslint/node_modules/escope/lib/referencer.js:567:22)
      at Referencer.Visitor.visit (/Users/kshipley/Programming/healthpro/rms/client/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:109:34)
      at Referencer.Visitor.visitChildren (/Users/kshipley/Programming/healthpro/rms/client/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:88:38)
      at Referencer.Visitor.visit (/Users/kshipley/Programming/healthpro/rms/client/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:112:14)
      at Referencer.Visitor.visitChildren (/Users/kshipley/Programming/healthpro/rms/client/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:88:38)
      at Referencer.CallExpression (/Users/kshipley/Programming/healthpro/rms/client/node_modules/eslint/node_modules/escope/lib/referencer.js:619:22)
      at Referencer.Visitor.visit (/Users/kshipley/Programming/healthpro/rms/client/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:109:34)
      at Referencer.VariableDeclaration (/Users/kshipley/Programming/healthpro/rms/client/node_modules/eslint/node_modules/escope/lib/referencer.js:657:30)
      at Referencer.referencer.VariableDeclaration (/Users/kshipley/Programming/healthpro/rms/client/node_modules/babel-eslint/index.js:238:25)
      at Referencer.Visitor.visit (/Users/kshipley/Programming/healthpro/rms/client/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:109:34)
      at Referencer.Visitor.visitChildren (/Users/kshipley/Programming/healthpro/rms/client/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:88:38)
      at Referencer.Program (/Users/kshipley/Programming/healthpro/rms/client/node_modules/eslint/node_modules/escope/lib/referencer.js:539:22)
      at Referencer.Visitor.visit (/Users/kshipley/Programming/healthpro/rms/client/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:109:34)
      at Object.analyze (/Users/kshipley/Programming/healthpro/rms/client/node_modules/eslint/node_modules/escope/lib/index.js:130:16)
      at Object.escope.analyze (/Users/kshipley/Programming/healthpro/rms/client/node_modules/babel-eslint/index.js:50:27)
      at EventEmitter.module.exports.api.verify (/Users/kshipley/Programming/healthpro/rms/client/node_modules/eslint/lib/eslint.js:663:35)
      at /Users/kshipley/.dotfiles/atom.symlink/packages/linter-eslint/lib/linter-eslint.coffee:129:25
      at exports.allowUnsafeNewFunction (/Users/kshipley/.dotfiles/atom.symlink/packages/linter-eslint/node_modules/loophole/lib/loophole.js:25:14)
      at LinterESLint.lintFile (/Users/kshipley/.dotfiles/atom.symlink/packages/linter-eslint/lib/linter-eslint.coffee:128:7)
      at /Users/kshipley/.dotfiles/atom.symlink/packages/linter/lib/linter-view.coffee:163:18
      at Array.forEach (native)
      at /Users/kshipley/.dotfiles/atom.symlink/packages/linter/lib/linter-view.coffee:162:18
      at FSReqWrap.oncomplete (fs.js:77:15)
    The error was thrown from the linter-eslint package. You can help by creating an issue. Please explain what actions triggered this error.
    Create issue on the linter-eslint package 

I have the community packages installed:

    atom-beautify @ 0.27.12
    linter @ 0.12.6
    linter-eslint @ 0.5.8
    react @ 0.12.0
    term2 @ 0.9.8
    toggle-quotes @ 0.11.0
    vim-mode @ 0.51.0

And the following npm packages that seem relevant:

    babel-eslint @ 3.1.9
    eslint @ 0.22.1
    eslint-plugin-react @ 2.4.0

I upgraded many of these early last week, but used Atom for several days after that with no issues. I updated Atom from 0.205.0 to 0.207.0 late Friday, so it could be related to that.

I'll take a crack at debugging when I can, but wanted to see if anyone else was experiencing this issue.

**Comment by shipstar** [comment]
It looks like this was happening in my command line eslint as well. Upgrading from 0.22.1 to 0.23.0 solved the problem. Closing!
