### ISSUE TITLE
Project config not respected in v8.2.0

### ISSUE THREAD

**Issue by sergey-smolin** [AtomLinter/linter-eslint#923]
## Issue Type

Bug

## Issue Description

When using atom's eslint on MacOS, I get this type of error in the developer console. Also the linter is working very slowly and some of the detected errors are not actually errors. This started about 2 days ago from the day of this positing. I think I did an update of eslint for atom at that time.

Edit: I added Linter Eslint: Debug output below
## Bug Checklist
- Restart Atom
- Verify the `eslint` CLI gives the proper result, while `linter-eslint` does not
- Paste the output of the `Linter Eslint: Debug` command from the Command Palette below

```
helpers.js:58 Error: channel closed
    at ChildProcess.target.send (internal/child_process.js:540:16)
    at Task.module.exports.Task.send (/Applications/Atom.app/Contents/Resources/app/src/task.js:119:1)
    at /Users/myusername/.atom/packages/linter-eslint/helpers.js:56:14
    at /Users/myusername/.atom/packages/linter-eslint/helpers.js:41:10
    at next (<anonymous>)
    at step (/Users/myusername/.atom/packages/linter-eslint/helpers.js:9:1)
    at /Users/myusername/.atom/packages/linter-eslint/helpers.js:9:1
    at /Users/myusername/.atom/packages/linter-eslint/helpers.js:9:1
    at sendJob (/Users/myusername/.atom/packages/linter-eslint/src/helpers.js:47:17)
    at /Users/myusername/.atom/packages/linter-eslint/helpers.js:112:28
    at next (<anonymous>)
    at step (/Users/myusername/.atom/packages/linter-eslint/helpers.js:9:1)
    at /Users/myusername/.atom/packages/linter-eslint/helpers.js:9:1
    at /Users/myusername/.atom/packages/linter-eslint/helpers.js:9:1
    at getDebugInfo (/Users/myusername/.atom/packages/linter-eslint/src/helpers.js:101:18)
    at Object.<anonymous> (/Users/myusername/.atom/packages/linter-eslint/helpers.js:136:23)
    at next (<anonymous>)
    at step (/Users/myusername/.atom/packages/linter-eslint/helpers.js:9:1)
    at /Users/myusername/.atom/packages/linter-eslint/helpers.js:9:1
    at Object.<anonymous> (/Users/myusername/.atom/packages/linter-eslint/helpers.js:9:1)
    at Object.generateDebugString (/Users/myusername/.atom/packages/linter-eslint/src/helpers.js:113:18)
    at atom-text-editor.<anonymous> (/Users/myusername/.atom/packages/linter-eslint/main.js:103:43)
    at next (<anonymous>)
    at step (/Users/myusername/.atom/packages/linter-eslint/main.js:4:1)
    at /Users/myusername/.atom/packages/linter-eslint/main.js:4:1
    at atom-text-editor.<anonymous> (/Users/myusername/.atom/packages/linter-eslint/main.js:4:1)
    at atom-text-editor.linterEslintDebug (/Users/myusername/.atom/packages/linter-eslint/main.js:96:7)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:1)
    at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:1
    at Object.didConfirmSelection (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/lib/command-palette-view.js:106:1)
    at SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-select-list/src/select-list-view.js:313:1)
    at SelectListView.didClickItem (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-select-list/src/select-list-view.js:228:1)
    at ListItemView.onclick (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-select-list/src/select-list-view.js:168:1)
    at ListItemView.didClick (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-select-list/src/select-list-view.js:361:1)
```

**Comment by IanVS** [comment]
You can run `Linter Eslint: Debug` in the atom command palette, which you can open with `cmd+shift+p`.  It will give us details about your configuration and installed versions.

**Comment by Arcanemagus** [comment]
The error in the title has nothing to do with this package, you can find it in a stock Atom install.

> Also the linter is working very slowly and some of the detected errors are not actually errors.

You'll have to be a _bit_ more specific if we are going to track any of that down 😛. Can you share some example code + configuration that produces these "not actually errors"?

**Comment by nielsvanmidden** [comment]
I have exactly the same issue since a couple of days. Same error.

**Comment by Micr** [comment]
> You'll have to be a bit more specific if we are going to track any of that down 😛. Can you share some example code + configuration that produces these "not actually errors"?

For example it used to respect configuration of webpack's resolve.modules. And now it shows those as unresolved imports. for example
`modules: [path.resolve(__dirname, "src"), "node_modules"]`
then imports like
`import something from 'somewhere';` where 'somewhere' is located inside 'src'
get labelled as errors. It wasn't like that before.
Also now it seems like eslint is completely hung up loading and not detecting any lint errors, without even detecting erorrs.(thats why I cant copy/paste the exact lint error message. Maybe later I will be able to add it here).

**Comment by IanVS** [comment]
If you're not able to run the debug command, what version of Atom and linter-eslint are you using?

**Comment by modosc** [comment]
i'm seeing this too - using atom 1.18.0-beta, linter-eslint 8.2.1, and eslint-3.19.0. it appears as though it's not loading up my `.eslintrc.js` file, even though it's specified in the package settings. things work fine from the command line.

also also at some point the linter plugin will crash and i get a repeated error in the developer tools about `channel being closed` - of course i'm unable to make it happen exactly at this point, when i can i'll update with the trace.

**Comment by modosc** [comment]
also i just verified the breakage happened between `8.1.7` and `8.2.0`.

**Comment by IanVS** [comment]
For those of you on atom 1.18.0-beta, can you check if you have the `pigments` package installed?  I was noticing out-of-memory errors myself, and disabling `pigments` solved it for me.  https://github.com/abe33/atom-pigments/issues/308 is the issue over there.

**Comment by Arcanemagus** [comment]
@Micr are you able to share a minimal case to reproduce your issues?

**Comment by Arcanemagus** [comment]
@modosc The same request for a way to reproduce this applies to you as well, neither of us have seen this issue or are able to reproduce it so without somebody's help in figuring out what is different about your setups this will never get fixed.

**Comment by modosc** [comment]
@Arcanemagus here you go:

https://github.com/modosc/linter-eslint-bug

**Comment by Arcanemagus** [comment]
@modosc Thanks! I was able to reproduce with that, looking into it.

**Comment by modosc** [comment]
any update here (or anything else i can help with)?

**Comment by modosc** [comment]
ping? stil happening as of `linter-eslint@8.3.2`

**Comment by UziTech** [comment]
Is this still an issue?
