### ISSUE TITLE
8.2.1: Error: Cannot assign to read only property '.js' of object '#<Object>'

### ISSUE THREAD

**Issue by leebenson** [AtomLinter/linter-eslint#926]
## Issue Type
Bug - see https://github.com/reactql/kit/issues/24

## Issue Description
Bumping from 8.1.7 -> 8.2.1 introduced [this error](https://github.com/reactql/kit/issues/24).

```
Cannot read config file: /Users/leebenson/dev/github/reactql/kit/.eslintrc.js
Error: Cannot assign to read only property '.js' of object '#<Object>' TypeError: Cannot read config file: /Users/leebenson/dev/github/reactql/kit/.eslintrc.js
Error: Cannot assign to read only property '.js' of object '#<Object>'
```

Here's a [link to the .eslintrc.js config file](https://github.com/reactql/kit/blob/master/.eslintrc.js) being used, copied below:

```js
require('babel-register');
const path = require('path');
const baseRules = require('eslint-config-airbnb-base/rules/style');
const [_, ...restricted] = baseRules.rules['no-restricted-syntax'];

const PATHS = require('./config/paths');

module.exports = {
  extends: 'airbnb',
  parser: 'babel-eslint',
  parserOptions: {
    ecmaVersion: 2017,
    sourceType: 'module',
    jsx: true,
  },
  env: {
    node: true,
    browser: true,
  },
  plugins: [
    'babel',
    'import',
    'jsx-a11y',
    'compat',
  ],
  rules: {
    'arrow-parens': ['error', 'as-needed'],
    'react/forbid-prop-types': [1, { forbid: ['any']} ],
    'no-plusplus': ['error', { allowForLoopAfterthoughts: true }],
    'react/prefer-stateless-function': [2, { ignorePureComponents: true }],
    'react/no-multi-comp': 0,
    'react/jsx-closing-bracket-location': [1, 'after-props'],
    'linebreak-style': 0,
    'react/jsx-filename-extension': [1, { extensions: ['.js', '.jsx'] }],
    'no-restricted-syntax': [2,
      ...restricted.filter(
        r => !['ForOfStatement'].includes(r.selector)
      ),
    ],
    'global-require': 0,
    'import/no-unresolved': [2, { commonjs: true }],
    'compat/compat': 2
  },
  settings: {
    'import/resolver': {
      webpack: {
        config: path.join(PATHS.webpack, 'eslint.js'),
      },
      polyfills: ['fetch'],
    }
  },
  globals: {
    SERVER: false,
  },
};
```

Notes:

1. The config above is part of a [starter kit](https://github.com/reactql/kit) that has separate Babel loaders and a relatively comprehensive Webpack build flow that this config file included. To test, clone the repo or run `npm i -g reactql` then `reactql new` to start a new project based off of it.

2. The webpack flow builds both a Node.js compatible and browser compatible bundle; because of this, there are multiple Babel configurations in play, including a root config to [kick-start](https://github.com/reactql/kit/blob/master/.babelrc) the initial linting/Webpack.

3. Removing the `babel-register` statement kills the `Cannot assign to read only property '.js' of object '#<Object>'` error, but then introduces `Resolve error: Unexpected token import` in every file.

4. Further commenting out `parser: 'babel-eslint'` also prevents the error, but then introduces linting errors on invalid ES6 such as `@decorator` syntax, or imports that are relevant to to paths specified in the Webpack config that's loaded.

## Bug Checklist
- Restart Atom
- Verify the `eslint` CLI gives the proper result, while `linter-eslint` does not
- Paste the output of the `Linter Eslint: Debug` command from the Command Palette below

Note: `Linter Eslint: Debug` isn't available in the command palette, so I've included the full dump of the console error below:

```
<embedded>:69958 Cannot read config file: /Users/leebenson/dev/github/reactql/kit/.eslintrc.js
Error: Cannot assign to read only property '.js' of object '#<Object>' TypeError: Cannot read config file: /Users/leebenson/dev/github/reactql/kit/.eslintrc.js
Error: Cannot assign to read only property '.js' of object '#<Object>'
    at registerExtension (/Users/leebenson/dev/github/reactql/kit/node_modules/babel-register/lib/node.js:150:27)
    at /Users/leebenson/dev/github/reactql/kit/node_modules/babel-register/lib/node.js:173:5
    at Array.forEach (native)
    at hookExtensions (/Users/leebenson/dev/github/reactql/kit/node_modules/babel-register/lib/node.js:171:9)
    at Object.<anonymous> (/Users/leebenson/dev/github/reactql/kit/node_modules/babel-register/lib/node.js:177:1)
    at Module._compile (module.js:556:32)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:225:23)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/leebenson/dev/github/reactql/kit/.eslintrc.js:1:18)
    at Module._compile (module.js:556:32)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:225:23)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at module.exports (/Users/leebenson/dev/github/reactql/kit/node_modules/require-uncached/index.js:28:9)
    at loadJSConfigFile (/Users/leebenson/dev/github/reactql/kit/node_modules/eslint/lib/config/config-file.js:160:16)
    at loadConfigFile (/Users/leebenson/dev/github/reactql/kit/node_modules/eslint/lib/config/config-file.js:215:22)
    at Object.load (/Users/leebenson/dev/github/reactql/kit/node_modules/eslint/lib/config/config-file.js:535:18)
    at loadConfig (/Users/leebenson/dev/github/reactql/kit/node_modules/eslint/lib/config.js:63:33)
    at getLocalConfig (/Users/leebenson/dev/github/reactql/kit/node_modules/eslint/lib/config.js:130:29)
    at Config.getConfig (/Users/leebenson/dev/github/reactql/kit/node_modules/eslint/lib/config.js:260:26)
    at processText (/Users/leebenson/dev/github/reactql/kit/node_modules/eslint/lib/cli-engine.js:224:33)
    at CLIEngine.executeOnText (/Users/leebenson/dev/github/reactql/kit/node_modules/eslint/lib/cli-engine.js:754:26)
    at lintJob (/Users/leebenson/.atom/packages/linter-eslint/src/worker.js:34:20)(anonymous function) @ <embedded>:69958
/Users/leebenson/.atom/packages/linter/lib/linter-registry.js:159 [Linter] Error running ESLint Error: Cannot read config file: /Users/leebenson/dev/github/reactql/kit/.eslintrc.js(…)(anonymous function) @ /Users/leebenson/.atom/packages/linter/lib/linter-registry.js:159
/Users/leebenson/.atom/packages/linter/lib/linter-registry.js:159 [Linter] Error running ESLint Error: Cannot read config file: /Users/leebenson/dev/github/reactql/kit/.eslintrc.js(…)(anonymous function) @ /Users/leebenson/.atom/packages/linter/lib/linter-registry.js:159
<embedded>:69958 Cannot read config file: /Users/leebenson/dev/github/reactql/kit/.eslintrc.js
Error: Cannot assign to read only property '.js' of object '#<Object>' TypeError: Cannot read config file: /Users/leebenson/dev/github/reactql/kit/.eslintrc.js
Error: Cannot assign to read only property '.js' of object '#<Object>'
    at registerExtension (/Users/leebenson/dev/github/reactql/kit/node_modules/babel-register/lib/node.js:150:27)
    at /Users/leebenson/dev/github/reactql/kit/node_modules/babel-register/lib/node.js:173:5
    at Array.forEach (native)
    at hookExtensions (/Users/leebenson/dev/github/reactql/kit/node_modules/babel-register/lib/node.js:171:9)
    at Object.<anonymous> (/Users/leebenson/dev/github/reactql/kit/node_modules/babel-register/lib/node.js:177:1)
    at Module._compile (module.js:556:32)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:225:23)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/leebenson/dev/github/reactql/kit/.eslintrc.js:1:18)
    at Module._compile (module.js:556:32)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:225:23)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at module.exports (/Users/leebenson/dev/github/reactql/kit/node_modules/require-uncached/index.js:28:9)
    at loadJSConfigFile (/Users/leebenson/dev/github/reactql/kit/node_modules/eslint/lib/config/config-file.js:160:16)
    at loadConfigFile (/Users/leebenson/dev/github/reactql/kit/node_modules/eslint/lib/config/config-file.js:215:22)
    at Object.load (/Users/leebenson/dev/github/reactql/kit/node_modules/eslint/lib/config/config-file.js:535:18)
    at loadConfig (/Users/leebenson/dev/github/reactql/kit/node_modules/eslint/lib/config.js:63:33)
    at getLocalConfig (/Users/leebenson/dev/github/reactql/kit/node_modules/eslint/lib/config.js:130:29)
    at Config.getConfig (/Users/leebenson/dev/github/reactql/kit/node_modules/eslint/lib/config.js:260:26)
    at processText (/Users/leebenson/dev/github/reactql/kit/node_modules/eslint/lib/cli-engine.js:224:33)
    at CLIEngine.executeOnText (/Users/leebenson/dev/github/reactql/kit/node_modules/eslint/lib/cli-engine.js:754:26)
    at lintJob (/Users/leebenson/.atom/packages/linter-eslint/src/worker.js:14:20)(anonymous function) @ <embedded>:69958
/Users/leebenson/.atom/packages/linter/lib/linter-registry.js:159 [Linter] Error running ESLint Error: Cannot read config file: /Users/leebenson/dev/github/reactql/kit/.eslintrc.js(…)(anonymous function) @ /Users/leebenson/.atom/packages/linter/lib/linter-registry.js:159
<embedded>:69958 Cannot read config file: /Users/leebenson/dev/github/reactql/kit/.eslintrc.js
Error: Cannot assign to read only property '.js' of object '#<Object>' TypeError: Cannot read config file: /Users/leebenson/dev/github/reactql/kit/.eslintrc.js
Error: Cannot assign to read only property '.js' of object '#<Object>'
    at registerExtension (/Users/leebenson/dev/github/reactql/kit/node_modules/babel-register/lib/node.js:150:27)
    at /Users/leebenson/dev/github/reactql/kit/node_modules/babel-register/lib/node.js:173:5
    at Array.forEach (native)
    at hookExtensions (/Users/leebenson/dev/github/reactql/kit/node_modules/babel-register/lib/node.js:171:9)
    at Object.<anonymous> (/Users/leebenson/dev/github/reactql/kit/node_modules/babel-register/lib/node.js:177:1)
    at Module._compile (module.js:556:32)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:225:23)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/leebenson/dev/github/reactql/kit/.eslintrc.js:1:18)
    at Module._compile (module.js:556:32)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:225:23)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at module.exports (/Users/leebenson/dev/github/reactql/kit/node_modules/require-uncached/index.js:28:9)
    at loadJSConfigFile (/Users/leebenson/dev/github/reactql/kit/node_modules/eslint/lib/config/config-file.js:160:16)
    at loadConfigFile (/Users/leebenson/dev/github/reactql/kit/node_modules/eslint/lib/config/config-file.js:215:22)
    at Object.load (/Users/leebenson/dev/github/reactql/kit/node_modules/eslint/lib/config/config-file.js:535:18)
    at loadConfig (/Users/leebenson/dev/github/reactql/kit/node_modules/eslint/lib/config.js:63:33)
    at getLocalConfig (/Users/leebenson/dev/github/reactql/kit/node_modules/eslint/lib/config.js:130:29)
    at Config.getConfig (/Users/leebenson/dev/github/reactql/kit/node_modules/eslint/lib/config.js:260:26)
    at processText (/Users/leebenson/dev/github/reactql/kit/node_modules/eslint/lib/cli-engine.js:224:33)
    at CLIEngine.executeOnText (/Users/leebenson/dev/github/reactql/kit/node_modules/eslint/lib/cli-engine.js:754:26)
    at lintJob (/Users/leebenson/.atom/packages/linter-eslint/src/worker.js:14:20)
```

**Comment by leebenson** [comment]
Update: I was able to fix this by replacing the Webpack resolver with module paths, and removing `babel-register` entirely:

```js
const path = require('path');
const baseRules = require('eslint-config-airbnb-base/rules/style');
const [_, ...restricted] = baseRules.rules['no-restricted-syntax'];

const PATHS = require('./config/paths');

module.exports = {
  extends: 'airbnb',
  parser: 'babel-eslint',
  parserOptions: {
    ecmaVersion: 2017,
    sourceType: 'module',
    jsx: true,
  },
  env: {
    node: true,
    browser: true,
  },
  plugins: [
    'babel',
    'import',
    'jsx-a11y',
    'compat',
  ],
  rules: {
    'arrow-parens': ['error', 'as-needed'],
    'react/forbid-prop-types': [1, { forbid: ['any']} ],
    'no-plusplus': ['error', { allowForLoopAfterthoughts: true }],
    'react/prefer-stateless-function': [2, { ignorePureComponents: true }],
    'react/no-multi-comp': 0,
    'react/jsx-closing-bracket-location': [1, 'after-props'],
    'linebreak-style': 0,
    'react/jsx-filename-extension': [1, { extensions: ['.js', '.jsx'] }],
    'no-restricted-syntax': [2,
      ...restricted.filter(
        r => !['ForOfStatement'].includes(r.selector)
      ),
    ],
    'global-require': 0,
    'import/no-unresolved': [2, { commonjs: true }],
    'compat/compat': 2
  },
  settings: {
    'import/resolver': {
      node: {
        paths: [
          PATHS.root,
          'node_modules',
        ],
      },
    },
  },
  globals: {
    SERVER: false,
  },
};
```

However, I think it's still worth keeping this issue open because there's a difference between how this plugin runs eslint, and running `eslint` from the CLI directly when `babel-register` is present.

**Comment by IanVS** [comment]
This is definitely something we should look into. For starters, do you have an `.eslintignore` file anywhere in your project structure?

**Comment by leebenson** [comment]
Sure, `.eslintignore` is just:

```
node_modules
dist
```

**Comment by IanVS** [comment]
And it is at your project root directory?

**Comment by skylize** [comment]
@leebenson Any chance you could widdle this down to a minimal repro? At the least, please link to a specific commit where this error occurs, instead of to master branch latest commit, where you already have workarounds in place.

**Comment by Arcanemagus** [comment]
Here's the linked repo at the time the original comment was made: [reactql/kit@~2017-05-26](https://github.com/reactql/kit/blob/f67b564cc2058e3467f8b50f38e73fe482c9b8ba/.eslintrc.js)

**Comment by UziTech** [comment]
Is this still an issue?
