### ISSUE TITLE
error if used rule "indent" with option "flatTernaryExpressions"

### ISSUE THREAD

**Issue by boggddan** [AtomLinter/linter-eslint#942]
I used `Windows 10 x64`, `Atom 1.18.0 x64`, `Liner: 2.2.0`

Sample:
```js
/*eslint indent: ["error", 4, { "flatTernaryExpressions": true }]*/

var a = foo
  ? bar : baz
    ? qux : boop;
```

Console:
```
<embedded>:70798 D:\ProjectRuby\table_test\src\js\test.js line 3:
	Configuration for rule "indent" is invalid:
	Value "data["1"].flatTernaryExpressions" has additional properties.
 Error: D:\ProjectRuby\table_test\src\js\test.js line 3:
	Configuration for rule "indent" is invalid:
	Value "data["1"].flatTernaryExpressions" has additional properties.

    at Object.validateRuleOptions (C:\Users\User\.atom\packages\linter-eslint\node_modules\eslint\lib\config\config-validator.js:109:15)
    at Object.keys.forEach.name (C:\Users\User\.atom\packages\linter-eslint\node_modules\eslint\lib\eslint.js:368:39)
    at Array.forEach (native)
    at ast.comments.forEach.comment (C:\Users\User\.atom\packages\linter-eslint\node_modules\eslint\lib\eslint.js:365:44)
    at Array.forEach (native)
    at modifyConfigsFromComments (C:\Users\User\.atom\packages\linter-eslint\node_modules\eslint\lib\eslint.js:331:18)
    at EventEmitter.module.exports.api.verify (C:\Users\User\.atom\packages\linter-eslint\node_modules\eslint\lib\eslint.js:834:26)
    at processText (C:\Users\User\.atom\packages\linter-eslint\node_modules\eslint\lib\cli-engine.js:264:31)
    at CLIEngine.executeOnText (C:\Users\User\.atom\packages\linter-eslint\node_modules\eslint\lib\cli-engine.js:754:26)
    at lintJob (file:///C:/Users/User/.atom/packages/linter-eslint/src/worker.js:14:20)
    at process.<anonymous> (file:///C:/Users/User/.atom/packages/linter-eslint/src/worker.js:52:22)
    at emitTwo (events.js:111:20)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

An error message is displayed only in the Atom
not errors when used eslint in the console 

```bash
eslint src/js/test.js

D:\ProjectRuby\table_test\src\js\test.js
  5:5  error  'a' is assigned a value but never used  no-unused-vars

✖ 1 problem (1 error, 0 warnings)
```

In the Atom
![2017-06-19_09h33_20](https://user-images.githubusercontent.com/24915025/27272346-70df2138-54d2-11e7-8e7a-f5f3514130a5.png)

**Comment by IanVS** [comment]
Can you please provide the output of `Linter ESLint: debug` from the command palette?  It looks like you might have an eslint version mismatch.

**Comment by Arcanemagus** [comment]
Closing due to a lack of response.
