### ISSUE TITLE
something wrong in atom 1.8.0

### ISSUE THREAD

**Issue by zhangwilling** [AtomLinter/linter-eslint#945]
## Issue Description

macos
atom 18.0
eslint error

## Bug Checklist
- Restart Atom
- Verify the `eslint` CLI gives the proper result, while `linter-eslint` does not

## Error Detail
```
atom error log:
[2017-06-21T02:45:38.473Z] [ERROR] atom-ide-diagnostics - Error in linter provider ESLint: Cannot find module 'circular-json'
Error: Cannot find module 'circular-json'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/willing/develop/app/captain-ios/node_modules/flat-cache/utils.js:3:20)
    at Module._compile (module.js:556:32)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:234:23)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/willing/develop/app/captain-ios/node_modules/flat-cache/cache.js:4:13)
    at Module._compile (module.js:556:32)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:234:23)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.create (/Users/willing/develop/app/captain-ios/node_modules/file-entry-cache/cache.js:12:21)
    at new CLIEngine (/Users/willing/develop/app/captain-ios/node_modules/eslint/lib/cli-engine.js:463:38)
    at lintJob (/Users/willing/.atom/packages/linter-eslint/src/worker.js:13:21)
    at process.<anonymous> (/Users/willing/.atom/packages/linter-eslint/src/worker.js:52:22)
    at emitTwo (events.js:111:20)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by IanVS** [comment]
It looks like it can't find a dependency of eslint.  Have you restarted Atom and if that fails, tried reinstalling your node_modules?

**Comment by IanVS** [comment]
I'm going to close this in hopes that it's working for you now, but please let us know if you're still having trouble.

**Comment by zhangwilling** [comment]
thx, i did nothing,but  everything was right.Any way ,thank u
