### ISSUE TITLE
Uncaught Error: Cannot find module './worker.js'

### ISSUE THREAD

**Issue by huffdesign** [AtomLinter/linter-eslint#946]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [linter-eslint](https://github.com/AtomLinter/linter-eslint) package 8.2.1

### Stack Trace

Uncaught Error: Cannot find module './worker.js'

```
At module.js:457

Error: Cannot find module './worker.js'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Function.require.resolve (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:69:35)
    at initializeESLintWorker (/packages/linter-eslint/src/main.js:154:44)
```

### Commands

```
     -1:18.6.0 core:backspace (input.hidden-input)
     -0:59.7.0 core:save (a.stack-toggle)
```

### Non-Core Packages

```
busy-signal 1.4.3 
editorconfig 2.2.2 
intentions 1.1.2 
lint 0.0.1 
linter 2.2.0 
linter-eslint 8.2.1 
linter-ui-default 1.6.2 
react 0.16.2 
```

**Comment by IanVS** [comment]
@huffdesign, have you restarted Atom lately?  If that doesn't work, try uninstalling and re-installing `linter-eslint`.

**Comment by IanVS** [comment]
Closing due to lack of response.  If you're still having problems, @huffdesign, please let us know.
