### ISSUE TITLE
Uncaught Error: Definition for rule 'object-curly-spacing' was not found.

### ISSUE THREAD

**Issue by preco21** [AtomLinter/linter-eslint#95]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.208.0
**System**: Unknown Windows Version
**Thrown From**: [linter-eslint](https://github.com/AtomLinter/linter-eslint) package, v0.5.8

### Stack Trace

Uncaught Error: Definition for rule 'object-curly-spacing' was not found.

```
At C:\Users\Preco\.atom\packages\linter-eslint\node_modules\eslint\lib\eslint.js:647

Error: Definition for rule 'object-curly-spacing' was not found.
  at C:\Users\Preco\.atom\packages\linter-eslint\node_modules\eslint\lib\eslint.js:647:27
  at Array.forEach (native)
  at EventEmitter.module.exports.api.verify (C:\Users\Preco\.atom\packages\linter-eslint\node_modules\eslint\lib\eslint.js:620:16)
  at C:\Users\Preco\.atom\packages\linter-eslint\lib\linter-eslint.coffee:129:25
  at exports.allowUnsafeNewFunction (C:\Users\Preco\.atom\packages\linter-eslint\node_modules\loophole\lib\loophole.js:25:14)
  at LinterESLint.lintFile (C:\Users\Preco\.atom\packages\linter-eslint\lib\linter-eslint.coffee:128:7)
  at C:\Users\Preco\.atom\packages\linter\lib\linter-view.coffee:163:18
  at Array.forEach (native)
  at C:\Users\Preco\.atom\packages\linter\lib\linter-view.coffee:162:18
  at FSReqWrap.oncomplete (fs.js:77:15)

```

### Commands

```
     -3:07.1.0 editor:newline (atom-text-editor.editor.is-focused)
     -3:06.5.0 core:paste (atom-text-editor.editor.is-focused)
     -3:04.4.0 core:save (atom-text-editor.editor.is-focused)
     -1:36.7.0 core:paste (atom-text-editor.editor.is-focused)
     -1:35.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:35.2.0 core:save (atom-text-editor.editor.is-focused)
     -1:13.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:12.8.0 core:save (atom-text-editor.editor.is-focused)
     -0:23.1.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:22.6.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:10.8.0 core:undo (atom-text-editor.editor.is-focused)
     -0:09.2.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:09.2.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:08.4.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:08.4.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:06.9.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "run-command",
      "language-javascript-better",
      "react",
      "linter-jshint",
      "linter-jscs"
    ],
    "autoHideMenuBar": true
  },
  "linter-eslint": {}
}
```

### Installed Packages

```coffee
# User
autoclose-html, v0.17.1
autocomplete-paths, v1.0.2
build, v0.37.0
color-picker, v2.0.4
editorconfig, v1.0.0
emmet, v2.3.10
file-icons, v1.5.7
html-entities, v0.4.0
linter, v0.12.7
linter-csslint, v0.0.13
linter-eslint, v0.5.8
linter-htmlhint, v0.0.16
minimap, v4.10.0
terminal-panel, v1.14.1

# Dev
No dev packages
```

**Comment by alanrsoares** [comment]
same problem here after updating eslint

**Comment by iam4x** [comment]
`eslint` has been updated since.
