### ISSUE TITLE
Uncaught TypeError: Cannot read property 'name' of null

### ISSUE THREAD

**Issue by Moeriki** [AtomLinter/linter-eslint#96]
I'm using Array destructuring in my function args like this. I only need the DB result but then linter-eslint crashes. I can easily prevent this by also capturing the first array value. But then I have a lint warning for an unused variable :)

```javascript
    async.series([
        (next) => createS3Object(eventModel, next),
        (next) => insertDB(eventModel, next),
    ], function (err, [, insertResult]) {
        if (err) {
            return callback(err);
        }

        callback(null, insertDoc);
    });
```

**Atom Version**: 0.209.0
**System**: Mac OS X 10.10.4
**Thrown From**: [linter-eslint](https://github.com/AtomLinter/linter-eslint) package, v0.5.8

### Stack Trace

Uncaught TypeError: Cannot read property 'name' of null

```
At /Users/moeriki/.atom/packages/linter-eslint/node_modules/eslint/lib/rules/no-dupe-args.js:60

TypeError: Cannot read property 'name' of null
  at /Users/moeriki/.atom/packages/linter-eslint/node_modules/eslint/lib/rules/no-dupe-args.js:60:42
  at Array.forEach (native)
  at /Users/moeriki/.atom/packages/linter-eslint/node_modules/eslint/lib/rules/no-dupe-args.js:59:36
  at Array.forEach (native)
  at EventEmitter.checkParams (/Users/moeriki/.atom/packages/linter-eslint/node_modules/eslint/lib/rules/no-dupe-args.js:45:21)
  at emitOne (events.js:82:20)
  at EventEmitter.emit (events.js:166:7)
  at Controller.controller.traverse.enter (/Users/moeriki/.atom/packages/linter-eslint/node_modules/eslint/lib/eslint.js:725:25)
  at Controller.__execute (/Users/moeriki/.atom/packages/linter-eslint/node_modules/eslint/node_modules/estraverse/estraverse.js:393:31)
  at Controller.traverse (/Users/moeriki/.atom/packages/linter-eslint/node_modules/eslint/node_modules/estraverse/estraverse.js:491:28)
  at EventEmitter.module.exports.api.verify (/Users/moeriki/.atom/packages/linter-eslint/node_modules/eslint/lib/eslint.js:718:24)
  at /Users/moeriki/.atom/packages/linter-eslint/lib/linter-eslint.coffee:129:25
  at exports.allowUnsafeNewFunction (/Users/moeriki/.atom/packages/linter-eslint/node_modules/loophole/lib/loophole.js:25:14)
  at LinterESLint.lintFile (/Users/moeriki/.atom/packages/linter-eslint/lib/linter-eslint.coffee:128:7)
  at /Users/moeriki/.atom/packages/linter/lib/linter-view.coffee:163:18
  at Array.forEach (native)
  at /Users/moeriki/.atom/packages/linter/lib/linter-view.coffee:162:18
  at FSReqWrap.oncomplete (fs.js:77:15)

```

### Commands

```
     -0:44.4.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:43.5.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:38 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -0:37.7.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:08.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:07.6.0 editor:select-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -0:07.1.0 core:move-right (atom-text-editor.editor.is-focused)
  2x -0:06.7.0 editor:select-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -0:04.8.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:03.6.0 editor:select-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -0:03.3.0 core:copy (atom-text-editor.editor.is-focused)
     -0:03.1.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:02.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:02.6.0 core:save (atom-text-editor.editor.is-focused)
     -0:00.5.0 editor:select-to-end-of-word (atom-text-editor.editor.is-focused)
     -0:00.2.0 core:copy (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-csslint",
      "dev-live-reload",
      "linter-jshint",
      "linter-jscs",
      "tabs-to-spaces",
      "meteor-api",
      "meteor-helper",
      "meteor-snippets",
      "merge-conflicts",
      "language-ejs",
      "language-haml",
      "language-jade",
      "react",
      "project-manager",
      "atom-typescript"
    ],
    "themes": [
      "seti-ui",
      "one-dark-syntax"
    ],
    "excludeVcsIgnoredPaths": false
  },
  "linter-eslint": {
    "disableWhenNoEslintrcFileInPath": true
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
color-picker, v2.0.4
docblockr, v0.7.2
editorconfig, v1.0.0
emmet, v2.3.10
highlight-selected, v0.9.3
language-hjson, v0.2.0
language-spacebars, v0.2.2
linter, v0.12.7
linter-eslint, v0.5.8
linter-jsonlint, v0.1.4
linter-shellcheck, v0.0.8
minimap, v4.10.0
pretty-json, v0.3.3
raml, v0.1.0
seti-ui, v0.7.1

# Dev
No dev packages
```

**Comment by iam4x** [comment]
It's an error thrown by `eslint` it self, they should be caught now and print in console.

Update `eslint` should do the trick.
