### ISSUE TITLE
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

### ISSUE THREAD

**Issue by mking** [AtomLinter/linter-eslint#97]
Steps to reproduce:

1. Clone https://github.com/mking/eslinter. This is a repo with a single source file (./app/app.js) and an .eslintrc file. Do `npm install` (installs eslint, babel-eslint, and eslint-plugin-react).
2. Edit ./app/app.js (in Atom with linter-eslint enabled). This invokes eslint on the file and causes the error to occur.

Command line eslint works fine. The error is probably related to [this commit](https://github.com/eslint/eslint/blob/c6e1d2390e035237225a06ce76e2a92c8363452c/lib/config-validator.js). I'm guessing previous versions of eslint did not try to use eval (well, Function(string)), while the current version of eslint does (through schemaValidator in the file from that commit).

**Atom Version**: 0.209.0
**System**: Mac OS X 10.10.3
**Thrown From**: [linter-eslint](https://github.com/AtomLinter/linter-eslint) package, v0.5.8

### Stack Trace

Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

```
At /Users/matt/eslinter/node_modules/eslint/node_modules/is-my-json-valid/node_modules/generate-function/index.js:55

EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

  at Function (native)
  at Function.line.toFunction (/Users/matt/eslinter/node_modules/eslint/node_modules/is-my-json-valid/node_modules/generate-function/index.js:55:21)
  at compile (/Users/matt/eslinter/node_modules/eslint/node_modules/is-my-json-valid/index.js:539:23)
  at module.exports (/Users/matt/eslinter/node_modules/eslint/node_modules/is-my-json-valid/index.js:560:10)
  at validateRuleOptions (/Users/matt/eslinter/node_modules/eslint/lib/config-validator.js:67:24)
  at /Users/matt/eslinter/node_modules/eslint/lib/config-validator.js:101:13
  at Array.forEach (native)
  at Object.validate (/Users/matt/eslinter/node_modules/eslint/lib/config-validator.js:100:35)
  at loadConfig (/Users/matt/eslinter/node_modules/eslint/lib/config.js:99:19)
  at getLocalConfig (/Users/matt/eslinter/node_modules/eslint/lib/config.js:225:23)
  at Config.getConfig (/Users/matt/eslinter/node_modules/eslint/lib/config.js:363:22)
  at CLIEngine.getConfigForFile (/Users/matt/eslinter/node_modules/eslint/lib/cli-engine.js:382:29)
  at LinterESLint.lintFile (/Users/matt/.atom/packages/linter-eslint/lib/linter-eslint.coffee:79:21)
  at /Users/matt/.atom/packages/linter/lib/linter-view.coffee:163:18
  at Array.forEach (native)
  at /Users/matt/.atom/packages/linter/lib/linter-view.coffee:162:18
  at FSReqWrap.oncomplete (fs.js:77:15)

```

### Commands

```
     -0:00.6.0 core:backspace (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "spell-check"
    ],
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  },
  "linter-eslint": {}
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
atom-ternjs, v0.6.4
atom-typescript, v4.5.13
go-plus, v3.3.11
linter, v0.12.7
linter-eslint, v0.5.8
pigments, v0.7.2
react, v0.12.0

# Dev
No dev packages
```

**Comment by keithamus** [comment]
Progress is happening in #99. This should be closed in favour of #99
