### ISSUE TITLE
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

### ISSUE THREAD

**Issue by alvaromb** [AtomLinter/linter-eslint#99]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.209.0
**System**: Mac OS X 10.10.3
**Thrown From**: [linter-eslint](https://github.com/AtomLinter/linter-eslint) package, v0.5.8

### Stack Trace

Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

```
At /Users/alvaro/apsl/mnm/mnm/node_modules/eslint/node_modules/is-my-json-valid/node_modules/generate-function/index.js:55

EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

  at Function (native)
  at Function.line.toFunction (/Users/alvaro/apsl/mnm/mnm/node_modules/eslint/node_modules/is-my-json-valid/node_modules/generate-function/index.js:55:21)
  at compile (/Users/alvaro/apsl/mnm/mnm/node_modules/eslint/node_modules/is-my-json-valid/index.js:539:23)
  at module.exports (/Users/alvaro/apsl/mnm/mnm/node_modules/eslint/node_modules/is-my-json-valid/index.js:560:10)
  at validateRuleOptions (/Users/alvaro/apsl/mnm/mnm/node_modules/eslint/lib/config-validator.js:67:24)
  at /Users/alvaro/apsl/mnm/mnm/node_modules/eslint/lib/config-validator.js:101:13
  at Array.forEach (native)
  at Object.validate (/Users/alvaro/apsl/mnm/mnm/node_modules/eslint/lib/config-validator.js:100:35)
  at loadConfig (/Users/alvaro/apsl/mnm/mnm/node_modules/eslint/lib/config.js:99:19)
  at getLocalConfig (/Users/alvaro/apsl/mnm/mnm/node_modules/eslint/lib/config.js:225:23)
  at Config.getConfig (/Users/alvaro/apsl/mnm/mnm/node_modules/eslint/lib/config.js:363:22)
  at CLIEngine.getConfigForFile (/Users/alvaro/apsl/mnm/mnm/node_modules/eslint/lib/cli-engine.js:382:29)
  at LinterESLint.lintFile (/Users/alvaro/.atom/packages/linter-eslint/lib/linter-eslint.coffee:79:21)
  at /Users/alvaro/.atom/packages/linter/lib/linter-view.coffee:163:18
  at Array.forEach (native)
  at /Users/alvaro/.atom/packages/linter/lib/linter-view.coffee:162:18
  at FSReqWrap.oncomplete (fs.js:77:15)

```

### Commands

```
     -5:08.5.0 editor:newline (atom-text-editor.editor.is-focused)
     -5:06.4.0 editor:move-to-end-of-line (atom-text-editor.editor.is-focused)
     -5:05.1.0 editor:newline (atom-text-editor.editor.is-focused)
     -4:43.9.0 core:paste (atom-text-editor.editor.is-focused)
     -4:40.4.0 core:move-right (atom-text-editor.editor.is-focused)
  2x -4:38.2.0 core:save (atom-text-editor.editor.is-focused)
     -0:05.0 core:move-right (atom-text-editor.editor.is-focused)
  4x -0:04.7.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:03.8.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "jshint",
      "ide-flow"
    ],
    "themes": [
      "one-dark-ui",
      "oceanic-next"
    ]
  },
  "linter-eslint": {}
}
```

### Installed Packages

```coffee
# User
language-babel, v0.8.0
linter, v0.12.7
linter-eslint, v0.5.8
linter-flow, v0.1.5
oceanic-next, v0.1.1
react, v0.12.0

# Dev
No dev packages
```

**Comment by alvaromb** [comment]
This is happening when I add this to my ``.eslintrc`` file:

```json
"rules": {
    "quotes": [1, "single"]
}
```

**Comment by alvaromb** [comment]
Confirmed that happens when I add any ``"rules"`` into ``.eslintrc`` file.

**Comment by mcasimir** [comment]
Same here, any workaround?

**Comment by mcasimir** [comment]
Duplicate of #100 and #97

**Comment by aruberto** [comment]
The issue occurs for me only when using eslint 0.23.0. The issue disappears when rolling back to eslint 0.22.1. I believe the issue is related to the new rule option validation added in https://github.com/eslint/eslint/issues/2595

Not sure if this is the correct approach to fixing this issue, but I can get eslint 0.23.0 working with linter-eslint by changing

```
config = engine.getConfigForFile(origPath)
```

to

```
config = {}
allowUnsafeNewFunction =>
  config = engine.getConfigForFile(origPath)
```

in linter-eslint.coffee

**Comment by magnus-bergman** [comment]
Seems like this issue is widely spread. A fix would be greatly appreciated!

**Comment by iam4x** [comment]
@aruberto This is the correct fix, could you drop me a PR?

**Comment by alvaromb** [comment]
[v0.5.9](https://github.com/AtomLinter/linter-eslint/releases/tag/v0.5.9) release solves this.

Many thanks!

**Comment by rearadmiral** [comment]
I'm seeing this in v3.0.2. Is there any chance there was a regression?

I'm pointing at an npm-installed eslint v1.3.1 on iojs v2.2.1 npm 2.11.2

Atom Packages
├── git-blame@0.4.5
├── git-plus@5.4.7
├── language-babel@0.13.5
├── linter@1.5.1
├── pigments@0.14.0
├── ruby-block-converter@3.5.0
├── ruby-syntax-replacer@0.4.0
└── toggle-quotes@0.11.3

**Comment by jameswlane** [comment]
I am also seeing this.
`EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".`
```
EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".
  at Function (native)
  at Function.line.toFunction (C:\Users\user\.atom\packages\linter-eslint\node_modules\eslint\node_modules\is-my-json-valid\node_modules\generate-function\index.js:55:21)
  at compile (C:\Users\user\.atom\packages\linter-eslint\node_modules\eslint\node_modules\is-my-json-valid\index.js:543:23)
  at visit (C:\Users\user\.atom\packages\linter-eslint\node_modules\eslint\node_modules\is-my-json-valid\index.js:326:16)
  at C:\Users\user\.atom\packages\linter-eslint\node_modules\eslint\node_modules\is-my-json-valid\index.js:523:9
  at Array.forEach (native)
  at visit (C:\Users\user\.atom\packages\linter-eslint\node_modules\eslint\node_modules\is-my-json-valid\index.js:520:31)
  at compile (C:\Users\user\.atom\packages\linter-eslint\node_modules\eslint\node_modules\is-my-json-valid\index.js:537:3)
  at module.exports (C:\Users\user\.atom\packages\linter-eslint\node_modules\eslint\node_modules\is-my-json-valid\index.js:564:10)
  at Object.<anonymous> (C:\Users\user\.atom\packages\linter-eslint\node_modules\eslint\lib\testers\rule-tester.js:79:22)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .js] (C:\Users\user\AppData\Local\atom\app-1.1.0\resources\app.asar\src\compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (C:\Users\user\.atom\packages\linter-eslint\node_modules\eslint\lib\api.js:11:17)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .js] (C:\Users\user\AppData\Local\atom\app-1.1.0\resources\app.asar\src\compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.module.exports.requireESLint (C:\Users\user\.atom\packages\linter-eslint\lib\linter-eslint.coffee:220:12)
  at Object.provider.lint (C:\Users\user\.atom\packages\linter-eslint\lib\linter-eslint.coffee:96:32)
  at promises.push.Promise.then._this.emitter.emit.linter (C:\Users\user\.atom\packages\linter\lib\linter-registry.js:95:28)
  at C:\Users\user\.atom\packages\linter\lib\linter-registry.js:94:25
  at Set.forEach (native)
  at LinterRegistry.lint (C:\Users\user\.atom\packages\linter\lib\linter-registry.js:92:20)
  at C:\Users\user\.atom\packages\linter\lib\linter.coffee:88:16
  at Emitter.module.exports.Emitter.emit (C:\Users\user\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
  at C:\Users\user\.atom\packages\linter\lib\editor-linter.js:100:23
  at C:\Users\user\.atom\packages\linter\lib\helpers.coffee:23:18
```

**Comment by Qard** [comment]
Same here. Just got this after the latest update.

**Comment by axefrog** [comment]
Same issue. Windows 10, eslint installed globally.

**Comment by mongris** [comment]
Same here.
linter-eslint 4.0.0
eslint 1.8.0

**Comment by davelnewton** [comment]
And here, I think after my ElCap update.

**Comment by JoeNoPhoto** [comment]
+1

**Comment by agierlicki** [comment]
I had this error too on ElCap with the current Atom (1.1.0), linter-eslint 4.0.0 and an old eslint version (1.4.1).
I just updated my eslint to v1.9.0 and the error went away. Maybe this will also help you guys.

**Comment by iwazaru** [comment]
I'm having this problem even with eslint 1.9.0 installed (OS X 10.11.1 , Atom 1.1.0, linter-eslint 4.0.0).

**Comment by JoeNoPhoto** [comment]
(OS X 10.11.1 , Atom 1.1.0, linter-eslint 4.0.0) still recieving the error after 1.9.0 eslint update.

**Comment by mads379** [comment]
Works for me. linter-eslint 4.0.0, eslint 1.9.0 and I've set the Global Node Path to `/usr/local`

**Comment by rvlander** [comment]
Add the same error. Just updated eslint and it works now:
```bash
npm install -g eslint
```

**Comment by mcgilly17** [comment]
Same issue:  eslint 1.9.0 installed (OS X 10.11.1 , Atom 1.1.0, linter-eslint 4.0.0, npm 3.3.12)

**Comment by dilizarov** [comment]
+1

**Comment by michelecos** [comment]
Installed today in Atom and have the same problem.

**Comment by sahiltalwar88** [comment]
Same problem here as well.

**Comment by marcio** [comment]
+1

**Comment by SpainTrain** [comment]
If you are experiencing this error:

1. __Try reinstalling eslint__ (whether local to project or global)
2. If issue persists, please provide environment details in the __active__ discussion https://github.com/AtomLinter/linter-eslint/issues/210

(locking this issue to centralize discussion)
